-- 001: CMS, account status and auditable administration (additive)
create extension if not exists pgcrypto;

create or replace function public.btv_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;

create or replace function public.btv_is_premium()
returns boolean language sql stable security definer set search_path=public
as $$ select public.btv_is_admin() or exists(select 1 from public.profiles where id=auth.uid() and account_type='premium') $$;

create table if not exists public.user_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'active' check(status in ('active','suspended')),
  reason text,
  suspended_at timestamptz,
  suspended_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id), action text not null,
  target_type text not null, target_id text, details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.content_categories (
  id uuid primary key default gen_random_uuid(), name text not null,
  slug text not null unique, content_type text not null,
  description text, is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(), title text not null,
  slug text not null unique, summary text not null default '', body text not null,
  country text, profession text, category text, featured_image_url text,
  access_level text not null default 'free' check(access_level in ('free','premium')),
  status text not null default 'draft' check(status in ('draft','published','archived')),
  author_id uuid references auth.users(id), published_at timestamptz,
  view_count bigint not null default 0, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.learning_resources (
  id uuid primary key default gen_random_uuid(), title text not null,
  description text not null default '', resource_type text not null check(resource_type in ('video','pdf','link','document')),
  country text, exam text, category text, thumbnail_url text, external_url text,
  storage_path text, mime_type text, size_bytes bigint,
  access_level text not null default 'free' check(access_level in ('free','premium')),
  status text not null default 'draft' check(status in ('draft','published','archived')),
  created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check(external_url is not null or storage_path is not null)
);
create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(), title text not null, body text not null,
  target_type text not null default 'all' check(target_type in ('all','premium','country','exam','users')),
  target_value text, target_user_ids uuid[] not null default '{}',
  status text not null default 'draft' check(status in ('draft','scheduled','published','archived')),
  scheduled_at timestamptz, published_at timestamptz, created_by uuid references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.announcement_reads (
  announcement_id uuid references public.announcements(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(), primary key(announcement_id,user_id)
);
create table if not exists public.reported_questions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  exam_type text not null check(exam_type in ('cbt','nclex')), question_id bigint not null,
  reason text not null, details text,
  status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')),
  reviewed_by uuid references auth.users(id), reviewed_at timestamptz,
  created_at timestamptz not null default now(), unique(user_id,exam_type,question_id,reason)
);

alter table if exists public.cbt_questions add column if not exists question_type text not null default 'single';
alter table if exists public.cbt_questions add column if not exists review_status text not null default 'reviewed';
alter table if exists public.cbt_questions add column if not exists source_hash text;
alter table if exists public.nclex_questions add column if not exists review_status text not null default 'reviewed';
alter table if exists public.nclex_questions add column if not exists source_hash text;
drop index if exists public.cbt_questions_source_hash_uidx;
drop index if exists public.nclex_questions_source_hash_uidx;
create unique index cbt_questions_source_hash_uidx on public.cbt_questions(source_hash);
create unique index nclex_questions_source_hash_uidx on public.nclex_questions(source_hash);
create index if not exists articles_lookup_idx on public.articles(status,country,profession,category,published_at desc);
create index if not exists resources_lookup_idx on public.learning_resources(status,country,exam,category);
create index if not exists announcements_schedule_idx on public.announcements(status,scheduled_at);
create index if not exists audit_created_idx on public.admin_audit_logs(created_at desc);
create index if not exists reports_status_idx on public.reported_questions(status,exam_type,created_at desc);

alter table public.user_status enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.content_categories enable row level security;
alter table public.articles enable row level security;
alter table public.learning_resources enable row level security;
alter table public.announcements enable row level security;
alter table public.announcement_reads enable row level security;
alter table public.reported_questions enable row level security;

drop policy if exists "status owner or admin" on public.user_status;
create policy "status owner or admin" on public.user_status for select to authenticated using(user_id=auth.uid() or public.btv_is_admin());
drop policy if exists "audit admin read" on public.admin_audit_logs;
create policy "audit admin read" on public.admin_audit_logs for select to authenticated using(public.btv_is_admin());
drop policy if exists "categories authenticated read" on public.content_categories;
create policy "categories authenticated read" on public.content_categories for select to authenticated using(is_active or public.btv_is_admin());
drop policy if exists "categories admin write" on public.content_categories;
create policy "categories admin write" on public.content_categories for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "articles audience read" on public.articles;
create policy "articles audience read" on public.articles for select to authenticated using(public.btv_is_admin() or (status='published' and (access_level='free' or public.btv_is_premium())));
drop policy if exists "articles admin write" on public.articles;
create policy "articles admin write" on public.articles for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "resources audience read" on public.learning_resources;
create policy "resources audience read" on public.learning_resources for select to authenticated using(public.btv_is_admin() or (status='published' and (access_level='free' or public.btv_is_premium())));
drop policy if exists "resources admin write" on public.learning_resources;
create policy "resources admin write" on public.learning_resources for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "announcements audience read" on public.announcements;
create policy "announcements audience read" on public.announcements for select to authenticated using(
 public.btv_is_admin() or (status='published' and (target_type='all'
 or (target_type='premium' and public.btv_is_premium())
 or (target_type='users' and auth.uid()=any(target_user_ids))
 or (target_type='country' and target_value=(select destination from public.profiles where id=auth.uid())))));
drop policy if exists "announcements admin write" on public.announcements;
create policy "announcements admin write" on public.announcements for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "reads owner" on public.announcement_reads;
create policy "reads owner" on public.announcement_reads for all to authenticated using(user_id=auth.uid() or public.btv_is_admin()) with check(user_id=auth.uid() or public.btv_is_admin());
drop policy if exists "reports owner insert" on public.reported_questions;
create policy "reports owner insert" on public.reported_questions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "reports admin manage" on public.reported_questions;
create policy "reports admin manage" on public.reported_questions for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());

create or replace function public.admin_set_user_access(p_user uuid,p_plan text,p_status text,p_reason text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.btv_is_admin() then raise exception 'Administrator access required'; end if;
 if p_plan not in ('free','premium') or p_status not in ('active','suspended') then raise exception 'Invalid access value'; end if;
 update public.profiles set account_type=p_plan,updated_at=now() where id=p_user and role<>'admin';
 insert into public.user_status(user_id,status,reason,suspended_at,suspended_by,updated_at)
 values(p_user,p_status,p_reason,case when p_status='suspended' then now() end,case when p_status='suspended' then auth.uid() end,now())
 on conflict(user_id) do update set status=excluded.status,reason=excluded.reason,suspended_at=excluded.suspended_at,suspended_by=excluded.suspended_by,updated_at=now();
 insert into public.admin_audit_logs(admin_id,action,target_type,target_id,details)
 values(auth.uid(),'set_user_access','user',p_user::text,jsonb_build_object('plan',p_plan,'status',p_status,'reason',p_reason));
end $$;

create or replace function public.admin_list_users(p_search text default '',p_plan text default null,p_status text default null,p_limit int default 50,p_offset int default 0)
returns table(id uuid,email text,full_name text,profession text,destination text,account_type text,role text,status text,created_at timestamptz,last_sign_in_at timestamptz)
language sql security definer set search_path=public,auth as $$
 select p.id,u.email,p.full_name,p.profession,p.destination,p.account_type,p.role,coalesce(s.status,'active'),p.created_at,u.last_sign_in_at
 from public.profiles p join auth.users u on u.id=p.id left join public.user_status s on s.user_id=p.id
 where public.btv_is_admin()
 and (p_search='' or coalesce(p.full_name,'') ilike '%'||p_search||'%' or coalesce(u.email,'') ilike '%'||p_search||'%')
 and (p_plan is null or p.account_type=p_plan) and (p_status is null or coalesce(s.status,'active')=p_status)
 order by p.created_at desc limit least(greatest(p_limit,1),200) offset greatest(p_offset,0)
$$;
revoke all on function public.admin_list_users(text,text,text,int,int) from public;
grant execute on function public.admin_list_users(text,text,text,int,int) to authenticated;

create or replace function public.btv_audit_admin_change()
returns trigger language plpgsql security definer set search_path=public as $$
declare row_data jsonb;
begin
 row_data:=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
 if auth.uid() is not null and public.btv_is_admin() then
  insert into public.admin_audit_logs(admin_id,action,target_type,target_id,details)
  values(auth.uid(),lower(tg_op),tg_table_name,coalesce(row_data->>'id',row_data->>'user_id'),jsonb_build_object('operation',tg_op));
 end if;if tg_op='DELETE' then return old;end if;return new;
end $$;
do $$ declare t text; begin
 foreach t in array array['content_categories','articles','learning_resources','announcements','reported_questions','cbt_questions','nclex_questions'] loop
  execute format('drop trigger if exists btv_admin_audit on public.%I',t);
  execute format('create trigger btv_admin_audit after insert or update or delete on public.%I for each row execute function public.btv_audit_admin_change()',t);
 end loop;
end $$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('learning-media','learning-media',false,52428800,array['image/jpeg','image/png','image/webp','application/pdf','text/vtt'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "learning media admin manage" on storage.objects;
create policy "learning media admin manage" on storage.objects for all to authenticated using(bucket_id='learning-media' and public.btv_is_admin()) with check(bucket_id='learning-media' and public.btv_is_admin());
