-- 002: in-app and browser push notifications
create table if not exists public.notification_preferences (
 user_id uuid primary key references auth.users(id) on delete cascade,
 push_enabled boolean not null default false, email_enabled boolean not null default true,
 categories jsonb not null default '{"cbt":true,"nclex":true,"study":true,"journey":true,"documents":true,"bookings":true,"payments":true,"subscriptions":true,"content":true,"announcements":true}',
 timezone text not null default 'UTC', quiet_start time, quiet_end time, updated_at timestamptz not null default now()
);
create table if not exists public.notifications (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 category text not null, title text not null, body text not null, action_url text,
 data jsonb not null default '{}', read_at timestamptz, scheduled_at timestamptz,
 delivered_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.push_subscriptions (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 endpoint text not null unique, p256dh text not null, auth_key text not null,
 user_agent text, enabled boolean not null default true, last_used_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.notification_delivery_logs (
 id bigint generated by default as identity primary key, notification_id uuid references public.notifications(id) on delete cascade,
 subscription_id uuid references public.push_subscriptions(id) on delete set null,
 channel text not null check(channel in ('push','in_app','email')), status text not null,
 provider_response text, attempted_at timestamptz not null default now()
);
create index if not exists notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;
create index if not exists notifications_schedule_idx on public.notifications(scheduled_at) where delivered_at is null;
create index if not exists push_user_idx on public.push_subscriptions(user_id,enabled);
alter table public.notification_preferences enable row level security;
alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_delivery_logs enable row level security;
drop policy if exists "preferences owner" on public.notification_preferences;
create policy "preferences owner" on public.notification_preferences for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "notifications owner read" on public.notifications;
create policy "notifications owner read" on public.notifications for select to authenticated using(user_id=auth.uid() or public.btv_is_admin());
drop policy if exists "notifications owner update" on public.notifications;
create policy "notifications owner update" on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "notifications admin create" on public.notifications;
create policy "notifications admin create" on public.notifications for insert to authenticated with check(public.btv_is_admin());
drop policy if exists "subscriptions owner" on public.push_subscriptions;
create policy "subscriptions owner" on public.push_subscriptions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "delivery admin read" on public.notification_delivery_logs;
create policy "delivery admin read" on public.notification_delivery_logs for select to authenticated using(public.btv_is_admin());
create or replace function public.mark_all_notifications_read()
returns int language plpgsql security invoker set search_path=public as $$ declare n int; begin
 update public.notifications set read_at=now() where user_id=auth.uid() and read_at is null; get diagnostics n=row_count; return n;
end $$;
