-- 004: transactional booking system
create extension if not exists btree_gist;
create table if not exists public.booking_services (
 id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique,
 description text not null default '', duration_minutes int not null check(duration_minutes between 10 and 480),
 buffer_minutes int not null default 0 check(buffer_minutes between 0 and 180),
 price_minor int not null default 0 check(price_minor>=0), currency text not null default 'GHS',
 cancellation_hours int not null default 24, reschedule_hours int not null default 24,
 max_bookings_per_slot int not null default 1 check(max_bookings_per_slot between 1 and 100),
 is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.availability_rules (
 id uuid primary key default gen_random_uuid(), service_id uuid references public.booking_services(id) on delete cascade,
 weekday int not null check(weekday between 0 and 6), start_time time not null, end_time time not null,
 timezone text not null default 'Europe/London', valid_from date, valid_until date, is_active boolean not null default true,
 check(start_time<end_time)
);
create table if not exists public.blocked_dates (
 id uuid primary key default gen_random_uuid(), service_id uuid references public.booking_services(id) on delete cascade,
 starts_at timestamptz not null, ends_at timestamptz not null, reason text, check(starts_at<ends_at)
);
create table if not exists public.bookings (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 service_id uuid not null references public.booking_services(id), starts_at timestamptz not null, ends_at timestamptz not null,
 customer_name text not null, customer_email text not null, role_band text, notes text,
 status text not null default 'pending_payment' check(status in ('pending_payment','confirmed','cancelled','completed','no_show')),
 payment_status text not null default 'not_required' check(payment_status in ('not_required','pending','paid','failed','refunded')),
 meeting_provider text, meeting_url text, admin_notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(starts_at<ends_at)
);
create table if not exists public.booking_payments (
 id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id) on delete cascade,
 paystack_reference text not null unique, amount_minor int not null, currency text not null,
 status text not null default 'pending' check(status in ('pending','successful','failed','refunded')),
 verified_at timestamptz, provider_payload jsonb not null default '{}', created_at timestamptz not null default now()
);
create table if not exists public.booking_status_history (
 id bigint generated by default as identity primary key, booking_id uuid not null references public.bookings(id) on delete cascade,
 from_status text, to_status text not null, changed_by uuid references auth.users(id), note text, created_at timestamptz not null default now()
);
create unique index if not exists bookings_active_slot_uidx on public.bookings(service_id,starts_at) where status in ('pending_payment','confirmed');
do $$ begin
 alter table public.bookings add constraint bookings_no_active_overlap exclude using gist
 (service_id with =,tstzrange(starts_at,ends_at,'[)') with &&) where (status in ('pending_payment','confirmed'));
exception when duplicate_object then null; end $$;
create index if not exists bookings_user_idx on public.bookings(user_id,starts_at desc);
create index if not exists bookings_admin_idx on public.bookings(status,starts_at);
create index if not exists availability_service_idx on public.availability_rules(service_id,weekday,is_active);
alter table public.booking_services enable row level security;
alter table public.availability_rules enable row level security;
alter table public.blocked_dates enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_payments enable row level security;
alter table public.booking_status_history enable row level security;
drop policy if exists "services authenticated read" on public.booking_services;
create policy "services authenticated read" on public.booking_services for select to authenticated using(is_active or public.btv_is_admin());
drop policy if exists "services admin write" on public.booking_services;
create policy "services admin write" on public.booking_services for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "availability authenticated read" on public.availability_rules;
create policy "availability authenticated read" on public.availability_rules for select to authenticated using(is_active or public.btv_is_admin());
drop policy if exists "availability admin write" on public.availability_rules;
create policy "availability admin write" on public.availability_rules for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "blocks authenticated read" on public.blocked_dates;
create policy "blocks authenticated read" on public.blocked_dates for select to authenticated using(true);
drop policy if exists "blocks admin write" on public.blocked_dates;
create policy "blocks admin write" on public.blocked_dates for all to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "bookings owner read" on public.bookings;
create policy "bookings owner read" on public.bookings for select to authenticated using(user_id=auth.uid() or public.btv_is_admin());
drop policy if exists "bookings admin update" on public.bookings;
create policy "bookings admin update" on public.bookings for update to authenticated using(public.btv_is_admin()) with check(public.btv_is_admin());
drop policy if exists "booking payments owner read" on public.booking_payments;
create policy "booking payments owner read" on public.booking_payments for select to authenticated using(public.btv_is_admin() or exists(select 1 from public.bookings b where b.id=booking_id and b.user_id=auth.uid()));
drop policy if exists "history owner read" on public.booking_status_history;
create policy "history owner read" on public.booking_status_history for select to authenticated using(public.btv_is_admin() or exists(select 1 from public.bookings b where b.id=booking_id and b.user_id=auth.uid()));
drop policy if exists "history admin write" on public.booking_status_history;
create policy "history admin write" on public.booking_status_history for insert to authenticated with check(public.btv_is_admin());
do $$ declare t text; begin foreach t in array array['booking_services','availability_rules','blocked_dates','bookings'] loop execute format('drop trigger if exists btv_admin_audit on public.%I',t);execute format('create trigger btv_admin_audit after insert or update or delete on public.%I for each row execute function public.btv_audit_admin_change()',t);end loop;end $$;

create or replace function public.create_booking(p_service uuid,p_starts timestamptz,p_name text,p_email text,p_role text default null,p_notes text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare s public.booking_services; new_id uuid; finish timestamptz; blocked boolean; available boolean;
begin
 if auth.uid() is null then raise exception 'Sign in required'; end if;
 select * into s from public.booking_services where id=p_service and is_active for share;
 if not found then raise exception 'Service unavailable'; end if;
 if p_starts<=now() then raise exception 'Choose a future time'; end if;
 finish:=p_starts+make_interval(mins=>s.duration_minutes);
 select exists(select 1 from public.availability_rules r where r.service_id=p_service and r.is_active
   and extract(dow from (p_starts at time zone r.timezone))::int=r.weekday
   and (r.valid_from is null or (p_starts at time zone r.timezone)::date>=r.valid_from)
   and (r.valid_until is null or (p_starts at time zone r.timezone)::date<=r.valid_until)
   and (p_starts at time zone r.timezone)::time>=r.start_time
   and (finish at time zone r.timezone)::time<=r.end_time) into available;
 if not available then raise exception 'Choose a time within the published availability.'; end if;
 select exists(select 1 from public.blocked_dates d where (d.service_id is null or d.service_id=p_service) and tstzrange(d.starts_at,d.ends_at,'[)') && tstzrange(p_starts,finish,'[)')) into blocked;
 if blocked then raise exception 'This time is unavailable'; end if;
 begin
  insert into public.bookings(user_id,service_id,starts_at,ends_at,customer_name,customer_email,role_band,notes,status,payment_status)
  values(auth.uid(),p_service,p_starts,finish,trim(p_name),lower(trim(p_email)),p_role,p_notes,case when s.price_minor=0 then 'confirmed' else 'pending_payment' end,case when s.price_minor=0 then 'not_required' else 'pending' end)
  returning id into new_id;
 exception when unique_violation then raise exception 'That slot was just booked. Please choose another.';
 end;
 insert into public.booking_status_history(booking_id,to_status,changed_by,note) values(new_id,case when s.price_minor=0 then 'confirmed' else 'pending_payment' end,auth.uid(),'Booking created');
 if s.price_minor=0 then insert into public.notifications(user_id,category,title,body,action_url) values(auth.uid(),'bookings','Booking confirmed','Your free booking has been confirmed.','#bookingCentre'); end if;
 return new_id;
end $$;

create or replace function public.manage_own_booking(p_booking uuid,p_action text,p_new_start timestamptz default null)
returns void language plpgsql security definer set search_path=public as $$
declare b public.bookings;s public.booking_services;new_end timestamptz;
begin
 select * into b from public.bookings where id=p_booking and user_id=auth.uid() for update;
 if not found then raise exception 'Booking not found'; end if;
 select * into s from public.booking_services where id=b.service_id;
 if b.status not in ('pending_payment','confirmed') then raise exception 'This booking can no longer be changed'; end if;
 if p_action='cancel' then
  if now()>b.starts_at-make_interval(hours=>s.cancellation_hours) then raise exception 'The cancellation deadline has passed'; end if;
  update public.bookings set status='cancelled',updated_at=now() where id=b.id;
  insert into public.booking_status_history(booking_id,from_status,to_status,changed_by,note) values(b.id,b.status,'cancelled',auth.uid(),'Cancelled by user');
 elsif p_action='reschedule' then
  if p_new_start is null or now()>b.starts_at-make_interval(hours=>s.reschedule_hours) then raise exception 'The reschedule deadline has passed'; end if;
  new_end:=p_new_start+make_interval(mins=>s.duration_minutes);
  update public.bookings set starts_at=p_new_start,ends_at=new_end,updated_at=now() where id=b.id;
  insert into public.booking_status_history(booking_id,from_status,to_status,changed_by,note) values(b.id,b.status,b.status,auth.uid(),'Rescheduled by user');
 else raise exception 'Invalid booking action'; end if;
exception when exclusion_violation or unique_violation then raise exception 'That slot is no longer available';
end $$;
