-- Beyond The Visa CBT Learning + Mock Exam database
-- Run once in Supabase SQL Editor after the profiles setup.

create table if not exists public.cbt_questions (
  id bigint generated by default as identity primary key,
  profession text not null check (profession in ('nurse','midwife')),
  category text not null,
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null check (correct_answer in ('A','B','C','D')),
  explanation text not null,
  is_premium boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cbt_exam_sessions (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profession text not null,
  question_count integer not null,
  total_questions integer not null,
  score integer not null default 0,
  percentage numeric(5,2) not null default 0,
  duration_seconds integer not null default 0,
  status text not null default 'completed' check (status in ('in_progress','completed','abandoned')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.cbt_attempts (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.cbt_questions(id) on delete cascade,
  selected_answer text check (selected_answer in ('A','B','C','D')),
  is_correct boolean not null,
  category text not null,
  mode text not null default 'practice' check (mode in ('practice','mock')),
  exam_session_id bigint references public.cbt_exam_sessions(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.cbt_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.cbt_questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id,question_id)
);

alter table public.cbt_questions enable row level security;
alter table public.cbt_exam_sessions enable row level security;
alter table public.cbt_attempts enable row level security;
alter table public.cbt_bookmarks enable row level security;

drop policy if exists "Authenticated users read active CBT questions" on public.cbt_questions;
create policy "Authenticated users read active CBT questions" on public.cbt_questions for select to authenticated using (is_active = true);

drop policy if exists "Users read own CBT exams" on public.cbt_exam_sessions;
create policy "Users read own CBT exams" on public.cbt_exam_sessions for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users create own CBT exams" on public.cbt_exam_sessions;
create policy "Users create own CBT exams" on public.cbt_exam_sessions for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users update own CBT exams" on public.cbt_exam_sessions;
create policy "Users update own CBT exams" on public.cbt_exam_sessions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users read own CBT attempts" on public.cbt_attempts;
create policy "Users read own CBT attempts" on public.cbt_attempts for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users create own CBT attempts" on public.cbt_attempts;
create policy "Users create own CBT attempts" on public.cbt_attempts for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own CBT bookmarks" on public.cbt_bookmarks;
create policy "Users manage own CBT bookmarks" on public.cbt_bookmarks for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- Starter nurse question bank. Replace or expand with clinically reviewed content before commercial launch.
insert into public.cbt_questions (profession,category,difficulty,question,option_a,option_b,option_c,option_d,correct_answer,explanation,is_premium)
select * from (values
('nurse','Professional values','easy','A patient asks you to discuss another patient’s diagnosis. What is the most appropriate response?','Share only general information','Explain that you cannot disclose another patient’s confidential information','Ask a colleague to answer','Discuss it after the shift','B','Confidential information must only be shared when there is a lawful and professionally justified reason.',false),
('nurse','Patient safety','easy','You notice that a prescribed medicine dose appears unusually high. What should you do first?','Administer it because it is prescribed','Withhold it permanently without telling anyone','Check the prescription and clarify the dose with an appropriate prescriber or pharmacist','Ask the patient whether they usually take it','C','A possible prescribing error should be checked and escalated before administration to prevent avoidable harm.',false),
('nurse','Infection prevention','easy','Which action is most important before and after direct patient contact?','Wear an apron at all times','Perform effective hand hygiene','Change the bed linen','Open a window','B','Hand hygiene is a core measure for reducing transmission of microorganisms during care.',false),
('nurse','Communication','medium','A patient has limited English and needs to consent to a procedure. What is the best approach?','Use a child relative to translate','Use an appropriate professional interpreting service','Ask the patient to sign and explain later','Cancel all care indefinitely','B','Professional interpretation supports informed consent, accuracy and confidentiality.',false),
('nurse','Safeguarding','medium','An adult patient tells you they are frightened of the person who cares for them at home. What should you do?','Promise to keep it secret','Record the concern and follow the safeguarding escalation process','Confront the alleged person immediately','Ignore it unless there is physical injury','B','Safeguarding concerns require accurate documentation and prompt action through local procedures; absolute secrecy should not be promised.',false),
('nurse','Deteriorating patient','medium','A patient suddenly becomes confused, tachycardic and hypotensive. What is your immediate priority?','Wait for the next routine observations','Complete an ABCDE assessment and escalate urgently','Offer a hot drink','Document it at the end of the shift','B','Sudden physiological deterioration requires systematic assessment, immediate escalation and time-critical treatment.',false),
('nurse','Medicines management','medium','A patient refuses a prescribed medicine. What is the most appropriate action?','Hide it in food','Respect the refusal, explore the reason, explain relevant information and document/escalate appropriately','Ask another nurse to force the patient','Record it as administered','B','A capable patient may refuse treatment. The nurse should provide information, assess concerns, document accurately and escalate when needed.',false),
('nurse','Documentation','easy','Which documentation entry is most appropriate?','Patient seems difficult','Patient complained all morning','At 10:15 patient reported pain 7/10 in lower abdomen; prescribed analgesia given and response reviewed','Everything normal','C','Records should be timely, factual, specific and include assessment, action and outcome.',false),
('nurse','Delegation','medium','When delegating a task to a healthcare assistant, the registered nurse remains responsible for:','Doing every part of the task personally','Ensuring the delegation is appropriate and that the person is competent and supported','Allowing the assistant to change the care plan independently','Avoiding all follow-up','B','Delegation requires assessment of the task, patient, competence, supervision and outcome.',false),
('nurse','Consent','medium','A patient with capacity changes their mind immediately before a procedure. What should happen?','Proceed because the form is signed','Respect the withdrawal of consent and inform the relevant team','Ask the family to overrule them','Sedate the patient','B','Consent is an ongoing process and a person with capacity can withdraw it at any time.',false),
('nurse','Nutrition and hydration','easy','Which finding may indicate dehydration?','Increased urine output and moist mucosa','Dry mucous membranes and reduced urine output','Low temperature only','Improved skin elasticity','B','Dry mucosa, reduced urine output, thirst, tachycardia and hypotension may indicate dehydration.',false),
('nurse','Pressure area care','medium','What is the best approach for a patient at risk of pressure damage?','Massage reddened skin firmly','Use an individualised prevention plan including repositioning, skin assessment and appropriate support surfaces','Keep the patient sitting in one position','Reduce fluid intake','B','Pressure injury prevention combines risk assessment, repositioning, skin care, nutrition and suitable equipment.',false),
('nurse','Pain assessment','easy','A patient says their pain is severe although they appear comfortable. What should the nurse do?','Ignore the report because appearance is normal','Accept the patient’s report, assess comprehensively and respond appropriately','Tell the patient to wait until they look distressed','Document only the nurse’s impression','B','Pain is subjective and the patient’s report should be taken seriously alongside a full assessment.',false),
('nurse','Mental health','medium','A patient says they intend to end their life tonight and has a plan. What is the priority?','Leave them alone to calm down','Take the disclosure seriously, maintain safety and obtain urgent specialist/medical support','Promise not to tell anyone','Ask them to return next week','B','A stated plan and intent indicate immediate risk requiring urgent safety measures and escalation.',false),
('nurse','End of life care','medium','A dying patient’s family asks why noisy respiratory secretions are occurring. What is the best response?','Tell them the patient is choking','Explain sensitively that secretions can occur near the end of life, assess comfort and follow the care plan','Avoid answering','Begin aggressive suction automatically','B','Clear, compassionate explanation and symptom-focused assessment support the patient and family.',false),
('nurse','Deteriorating patient','hard','During an ABCDE assessment, which problem should generally be addressed first?','A low appetite','A threatened airway','A missed outpatient appointment','A long-term skin condition','B','Life-threatening airway problems take priority in the ABCDE approach.',true),
('nurse','Infection prevention','medium','A patient has suspected infectious diarrhoea. Which action is most appropriate?','Use alcohol hand rub only after care','Follow isolation precautions and wash hands with soap and water when indicated','Move the patient through shared areas','Share equipment without cleaning','B','Contact precautions, appropriate isolation, environmental cleaning and soap-and-water handwashing are important for some diarrhoeal pathogens.',true),
('nurse','Medicines management','hard','You discover that a medicine was administered to the wrong patient. What should happen first?','Alter the record','Assess the patient and obtain urgent clinical advice while following incident and duty-of-candour procedures','Wait to see whether symptoms develop','Ask the patient not to mention it','B','Immediate patient assessment and clinical escalation come first, followed by transparent reporting, documentation and learning.',true),
('nurse','Professional values','medium','A colleague posts a photograph from a clinical area on social media and a patient can be identified. What should you do?','Like the post','Ignore it because it is outside work','Act promptly through appropriate reporting and safeguarding/confidentiality processes','Share it privately','C','Identifiable patient information on social media is a serious confidentiality and professionalism concern requiring prompt action.',true),
('nurse','Communication','medium','A distressed relative becomes verbally aggressive. What is the best initial response?','Shout back','Use calm communication, maintain safety, acknowledge concerns and seek support if risk escalates','Immediately disclose confidential details','Walk away without explanation','B','De-escalation begins with calm, respectful communication and attention to safety and boundaries.',true),
('midwife','Professional values','easy','A woman asks you to share another service user’s birth details. What should you do?','Share only the baby’s weight','Explain that you cannot disclose confidential information','Ask a student to answer','Post a general summary online','B','Confidentiality applies to maternity care and identifiable information must not be disclosed without a lawful basis.',false),
('midwife','Maternal deterioration','medium','A postpartum woman has heavy bleeding, tachycardia and feels faint. What is the priority?','Offer food and reassess later','Initiate emergency assessment and escalation for suspected postpartum haemorrhage','Encourage her to walk','Complete discharge paperwork','B','Postpartum haemorrhage can rapidly become life-threatening and requires immediate emergency management.',false),
('midwife','Newborn care','easy','Which observation in a newborn requires urgent assessment?','Brief hiccups','Central cyanosis','Sneezing once','Sleeping after a feed','B','Central cyanosis may indicate inadequate oxygenation and requires urgent assessment.',false),
('midwife','Consent','medium','A woman with capacity declines a recommended vaginal examination in labour. What should the midwife do?','Perform it because it is clinically recommended','Respect the decision, explain options and document the discussion','Ask her partner to consent','Threaten to withdraw care','B','A person with capacity can refuse an examination. Care should remain respectful, informed and documented.',false),
('midwife','Safeguarding','medium','You are concerned that a pregnant teenager is being exploited. What should you do?','Keep the concern to yourself','Follow safeguarding procedures and escalate promptly','Question the suspected person alone','Wait until after birth','B','Possible exploitation requires prompt safeguarding action in line with local policy.',false),
('midwife','Infant feeding','easy','What is an appropriate response when a mother asks for help with breastfeeding?','Give the same instruction to everyone','Observe a feed with consent and provide individualised, evidence-based support','Tell her pain is always normal','Recommend stopping immediately','B','Skilled, respectful assessment helps identify positioning, attachment and individual support needs.',false),
('midwife','Infection prevention','easy','Before examining a newborn, the midwife should first:','Put on two pairs of gloves for every contact','Perform hand hygiene','Change the cot mattress','Give antibiotics','B','Hand hygiene is essential before and after contact with the newborn.',false),
('midwife','Maternal deterioration','hard','A pregnant woman at 34 weeks reports severe headache, visual disturbance and epigastric pain. What is the priority?','Routine review next week','Urgent assessment and escalation for possible severe pre-eclampsia','Advise sleep only','Encourage strenuous exercise','B','These symptoms may indicate severe pre-eclampsia and require urgent maternal and fetal assessment.',true),
('midwife','Fetal wellbeing','medium','A woman reports significantly reduced fetal movements. What is the best advice?','Wait several days','Seek prompt maternity assessment according to local guidance','Drink coffee and ignore it','Only attend if labour starts','B','Reduced fetal movement warrants prompt assessment because it can be associated with fetal compromise.',true),
('midwife','Documentation','easy','Which maternity record entry is best?','Mother fine','At 14:20 fetal heart rate assessed at 140 bpm; maternal observations documented and plan discussed','No concerns probably','Routine care done','B','Clinical records should be objective, timely, clear and sufficiently detailed.',false)
) as v(profession,category,difficulty,question,option_a,option_b,option_c,option_d,correct_answer,explanation,is_premium)
where not exists (select 1 from public.cbt_questions);
