-- Beyond The Visa CBT + Mock Exam database
-- Run this entire file once in Supabase: SQL Editor > New query > Run

create table if not exists public.cbt_questions (
  id bigint generated by default as identity primary key,
  profession text not null default 'nurse' check (profession in ('nurse','midwife','both')),
  subject text not null,
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('A','B','C','D')),
  explanation text not null,
  access_level text not null default 'free' check (access_level in ('free','premium')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cbt_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.cbt_questions(id) on delete cascade,
  selected_option text not null check (selected_option in ('A','B','C','D')),
  is_correct boolean not null,
  mode text not null default 'practice' check (mode in ('practice','mock')),
  attempted_at timestamptz not null default now()
);

create table if not exists public.cbt_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.cbt_questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

create table if not exists public.mock_exam_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profession text not null default 'nurse',
  total_questions integer not null,
  correct_answers integer not null,
  percentage numeric(5,2) not null,
  duration_seconds integer not null default 0,
  completed_at timestamptz not null default now()
);

alter table public.cbt_questions enable row level security;
alter table public.cbt_attempts enable row level security;
alter table public.cbt_bookmarks enable row level security;
alter table public.mock_exam_results enable row level security;

drop policy if exists "Authenticated users read active CBT questions" on public.cbt_questions;
create policy "Authenticated users read active CBT questions"
on public.cbt_questions for select to authenticated
using (is_active = true);

drop policy if exists "Users read own CBT attempts" on public.cbt_attempts;
create policy "Users read own CBT attempts"
on public.cbt_attempts for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users insert own CBT attempts" on public.cbt_attempts;
create policy "Users insert own CBT attempts"
on public.cbt_attempts for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users read own CBT bookmarks" on public.cbt_bookmarks;
create policy "Users read own CBT bookmarks"
on public.cbt_bookmarks for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users add own CBT bookmarks" on public.cbt_bookmarks;
create policy "Users add own CBT bookmarks"
on public.cbt_bookmarks for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users remove own CBT bookmarks" on public.cbt_bookmarks;
create policy "Users remove own CBT bookmarks"
on public.cbt_bookmarks for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users read own mock results" on public.mock_exam_results;
create policy "Users read own mock results"
on public.mock_exam_results for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users insert own mock results" on public.mock_exam_results;
create policy "Users insert own mock results"
on public.mock_exam_results for insert to authenticated
with check ((select auth.uid()) = user_id);

-- Starter demonstration questions. Replace/expand after professional clinical review.
insert into public.cbt_questions
(profession,subject,difficulty,question_text,option_a,option_b,option_c,option_d,correct_option,explanation,access_level)
select * from (values
('nurse','Patient safety','easy','A patient suddenly becomes unresponsive. What should the nurse do first?','Document the event','Assess responsiveness and call for help','Contact the family','Complete an incident form','B','Immediate assessment and escalation come before documentation or non-urgent communication.','free'),
('nurse','Infection prevention','easy','What is the most effective routine action for reducing transmission of infection between patients?','Wearing an apron all day','Hand hygiene at the correct moments','Giving prophylactic antibiotics','Keeping windows open','B','Effective hand hygiene at the appropriate moments is a core measure for preventing cross-infection.','free'),
('nurse','Medicines management','medium','Before administering a medicine, which action best supports safe practice?','Ask another patient to identify the medicine','Check the prescription, patient identity, allergies and relevant observations','Administer it first and document later','Rely on the medicine colour','B','Safe administration requires verification of the prescription, patient, allergies and relevant clinical information.','free'),
('nurse','Deteriorating patient','medium','A patient has a respiratory rate of 30 breaths per minute and new confusion. What is the priority?','Wait until the next observation round','Escalate promptly and assess using an ABCDE approach','Offer a hot drink','Ask relatives to observe the patient','B','New confusion and marked tachypnoea may indicate acute deterioration and require immediate structured assessment and escalation.','free'),
('nurse','Communication','easy','Which response best demonstrates person-centred communication?','Use technical terminology to save time','Speak only to the relative','Check the patient’s preferred communication needs and understanding','Avoid discussing choices','C','Person-centred communication adapts to the individual and confirms understanding.','free'),
('nurse','Safeguarding','medium','A patient privately discloses possible abuse. What should the nurse do?','Promise absolute secrecy','Listen, document accurately and follow safeguarding procedures','Confront the alleged abuser alone','Post the concern in a staff group chat','B','The nurse should listen without leading, document factually and escalate through safeguarding pathways.','free'),
('midwife','Maternity safety','medium','A pregnant woman reports reduced fetal movements. What is the safest advice?','Wait until the next routine appointment','Seek prompt maternity assessment according to local guidance','Drink coffee and reassess next week','Ignore it if there is no pain','B','Reduced fetal movements require timely assessment rather than delay.','free'),
('midwife','Postnatal care','medium','A postnatal woman has heavy bleeding and feels faint. What is the priority?','Provide routine discharge advice','Call for urgent help and begin immediate assessment','Ask her to sleep','Arrange a review next month','B','Heavy bleeding with faintness may indicate postpartum haemorrhage and requires urgent escalation and assessment.','free'),
('both','Professional practice','easy','What should a registrant do after making a documentation error in a paper record?','Erase it completely','Use correction fluid','Correct it according to policy while keeping the original entry legible','Remove the page','C','Records must remain clear and auditable; corrections should follow organisational policy without obscuring the original entry.','free'),
('both','Consent','medium','An adult patient with capacity refuses a recommended treatment. What should the professional do?','Administer it covertly','Respect the refusal after ensuring the patient is informed','Ask the family to overrule the patient','Discharge the patient immediately','B','A capacitous adult can refuse treatment. The professional should ensure the decision is informed and document it appropriately.','free')
) as seed(profession,subject,difficulty,question_text,option_a,option_b,option_c,option_d,correct_option,explanation,access_level)
where not exists (select 1 from public.cbt_questions);
