-- Beyond The Visa NCLEX learning database
-- Run this entire file once in Supabase: SQL Editor > New query > Run
-- This creates an original NCLEX-style practice bank. It does not contain official exam items.

create table if not exists public.nclex_questions (
  id bigint generated by default as identity primary key,
  exam text not null default 'NCLEX-RN' check (exam in ('NCLEX-RN','NCLEX-PN')),
  category text not null,
  client_need text not null,
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  question_type text not null default 'single' check (question_type in ('single','select_all')),
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  option_e text,
  option_f text,
  correct_options text[] not null,
  rationale text not null,
  test_strategy text,
  access_level text not null default 'free' check (access_level in ('free','premium')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nclex_correct_options_valid check (
    array_length(correct_options,1) >= 1
    and correct_options <@ array['A','B','C','D','E','F']::text[]
  )
);

create table if not exists public.nclex_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.nclex_questions(id) on delete cascade,
  selected_options text[] not null,
  is_correct boolean not null,
  mode text not null default 'practice' check (mode in ('practice','adaptive','mock')),
  attempted_at timestamptz not null default now()
);

create table if not exists public.nclex_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.nclex_questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

create table if not exists public.nclex_exam_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  exam text not null default 'NCLEX-RN',
  mode text not null default 'mock' check (mode in ('mock','adaptive')),
  total_questions integer not null,
  correct_answers integer not null,
  percentage numeric(5,2) not null,
  readiness_band text not null,
  duration_seconds integer not null default 0,
  completed_at timestamptz not null default now()
);

alter table public.nclex_questions enable row level security;
alter table public.nclex_attempts enable row level security;
alter table public.nclex_bookmarks enable row level security;
alter table public.nclex_exam_results enable row level security;

drop policy if exists "Authenticated users read active NCLEX questions" on public.nclex_questions;
create policy "Authenticated users read active NCLEX questions"
on public.nclex_questions for select to authenticated
using (is_active = true);

drop policy if exists "Users read own NCLEX attempts" on public.nclex_attempts;
create policy "Users read own NCLEX attempts"
on public.nclex_attempts for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users insert own NCLEX attempts" on public.nclex_attempts;
create policy "Users insert own NCLEX attempts"
on public.nclex_attempts for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users read own NCLEX bookmarks" on public.nclex_bookmarks;
create policy "Users read own NCLEX bookmarks"
on public.nclex_bookmarks for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users add own NCLEX bookmarks" on public.nclex_bookmarks;
create policy "Users add own NCLEX bookmarks"
on public.nclex_bookmarks for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users remove own NCLEX bookmarks" on public.nclex_bookmarks;
create policy "Users remove own NCLEX bookmarks"
on public.nclex_bookmarks for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users read own NCLEX results" on public.nclex_exam_results;
create policy "Users read own NCLEX results"
on public.nclex_exam_results for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users insert own NCLEX results" on public.nclex_exam_results;
create policy "Users insert own NCLEX results"
on public.nclex_exam_results for insert to authenticated
with check ((select auth.uid()) = user_id);

-- Original starter questions for testing. Expand only with independently reviewed content.
insert into public.nclex_questions
(exam,category,client_need,difficulty,question_type,question_text,option_a,option_b,option_c,option_d,option_e,option_f,correct_options,rationale,test_strategy,access_level)
select * from (values
('NCLEX-RN','Fundamentals','Safe and Effective Care Environment','easy','single','A client is found on the floor beside the bed. Which action should the nurse take first?','Complete an incident report','Assess the client for injury and responsiveness','Call the family','Return the client to bed immediately',null,null,array['B'],'The client must be assessed before being moved or before documentation and notifications are completed.','For priority questions, assess immediate safety and physiologic status first.','free'),
('NCLEX-RN','Infection Control','Safety and Infection Control','easy','single','Which action is most effective for preventing transmission of microorganisms between clients?','Wearing the same gloves between tasks','Performing hand hygiene at the appropriate moments','Giving antibiotics before every procedure','Keeping all client doors closed',null,null,array['B'],'Correct hand hygiene interrupts transmission and remains the most important routine infection-prevention measure.','Choose the broad, consistently effective safety intervention.','free'),
('NCLEX-RN','Pharmacology','Pharmacological and Parenteral Therapies','medium','single','Before administering digoxin, which assessment is the priority?','Bowel sounds','Apical pulse for one full minute','Pupil response','Capillary refill',null,null,array['B'],'Digoxin can slow cardiac conduction. The apical pulse should be assessed before administration and findings acted on according to the prescription and policy.','Link the medication’s major adverse effect to the assessment.','free'),
('NCLEX-RN','Medical-Surgical','Physiological Adaptation','medium','single','A client with heart failure develops severe dyspnea and pink frothy sputum. What is the nurse’s priority action?','Encourage oral fluids','Position upright and activate urgent assistance','Place the client flat','Delay intervention until the next vital-sign round',null,null,array['B'],'These findings may indicate acute pulmonary edema. Upright positioning supports ventilation while urgent escalation and treatment are initiated.','Address airway and breathing before routine care.','free'),
('NCLEX-RN','Mental Health','Psychosocial Integrity','medium','single','A client says, “There is no reason for me to live.” Which response is best?','You should not talk that way','Are you thinking about harming yourself?','Everyone feels sad sometimes','Let us discuss this tomorrow',null,null,array['B'],'Direct, calm assessment of suicidal thoughts is necessary and does not increase suicide risk.','When safety is threatened, ask directly and assess immediately.','free'),
('NCLEX-RN','Maternal-Newborn','Health Promotion and Maintenance','medium','single','A postpartum client has heavy vaginal bleeding and a boggy uterus. Which intervention should the nurse perform first?','Massage the uterine fundus','Offer a warm drink','Prepare discharge paperwork','Encourage the client to ambulate',null,null,array['A'],'A boggy uterus suggests uterine atony. Fundal massage is an immediate nursing action while additional help and treatment are obtained.','Use the assessment clue to identify the reversible cause.','free'),
('NCLEX-RN','Pediatrics','Health Promotion and Maintenance','easy','single','Which finding in an infant requires the most immediate follow-up?','Respiratory rate of 68/min with nasal flaring','Sleeping after a feeding','Grasp reflex present','Occasional hiccups',null,null,array['A'],'Tachypnea with nasal flaring indicates respiratory distress and requires prompt assessment and escalation.','Prioritize signs of breathing difficulty.','free'),
('NCLEX-RN','Leadership','Management of Care','hard','single','The charge nurse receives four client reports. Which client should be assessed first?','A client awaiting routine discharge teaching','A client with new stridor after thyroid surgery','A client requesting a sleep aid','A client with chronic pain rated 6 of 10',null,null,array['B'],'New stridor may signal airway obstruction after thyroid surgery and is an immediate threat to life.','Use ABCs and acute change over chronic or routine needs.','free'),
('NCLEX-RN','Delegation','Management of Care','medium','single','Which task is appropriate for the RN to delegate to an experienced unlicensed assistive personnel?','Initial assessment of chest pain','Teaching a client to self-inject insulin','Obtaining routine vital signs for a stable client','Evaluating pain medication effectiveness',null,null,array['C'],'Routine data collection for a stable client can be delegated. Assessment, teaching and evaluation remain RN responsibilities.','Delegate predictable tasks, not nursing judgment.','free'),
('NCLEX-RN','Diabetes','Reduction of Risk Potential','medium','select_all','A client with diabetes is awake and has a blood glucose of 52 mg/dL. Which actions should the nurse take? Select all that apply.','Give 15 g of fast-acting carbohydrate','Recheck glucose in about 15 minutes','Administer long-acting insulin immediately','Repeat treatment if glucose remains low','Leave the client alone to rest','Assess for symptoms and contributing factors',array['A','B','D','F'],'An awake client with hypoglycemia should receive fast-acting carbohydrate, be reassessed, retreated if needed and evaluated for symptoms and causes.','For select-all questions, judge every option independently.','free'),
('NCLEX-RN','Respiratory','Physiological Adaptation','hard','select_all','Which findings may indicate worsening respiratory distress? Select all that apply.','New confusion','Use of accessory muscles','Oxygen saturation falling from baseline','Warm dry skin with normal speech','Inability to speak full sentences','Respiratory rate of 16/min without effort',array['A','B','C','E'],'Neurologic change, increased work of breathing, falling oxygen saturation and inability to speak normally are concerning signs.','Select objective signs of impaired oxygenation or increased work of breathing.','free'),
('NCLEX-RN','Renal','Reduction of Risk Potential','medium','single','A client with acute kidney injury has a potassium level of 6.4 mEq/L. Which finding is most concerning?','Peaked T waves on the ECG','Dry skin','Mild thirst','Urine specific gravity of 1.020',null,null,array['A'],'Severe hyperkalemia can cause lethal dysrhythmias; peaked T waves are an urgent cardiac manifestation.','Identify the finding linked to immediate mortality risk.','free'),
('NCLEX-RN','Neurology','Physiological Adaptation','hard','single','A client develops facial droop and unilateral arm weakness 30 minutes ago. What is the priority nursing action?','Allow the client to sleep','Activate the stroke response and note the last-known-well time','Give food to test swallowing','Schedule a routine clinic visit',null,null,array['B'],'Acute focal neurologic deficits require emergency stroke evaluation. The last-known-well time guides time-sensitive treatment.','Recognize time-critical emergencies and avoid oral intake until swallowing is assessed.','free'),
('NCLEX-RN','Ethics','Management of Care','medium','single','A competent adult refuses a blood transfusion for religious reasons. What should the nurse do?','Request that the family override the decision','Respect the refusal, confirm informed understanding and notify the provider','Administer the transfusion secretly','Ask another nurse to obtain consent',null,null,array['B'],'A competent adult has the right to refuse treatment. The nurse should ensure the decision is informed, communicate it and document appropriately.','Autonomy applies when the client has decision-making capacity.','free')
) as seed(exam,category,client_need,difficulty,question_type,question_text,option_a,option_b,option_c,option_d,option_e,option_f,correct_options,rationale,test_strategy,access_level)
where not exists (select 1 from public.nclex_questions);
