const sb=window.btvSupabase,$=id=>document.getElementById(id);let user=null,questions=[],current=null,answeredCurrent=false,bookmarks=new Set(),mock=[],mockIndex=0,mockCorrect=0,mockAnswers=[],timerId=null,remaining=1200,startedAt=0;
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='index.html';return}user=session.user;$('loading').hidden=true;$('app').hidden=false;await Promise.all([loadQuestions(),loadBookmarks(),refreshStats(),loadHistory()]);bind();populateSubjects();if(!restoreMock())showPractice()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('profession').onchange=()=>{populateSubjects();showPractice()};$('subject').onchange=showPractice;$('loadPractice').onclick=showPractice;$('startMock').onclick=startMock;$('logout').onclick=async()=>{await sb.auth.signOut();location.href='index.html'}}
async function loadQuestions(){const {data,error}=await sb.from('cbt_questions').select('*').eq('is_active',true);if(error){toast(error.message);return}questions=data||[]}
async function loadBookmarks(){const {data}=await sb.from('cbt_bookmarks').select('question_id').eq('user_id',user.id);bookmarks=new Set((data||[]).map(x=>x.question_id))}
function eligible(prof,subject='all'){return questions.filter(q=>(q.profession===prof||q.profession==='both')&&(subject==='all'||q.subject===subject))}
function populateSubjects(){const p=$('profession').value,old=$('subject').value;const subjects=[...new Set(eligible(p).map(q=>q.subject))].sort();$('subject').innerHTML='<option value="all">All subjects</option>'+subjects.map(s=>`<option>${esc(s)}</option>`).join('');if(subjects.includes(old))$('subject').value=old}
function showPractice(){const pool=eligible($('profession').value,$('subject').value);if(!pool.length){$('practiceCard').innerHTML='<p>No questions found. Run BTV-CBT-SETUP.sql in Supabase first.</p>';return}current=pool[Math.floor(Math.random()*pool.length)];answeredCurrent=false;renderQuestion($('practiceCard'),current,false)}
function renderQuestion(box,q,isMock){box.innerHTML=`<div class="questionMeta"><span>${esc(q.subject)} · ${esc(q.difficulty)}</span><span>${esc(q.profession)}</span></div><h2>${esc(q.question_text)}</h2><div class="options">${['A','B','C','D'].map(k=>`<button class="option" data-option="${k}"><b>${k}.</b> ${esc(q['option_'+k.toLowerCase()])}</button>`).join('')}</div><div class="explanation" hidden></div><div class="actions">${isMock?'':`<button class="bookmark">${bookmarks.has(q.id)?'★ Bookmarked':'☆ Bookmark'}</button><button class="next">Next question</button>`}</div>`;box.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>isMock?answerMock(b.dataset.option):answerPractice(b.dataset.option));if(!isMock){box.querySelector('.next').onclick=showPractice;box.querySelector('.bookmark').onclick=toggleBookmark}}
async function answerPractice(option){if(answeredCurrent)return;answeredCurrent=true;markAnswer($('practiceCard'),current,option,true);const {error}=await sb.from('cbt_attempts').insert({user_id:user.id,question_id:current.id,selected_option:option,is_correct:option===current.correct_option,mode:'practice'});if(error)toast(error.message);await refreshStats()}
function markAnswer(box,q,option,explain){box.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.option===q.correct_option)b.classList.add('correct');else if(b.dataset.option===option)b.classList.add('wrong')});if(explain){const e=box.querySelector('.explanation');e.hidden=false;e.innerHTML=`<b>${option===q.correct_option?'Correct':'Not quite'}.</b> ${esc(q.explanation)}`}}
async function toggleBookmark(){if(!current)return;const on=bookmarks.has(current.id);if(on){await sb.from('cbt_bookmarks').delete().eq('user_id',user.id).eq('question_id',current.id);bookmarks.delete(current.id)}else{await sb.from('cbt_bookmarks').insert({user_id:user.id,question_id:current.id});bookmarks.add(current.id)}$('practiceCard').querySelector('.bookmark').textContent=bookmarks.has(current.id)?'★ Bookmarked':'☆ Bookmark';await refreshStats()}
async function refreshStats(){const {data:a}=await sb.from('cbt_attempts').select('is_correct').eq('user_id',user.id);const list=a||[],correct=list.filter(x=>x.is_correct).length;$('answered').textContent=list.length;$('correct').textContent=correct;$('accuracy').textContent=list.length?Math.round(correct/list.length*100)+'%':'0%';$('bookmarked').textContent=bookmarks.size;const {count}=await sb.from('mock_exam_results').select('*',{count:'exact',head:true}).eq('user_id',user.id);$('mockCount').textContent=count||0}
function switchView(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));if(v==='history')loadHistory()}
function saveMockState(){if(!mock.length)return;localStorage.setItem('btv-cbt-mock-resume',JSON.stringify({ids:mock.map(q=>q.id),index:mockIndex,correct:mockCorrect,answers:mockAnswers.map(x=>({id:x.q.id,option:x.option,ok:x.ok})),remaining,startedAt,profession:$('mockProfession').value}))}
function clearMockState(){localStorage.removeItem('btv-cbt-mock-resume')}
function restoreMock(){try{const s=JSON.parse(localStorage.getItem('btv-cbt-mock-resume')||'null');if(!s?.ids?.length||s.remaining<=0)return false;mock=s.ids.map(id=>questions.find(q=>String(q.id)===String(id))).filter(Boolean);if(!mock.length)return false;mockIndex=Math.min(s.index,mock.length-1);mockCorrect=s.correct||0;mockAnswers=(s.answers||[]).map(x=>({q:questions.find(q=>String(q.id)===String(x.id)),option:x.option,ok:x.ok})).filter(x=>x.q);remaining=s.remaining;startedAt=s.startedAt||Date.now();$('mockProfession').value=s.profession||'nurse';$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;switchView('mock');renderMock();renderTimer();timerId=setInterval(()=>{remaining--;if(remaining%5===0)saveMockState();renderTimer();if(remaining<=0)finishMock()},1000);return true}catch{return false}}
function startMock(){const pool=eligible($('mockProfession').value);if(pool.length<2){toast('Add more questions in Supabase first.');return}const tier=new URLSearchParams(location.search).get('tier')==='short'?'short':'full',limit=tier==='short'?30:60;mock=[...pool].sort(()=>Math.random()-.5).slice(0,Math.min(limit,pool.length));mockIndex=0;mockCorrect=0;mockAnswers=[];remaining=(tier==='short'?30:60)*60;startedAt=Date.now();saveMockState();$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;renderMock();timerId=setInterval(()=>{remaining--;renderTimer();if(remaining<=0)finishMock()},1000);renderTimer()}
function renderTimer(){const m=Math.floor(remaining/60),s=remaining%60;$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`}
function renderMock(){if(mockIndex>=mock.length){finishMock();return}$('mockProgress').textContent=`Question ${mockIndex+1} of ${mock.length}`;renderQuestion($('mockCard'),mock[mockIndex],true)}
function answerMock(option){const q=mock[mockIndex],ok=option===q.correct_option;if(ok)mockCorrect++;mockAnswers.push({q,option,ok});markAnswer($('mockCard'),q,option,false);setTimeout(()=>{mockIndex++;saveMockState();renderMock()},350)}
function topicSummary(rows,key){const map={};rows.forEach(x=>{const n=x.q?.[key]||'General',r=map[n]||(map[n]={ok:0,total:0});r.total++;if(x.ok)r.ok++});return Object.entries(map).sort((a,b)=>(a[1].ok/a[1].total)-(b[1].ok/b[1].total))}
function reviewList(rows){return rows.filter(x=>!x.ok).slice(0,8).map(x=>'<li><b>'+esc(x.q.question_text)+'</b><br><span>'+esc(x.q.explanation)+'</span></li>').join('')||'<li>No incorrect answers to review.</li>'}
async function finishMock(){if(timerId){clearInterval(timerId);timerId=null}if(!$('mockExam').hidden){clearMockState();$('mockExam').hidden=true;const pct=Math.round(mockCorrect/mock.length*100),duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));const {error}=await sb.from('mock_exam_results').insert({user_id:user.id,profession:$('mockProfession').value,total_questions:mock.length,correct_answers:mockCorrect,percentage:pct,duration_seconds:duration});$('mockResult').hidden=false;const topics=topicSummary(mockAnswers,'subject'),weak=topics.slice(0,3),strong=[...topics].reverse().slice(0,3);$('mockResult').innerHTML=`<span class="band">${pct>=68?'Pass':'Further preparation recommended'}</span><h2>${pct}%</h2><p>You answered ${mockCorrect} of ${mock.length} correctly in ${Math.ceil(duration/60)} minutes.</p><div class="resultGrid78"><article><b>Strongest topics</b><p>${strong.map(x=>esc(x[0])+' '+Math.round(x[1].ok/x[1].total*100)+'%').join('<br>')||'More answers needed'}</p></article><article><b>Revision priorities</b><p>${weak.map(x=>esc(x[0])+' '+Math.round(x[1].ok/x[1].total*100)+'%').join('<br>')||'More answers needed'}</p></article></div><details><summary>Review incorrect answers</summary><ol class="incorrectReview78">${reviewList(mockAnswers)}</ol></details><button class="primary" id="again">Try another mock</button>`;$('again').onclick=()=>{$('mockResult').hidden=true;$('mockIntro').hidden=false};if(error)toast(error.message);if(new URLSearchParams(location.search).get('tier')==='short')await window.BTVCoins?.complete('cbt_short',pct,mock.length,{time_used_seconds:duration,answers:mockAnswers.map(x=>({question_id:x.q.id,selected:x.option,correct:x.ok,topic:x.q.subject}))});else await window.BTVCoins?.complete('cbt_full',pct,mock.length,{time_used_seconds:duration,answers:mockAnswers.map(x=>({question_id:x.q.id,selected:x.option,correct:x.ok,topic:x.q.subject}))});await refreshStats();await loadHistory()}}
async function loadHistory(){const {data,error}=await sb.from('mock_exam_results').select('*').eq('user_id',user.id).order('completed_at',{ascending:false}).limit(20);if(error){$('historyList').textContent=error.message;return}const rows=data||[];$('historyList').innerHTML=rows.length?rows.map(r=>`<div class="historyRow"><div><b>${Number(r.percentage).toFixed(0)}% · ${esc(r.profession)}</b><small>${new Date(r.completed_at).toLocaleString()}</small></div><span>${r.correct_answers}/${r.total_questions}</span></div>`).join(''):'<p>No mock exams completed yet.</p>'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init();
