const sb=window.btvSupabase,$=id=>document.getElementById(id);let user=null,questions=[],current=null,answeredCurrent=false,bookmarks=new Set(),mock=[],mockIndex=0,mockCorrect=0,mockAnswers=[],timerId=null,remaining=1200,startedAt=0,paidAttempt=null,lockedProfession=null;
const professionVisuals={nurse:{title:'Nurse question bank',detail:'Questions matched to nursing workflows and exam domains.',image:'home-nurse-blur-v101.png',alt:'Nurse question bank illustration'},midwife:{title:'Midwife question bank',detail:'Questions matched to maternity and midwifery care contexts.',image:'midwife-question-bank-v119.svg',alt:'Midwife question bank illustration'},both:{title:'Mixed profession question bank',detail:'Questions relevant across nursing and midwifery settings.',image:'nurse-midwife-question-bank-v119.svg',alt:'Nurse and midwife question bank illustration'}};
function normaliseProfession(value){const raw=String(value||'').trim().toLowerCase();if(raw==='midwife'||raw==='midwifery')return'midwife';if(raw==='both')return'both';return'nurse'}
function questionAudience(value){const raw=String(value||'').trim().toLowerCase();if(!raw)return'both';if(raw==='midwife'||raw==='midwifery')return'midwife';if(raw==='nurse'||raw==='nursing')return'nurse';if(raw==='both'||raw==='all')return'both';return'both'}
function profileProfession(){try{const profile=JSON.parse(localStorage.getItem('btv-profile')||'{}');const preferred=profile.profession||profile.role||'';const fromMeta=user?.user_metadata?.profession||'';const token=String(preferred||fromMeta).toLowerCase();if(token.includes('midwife'))return'midwife';if(token.includes('nurse'))return'nurse';return null}catch{return null}}
function applyProfessionScope(){lockedProfession=profileProfession();if(!lockedProfession)return updateProfessionVisual($('profession').value);['profession','mockProfession'].forEach(id=>{const select=$(id);if(!select)return;select.value=lockedProfession;select.disabled=true;select.setAttribute('aria-label',`${lockedProfession==='midwife'?'Midwife':'Nurse'} question bank`)});const panel=$('practiceView');if(panel&&!panel.querySelector('.audienceLockNote119'))panel.insertAdjacentHTML('afterbegin',`<p class="audienceLockNote119">Showing ${lockedProfession==='midwife'?'midwife':'nurse'} question bank for your registered profession.</p>`);updateProfessionVisual(lockedProfession)}
function updateProfessionVisual(value){const key=normaliseProfession(value),asset=professionVisuals[key]||professionVisuals.nurse;const host=$('practiceCard');if(!host)return;host.dataset.professionVisual=key;host.style.setProperty('--profession-visual-url',`url('${asset.image}')`)}
function visualMarkup(value){const key=normaliseProfession(value),asset=professionVisuals[key]||professionVisuals.nurse;return`<figure class="professionVisual119"><img src="${asset.image}" alt="${esc(asset.alt)}" loading="lazy" width="1200" height="420"><figcaption><span>${esc(asset.title)}</span><small>${esc(asset.detail)}</small></figcaption></figure>`}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='index.html';return}user=session.user;$('loading').hidden=true;$('app').hidden=false;await Promise.all([loadQuestions(),loadBookmarks(),refreshStats(),loadHistory()]);bind();populateSubjects();if(paidAttempt)startPaidMock();else if(!restoreMock())showPractice()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('profession').onchange=()=>{updateProfessionVisual($('profession').value);populateSubjects();showPractice()};$('subject').onchange=showPractice;$('loadPractice').onclick=showPractice;$('startMock').onclick=startMock;$('logout').onclick=async()=>{await sb.auth.signOut();location.href='index.html'}}
async function loadQuestions(){const attempt=new URLSearchParams(location.search).get('attempt');if(attempt){try{paidAttempt=await window.BTVExam.resumeExam(attempt);questions=paidAttempt.questions||[];return}catch(error){toast(error.message);return}}questions=[];for(let from=0;;from+=1000){const {data,error}=await sb.from('cbt_questions').select('*').eq('is_active',true).order('id').range(from,from+999);if(error){toast(error.message);return}questions.push(...(data||[]));if(!data||data.length<1000)break}}
async function loadBookmarks(){const {data}=await sb.from('cbt_bookmarks').select('question_id').eq('user_id',user.id);bookmarks=new Set((data||[]).map(x=>x.question_id))}
function eligible(prof,subject='all'){const audience=normaliseProfession(prof);return questions.filter(q=>{const qProfession=questionAudience(q.profession);const qAudience=qProfession==='both'||qProfession===audience;return qAudience&&(subject==='all'||q.subject===subject)})}
function populateSubjects(){const p=$('profession').value,old=$('subject').value;const subjects=[...new Set(eligible(p).map(q=>q.subject))].sort();$('subject').innerHTML='<option value="all">All subjects</option>'+subjects.map(s=>`<option>${esc(s)}</option>`).join('');if(subjects.includes(old))$('subject').value=old}
function showPractice(){const pool=eligible($('profession').value,$('subject').value);if(!pool.length){$('practiceCard').innerHTML='<p>No questions found. Run BTV-CBT-SETUP.sql in Supabase first.</p>';return}current=pool[Math.floor(Math.random()*pool.length)];answeredCurrent=false;renderQuestion($('practiceCard'),current,false)}
function renderQuestion(box,q,isMock){const audience=questionAudience(q.profession);box.innerHTML=`${visualMarkup(audience==='both'?$('profession').value:audience)}${q.sample_question?'<div class="sampleBadge118">SAMPLE QUESTION · NOT CLINICALLY REVIEWED</div><p class="sampleNotice118">For study guidance only. This is not an official exam question and does not replace professional training, local policy or clinical judgement.</p>':''}<div class="questionMeta"><span>${esc(q.subject)} · ${esc(q.difficulty)}</span><span>${esc(audience==='both'?'nurse & midwife':audience)}</span></div><h2>${esc(cleanQuestion(q.question_text))}</h2><div class="options">${['A','B','C','D'].map(k=>`<button class="option" data-option="${k}"><b>${k}.</b> ${esc(q['option_'+k.toLowerCase()])}</button>`).join('')}</div><div class="explanation" hidden></div><div class="actions">${isMock?'':`<button class="bookmark">${bookmarks.has(q.id)?'★ Bookmarked':'☆ Bookmark'}</button><button class="next">Next question</button>`}</div>`;box.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>isMock?answerMock(b.dataset.option):answerPractice(b.dataset.option));if(!isMock){box.querySelector('.next').onclick=showPractice;box.querySelector('.bookmark').onclick=toggleBookmark}}
async function answerPractice(option){if(answeredCurrent)return;const usage=await sb.rpc('btv_use_free_practice',{p_exam_type:'cbt'});if(usage.error||!usage.data?.success){toast(usage.data?.message||usage.error?.message||"You have completed today's free CBT questions.");if(usage.data?.code==='DAILY_LIMIT_REACHED')window.BTVCoins?.showDailyCompletion?.('cbt',usage.data);return}answeredCurrent=true;markAnswer($('practiceCard'),current,option,true);const {error}=await sb.from('cbt_attempts').insert({user_id:user.id,question_id:current.id,selected_option:option,is_correct:option===current.correct_option,mode:'practice'});if(error)toast(error.message);await refreshStats();window.BTVCoins?.dailyProgress?.('cbt',usage.data);if(usage.data?.remaining===0)window.BTVCoins?.showDailyCompletion?.('cbt',usage.data)}
function markAnswer(box,q,option,explain){box.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.option===q.correct_option)b.classList.add('correct');else if(b.dataset.option===option)b.classList.add('wrong')});if(explain){const e=box.querySelector('.explanation');e.hidden=false;e.innerHTML=`<b>${option===q.correct_option?'Correct':'Not quite'}.</b> ${esc(q.explanation)}`}}
async function toggleBookmark(){if(!current)return;const on=bookmarks.has(current.id);if(on){await sb.from('cbt_bookmarks').delete().eq('user_id',user.id).eq('question_id',current.id);bookmarks.delete(current.id)}else{await sb.from('cbt_bookmarks').insert({user_id:user.id,question_id:current.id});bookmarks.add(current.id)}$('practiceCard').querySelector('.bookmark').textContent=bookmarks.has(current.id)?'★ Bookmarked':'☆ Bookmark';await refreshStats()}
async function refreshStats(){const {data:a}=await sb.from('cbt_attempts').select('is_correct').eq('user_id',user.id);const list=a||[],correct=list.filter(x=>x.is_correct).length;$('answered').textContent=list.length;$('correct').textContent=correct;$('accuracy').textContent=list.length?Math.round(correct/list.length*100)+'%':'0%';$('bookmarked').textContent=bookmarks.size;const {count}=await sb.from('mock_exam_results').select('*',{count:'exact',head:true}).eq('user_id',user.id);$('mockCount').textContent=count||0}
function switchView(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));if(v==='history')loadHistory()}
function saveMockState(){if(!mock.length)return;localStorage.setItem('btv-cbt-mock-resume',JSON.stringify({ids:mock.map(q=>q.id),index:mockIndex,correct:mockCorrect,answers:mockAnswers.map(x=>({id:x.q.id,option:x.option,ok:x.ok})),remaining,startedAt,profession:$('mockProfession').value}))}
function clearMockState(){localStorage.removeItem('btv-cbt-mock-resume')}
function restoreMock(){try{const s=JSON.parse(localStorage.getItem('btv-cbt-mock-resume')||'null');if(!s?.ids?.length||s.remaining<=0)return false;mock=s.ids.map(id=>questions.find(q=>String(q.id)===String(id))).filter(Boolean);if(!mock.length)return false;mockIndex=Math.min(s.index,mock.length-1);mockCorrect=s.correct||0;mockAnswers=(s.answers||[]).map(x=>({q:questions.find(q=>String(q.id)===String(x.id)),option:x.option,ok:x.ok})).filter(x=>x.q);remaining=s.remaining;startedAt=s.startedAt||Date.now();$('mockProfession').value=s.profession||'nurse';$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;switchView('mock');renderMock();renderTimer();timerId=setInterval(()=>{remaining--;if(remaining%5===0)saveMockState();renderTimer();if(remaining<=0)finishMock()},1000);return true}catch{return false}}
function startPaidMock(){mock=questions;mockIndex=0;mockCorrect=0;mockAnswers=[];remaining=Math.max(1,Math.floor((new Date(paidAttempt.attempt.expires_at)-Date.now())/1000));startedAt=new Date(paidAttempt.attempt.started_at).getTime();$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;switchView('mock');renderMock();renderTimer();timerId=setInterval(()=>{remaining--;renderTimer();if(remaining<=0)finishMock()},1000)}
function startMock(){const pool=eligible($('mockProfession').value);if(pool.length<2){toast('Add more questions in Supabase first.');return}const tier=new URLSearchParams(location.search).get('tier')==='short'?'short':'full',limit=tier==='short'?30:60;mock=[...pool].sort(()=>Math.random()-.5).slice(0,Math.min(limit,pool.length));mockIndex=0;mockCorrect=0;mockAnswers=[];remaining=(tier==='short'?15:30)*60;startedAt=Date.now();saveMockState();$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;renderMock();timerId=setInterval(()=>{remaining--;renderTimer();if(remaining<=0)finishMock()},1000);renderTimer()}
function renderTimer(){const m=Math.floor(remaining/60),s=remaining%60;$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`}
function renderMock(){if(mockIndex>=mock.length){finishMock();return}$('mockProgress').textContent=`Question ${mockIndex+1} of ${mock.length}`;renderQuestion($('mockCard'),mock[mockIndex],true)}
function answerMock(option){const q=mock[mockIndex];if(paidAttempt){mockAnswers.push({q,option,ok:null});$('mockCard').querySelectorAll('.option').forEach(b=>b.disabled=true);setTimeout(()=>{mockIndex++;renderMock()},180);return}const ok=option===q.correct_option;if(ok)mockCorrect++;mockAnswers.push({q,option,ok});markAnswer($('mockCard'),q,option,false);setTimeout(()=>{mockIndex++;saveMockState();renderMock()},350)}
function topicSummary(rows,key){const map={};rows.forEach(x=>{const n=x.q?.[key]||'General',r=map[n]||(map[n]={ok:0,total:0});r.total++;if(x.ok)r.ok++});return Object.entries(map).sort((a,b)=>(a[1].ok/a[1].total)-(b[1].ok/b[1].total))}
function reviewList(rows){return rows.filter(x=>!x.ok).slice(0,8).map(x=>'<li><b>'+esc(x.q.question_text)+'</b><br><span>'+esc(x.q.explanation)+'</span></li>').join('')||'<li>No incorrect answers to review.</li>'}
async function finishPaidMock(){if(timerId){clearInterval(timerId);timerId=null}if($('mockExam').hidden)return;$('mockExam').hidden=true;try{const answers={};mockAnswers.forEach(x=>answers[String(x.q.id)]=x.option);const result=await window.BTVExam.submitExam(paidAttempt.attempt.id,answers),review=result.questions||[];mockAnswers=review.map(q=>({q,option:q.selected_answer,ok:q.is_correct}));mockCorrect=Number(result.correct_count||mockAnswers.filter(x=>x.ok).length);const pct=Number(result.score||0),duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));$('mockResult').hidden=false;$('mockResult').innerHTML=`<span class="band">${pct>=68?'Pass':'Further preparation recommended'}</span><h2>${pct}%</h2><p>You answered ${mockCorrect} of ${mock.length} correctly in ${Math.ceil(duration/60)} minutes.</p><details><summary>Review answers and explanations</summary><ol class="incorrectReview78">${reviewList(mockAnswers)}</ol></details><button class="primary" id="again">Return to learning</button>`;$('again').onclick=()=>location.href='index.html?screen=learn';window.dispatchEvent(new CustomEvent('btv:wallet-changed'));await refreshStats();await loadHistory()}catch(error){toast(error.message);$('mockExam').hidden=false}}
async function finishMock(){if(paidAttempt)return finishPaidMock();if(timerId){clearInterval(timerId);timerId=null}if(!$('mockExam').hidden){clearMockState();$('mockExam').hidden=true;const pct=Math.round(mockCorrect/mock.length*100),duration=Math.max(0,Math.round((Date.now()-startedAt)/1000));const {error}=await sb.from('mock_exam_results').insert({user_id:user.id,profession:$('mockProfession').value,total_questions:mock.length,correct_answers:mockCorrect,percentage:pct,duration_seconds:duration});$('mockResult').hidden=false;const topics=topicSummary(mockAnswers,'subject'),weak=topics.slice(0,3),strong=[...topics].reverse().slice(0,3);$('mockResult').innerHTML=`<span class="band">${pct>=68?'Pass':'Further preparation recommended'}</span><h2>${pct}%</h2><p>You answered ${mockCorrect} of ${mock.length} correctly in ${Math.ceil(duration/60)} minutes.</p><div class="resultGrid78"><article><b>Strongest topics</b><p>${strong.map(x=>esc(x[0])+' '+Math.round(x[1].ok/x[1].total*100)+'%').join('<br>')||'More answers needed'}</p></article><article><b>Revision priorities</b><p>${weak.map(x=>esc(x[0])+' '+Math.round(x[1].ok/x[1].total*100)+'%').join('<br>')||'More answers needed'}</p></article></div><details><summary>Review incorrect answers</summary><ol class="incorrectReview78">${reviewList(mockAnswers)}</ol></details><button class="primary" id="again">Try another mock</button>`;$('again').onclick=()=>{$('mockResult').hidden=true;$('mockIntro').hidden=false};if(error)toast(error.message);if(new URLSearchParams(location.search).get('tier')==='short')await window.BTVCoins?.complete('cbt_short',pct,mock.length,{time_used_seconds:duration,answers:mockAnswers.map(x=>({question_id:x.q.id,selected:x.option,correct:x.ok,topic:x.q.subject}))});else await window.BTVCoins?.complete('cbt_full',pct,mock.length,{time_used_seconds:duration,answers:mockAnswers.map(x=>({question_id:x.q.id,selected:x.option,correct:x.ok,topic:x.q.subject}))});await refreshStats();await loadHistory()}}
async function loadHistory(){const {data,error}=await sb.from('mock_exam_results').select('*').eq('user_id',user.id).order('completed_at',{ascending:false}).limit(20);if(error){$('historyList').textContent=error.message;return}const rows=data||[];$('historyList').innerHTML=rows.length?rows.map(r=>`<div class="historyRow"><div><b>${Number(r.percentage).toFixed(0)}% · ${esc(r.profession)}</b><small>${new Date(r.completed_at).toLocaleString()}</small></div><span>${r.correct_answers}/${r.total_questions}</span></div>`).join(''):'<p>No mock exams completed yet.</p>'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cleanQuestion(v){return String(v??'').replace(/^\[BTV-[^\]]+\]\s*/,'')}
init().then(()=>applyProfessionScope());
