(()=>{
 'use strict';
 if(window.__btvExperienceV306)return;window.__btvExperienceV306=true;
 if(!document.querySelector('link[href^="experience-v30.6.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="experience-v30.6.css?v=30.6">');
 const $=s=>document.querySelector(s);
 const country=()=>{try{return state?.country||'uk'}catch{}try{return JSON.parse(localStorage.getItem('btv-profile')||'{}').destination||'uk'}catch{return'uk'}};
 const examFor=code=>code==='uk'?{id:'cbt',label:'CBT exam',name:'UK CBT preparation'}:['us','ca'].includes(code)?{id:'nclex',label:'NCLEX exam',name:'NCLEX-RN preparation'}:null;
 function openMemberPane(id){$('#btvPlatformOpen')?.click();setTimeout(()=>document.querySelector(`[data-btv-pane="${id}"]`)?.click(),120)}
 function addLibrary(){const learn=$('#learn'),title=learn?.querySelector('.pageTitle');if(!learn||!title||learn.querySelector('.learningLibrary'))return;const box=document.createElement('section');box.className='learningLibrary';box.innerHTML='<button class="libraryTile" data-library="discover"><i>▤</i><span><b>Articles & guides</b><small>Read content published by the Beyond The Visa team</small></span><span>→</span></button><button class="libraryTile" data-library="learn"><i>▶</i><span><b>Video centre</b><small>Watch lessons and continue your learning</small></span><span>→</span></button>';title.insertAdjacentElement('afterend',box);box.querySelectorAll('[data-library]').forEach(b=>b.onclick=()=>openMemberPane(b.dataset.library))}
 function tidyExams(){const learn=$('#learn'),tabs=learn?.querySelector('.learnTabs');if(!learn||!tabs)return;document.querySelectorAll('[data-cbt-centre],[data-nclex-centre]').forEach(x=>x.remove());const wanted=examFor(country());tabs.querySelectorAll('[data-learn-tab="cbt"],[data-learn-tab="nclex"]').forEach(b=>{b.hidden=!wanted||b.dataset.learnTab!==wanted.id;b.classList.remove('active')});let button=tabs.querySelector(`[data-learn-tab="${wanted?.id||'none'}"]`);if(wanted&&!button){button=document.createElement('button');button.dataset.learnTab=wanted.id;button.textContent=wanted.label;tabs.append(button);button.onclick=()=>{if(typeof showLearningTab==='function')showLearningTab(wanted.id)}}if(button){button.hidden=false;if(button.textContent!==wanted.label)button.textContent=wanted.label;let panel=$(`#${wanted.id}Lesson`);if(!panel){panel=document.createElement('section');panel.id=wanted.id+'Lesson';panel.className='learnPanel';learn.append(panel)}if(!panel.children.length)panel.innerHTML=`<div class="examDestinationNote"><i>✓</i><div><b>${wanted.name}</b><small>This exam centre appears because it matches your selected destination. Open it for questions, mock tests and performance insights.</small></div></div>`}const active=tabs.querySelector('button.active:not([hidden])');if(!active)tabs.querySelector('[data-learn-tab="guide"]')?.classList.add('active')}
 function findOpenButton(words){return [...document.querySelectorAll('[data-open]')].find(x=>words.some(w=>x.textContent.toLowerCase().includes(w)))}
 function openExisting(words){const b=findOpenButton(words);if(b){b.click();closeMenu();return true}return false}
 function removeUtilityTiles(){document.querySelectorAll('#home button,.quick button,.actionGrid button,.supportGrid article').forEach(x=>{const t=x.textContent.toLowerCase();if(['feedback','contact us','privacy','legal','terms & conditions','cookie policy'].some(k=>t.includes(k))){x.hidden=true;x.dataset.movedToMenu='true'}})}
 function closeMenu(){const wrap=$('#appMenuBackdrop');if(wrap)wrap.hidden=true;document.body.style.overflow=''}
 function buildMenu(){if($('#appMenuBackdrop'))return;const header=$('#appShell header .headerActions')||$('#appShell header');if(!header)return;const trigger=document.createElement('button');trigger.className='appMenuButton';trigger.type='button';trigger.setAttribute('aria-label','Open menu');trigger.textContent='☰';header.prepend(trigger);document.body.insertAdjacentHTML('beforeend',`<div id="appMenuBackdrop" class="appMenuBackdrop" hidden><aside class="appMenu" role="dialog" aria-modal="true" aria-label="App menu"><div class="appMenuHead"><div><small>BEYOND THE VISA</small><h2>Menu</h2></div><button class="appMenuClose" aria-label="Close menu">×</button></div><div class="appMenuGroup"><span>ACCOUNT</span><button class="appMenuItem" data-menu-action="profile"><i>●</i>Profile & preferences</button><button class="appMenuItem" data-menu-action="documents"><i>▣</i>My documents</button></div><div class="appMenuGroup"><span>HELP & FEEDBACK</span><button class="appMenuItem" data-menu-action="contact"><i>?</i>Contact us</button><button class="appMenuItem" data-menu-action="feedback"><i>★</i>Feedback, bugs & ideas</button></div><div class="appMenuGroup"><span>PRIVACY & LEGAL</span><a class="appMenuItem" href="privacy-policy.html"><i>⌾</i>Privacy policy</a><a class="appMenuItem" href="terms-and-conditions.html"><i>✓</i>Terms & conditions</a><a class="appMenuItem" href="cookie-policy.html"><i>◌</i>Cookie policy</a></div></aside></div>`);const wrap=$('#appMenuBackdrop');trigger.onclick=()=>{wrap.hidden=false;document.body.style.overflow='hidden'};wrap.querySelector('.appMenuClose').onclick=closeMenu;wrap.onclick=e=>{if(e.target===wrap)closeMenu()};wrap.querySelector('[data-menu-action="profile"]').onclick=()=>openExisting(['profile'])||$('#headerProfile')?.click();wrap.querySelector('[data-menu-action="documents"]').onclick=()=>openExisting(['document']);wrap.querySelector('[data-menu-action="contact"]').onclick=()=>openExisting(['contact']);wrap.querySelector('[data-menu-action="feedback"]').onclick=()=>openExisting(['feedback','rate this app','report a bug','request a feature'])}
 function refine(){buildMenu();removeUtilityTiles();addLibrary();tidyExams()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',refine):refine();
 let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;refine()})}).observe(document.documentElement,{childList:true,subtree:true});
 document.addEventListener('click',event=>{if(event.target.closest('[data-open="learn"],.nav[data-open="learn"]'))setTimeout(refine,60)},true);
 window.addEventListener('btv:membership',()=>setTimeout(refine,50));
})();
