(()=>{
 if(window.__btvExperience85)return;window.__btvExperience85=true;
 const $=s=>document.querySelector(s),db=()=>window.btvSupabase;
 const profile=()=>{try{return window.userProfile?.()||JSON.parse(localStorage.getItem('btv-profile')||'{}')}catch{return{}}};
 const context=()=>{const p=profile(),raw=String(window.state?.country||p.destination||p.destinationCountry||'').toLowerCase(),country=({usa:'us','united states':'us','united kingdom':'uk',england:'uk',scotland:'uk','northern ireland':'uk',australia:'au',canada:'ca','new zealand':'nz',ireland:'ie'}[raw]||raw),profession=String(p.profession||p.role||'').toLowerCase();return{country,profession}};
 const eligible=exam=>{const x=context(),n=x.profession.includes('nurse'),m=x.profession.includes('midwi');if(exam==='cbt')return x.country==='uk'&&(n||m);if(exam==='nclex')return n&&['us','ca','au'].includes(x.country);if(exam==='ielts')return ['uk','au','ca','nz','ie'].includes(x.country);return true};
 const premium=()=>localStorage.getItem('btv-premium')==='yes';
 function openPremium(){const trigger=$('[data-open-premium]');if(trigger)trigger.click();else window.openScreen?.('premium')}
 function exams(){
  ['cbt','nclex','ielts'].forEach(exam=>{const tab=$(`[data-learn-tab="${exam}"]`),panel=$(`#${exam}Lesson`),allowed=eligible(exam);[tab,panel].forEach(node=>{if(!node)return;node.hidden=!allowed;node.dataset.examIneligibleV84=String(!allowed);node.setAttribute('aria-hidden',String(!allowed))});if(tab&&allowed){tab.classList.toggle('premiumExam85',!premium());tab.setAttribute('aria-label',`${exam.toUpperCase()}${premium()?'':' Premium'}`)}});
  $('#learn')?.querySelectorAll('[data-go="cbt"],[data-go="nclex"],[data-feature="cbt"],[data-feature="nclex"],.cbtTile,.nclexTile').forEach(node=>{if(!node.closest('#cbtLesson,#nclexLesson,.learnTabs'))node.remove()});
  const active=$('.learnPanel.active[data-exam-ineligible-v84="true"]');if(active)$('[data-learn-tab="guide"]')?.click();
 }
 function explore(){const grid=$('#home .quick');if(!grid)return;if(!grid.querySelector('.exploreMentor85')){const mentor=document.createElement('button');mentor.className='exploreMentor85';mentor.innerHTML='<i>♙</i><span>Mentor marketplace</span><small>Connect with approved professional mentors</small>';mentor.onclick=()=>window.BTVFeatures?.open?.('mentors');grid.append(mentor)}if(!grid.querySelector('.exploreStory85')){const story=document.createElement('button');story.className='exploreStory85';story.innerHTML='<i>★</i><span>Success stories</span><small>Real journeys, lessons and encouragement</small>';story.onclick=()=>window.BTVFeatures?.open?.('stories');grid.append(story)}}
 function premiumBadge(){const badge=$('#premiumSecureBadge');if(!badge)return;if(!badge.querySelector('img'))badge.innerHTML='<img src="premium-emblem-v85.png" alt="Premium member">'}
 async function admin(){try{const session=(await db()?.auth?.getSession())?.data?.session;if(!session)return false;if(['admin','owner'].includes(session.user.app_metadata?.role)||['admin','owner'].includes(session.user.user_metadata?.role))return true;let result=await db().from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(result.error)result=await db().from('profiles').select('role').eq('user_id',session.user.id).maybeSingle();return ['admin','owner'].includes(result.data?.role)}catch{return false}}
 function openScreen(id){document.querySelector(`[data-open="${id}"]`)?.click()||window.openScreen?.(id)}
 async function menu(){const panel=$('.shortcutPanel83');if(!panel||panel.dataset.v85)return;panel.dataset.v85='true';panel.querySelectorAll('[data-shortcut83="mentor"],[data-shortcut83="story"],[data-shortcut83="community"]').forEach(x=>x.remove());const groups=panel.querySelectorAll('.shortcutGroup83'),host=groups[groups.length-1]||panel;const support=document.createElement('div');support.className='shortcutGroup83 supportMenu85';support.innerHTML='<span>SUPPORT & TRUST</span><button class="shortcutItem83" data-v85-route="legal"><b>Privacy & legal</b><small>Policies, cookies and your data</small></button><button class="shortcutItem83" data-v85-route="feedback"><b>Feedback</b><small>Rate, report or request a feature</small></button><button class="shortcutItem83" data-v85-route="contact"><b>Contact us</b><small>Support and general enquiries</small></button>';host.after(support);if(await admin()&&!panel.querySelector('[data-shortcut83="admin"], [data-v85-route="admin"]')){const management=document.createElement('div');management.className='shortcutGroup83';management.innerHTML='<span>MANAGEMENT</span><button class="shortcutItem83 shortcutAdmin83" data-v85-route="admin"><b>Admin Portal</b><small>Manage users, content and services</small></button>';support.after(management)}support.querySelectorAll('[data-v85-route]').forEach(b=>b.onclick=()=>{document.querySelector('.shortcutClose83')?.click();openScreen(b.dataset.v85Route)});panel.querySelector('[data-v85-route="admin"]')?.addEventListener('click',()=>location.href='admin.html')}
 function wallet(){const shell=$('#platformHubV72');if(!shell)return;shell.classList.toggle('walletShell85',!!shell.querySelector('[data-wallet-tab]'))}
 function scientific(){const panel=$('#calculationsLesson'),card=panel?.querySelector('.calcCard');if(!card||card.querySelector('.scientificCalc85'))return;const calc=document.createElement('section');calc.className='scientificCalc85';calc.innerHTML='<header><b>Scientific calculator</b><small>For working only—enter your final answer separately</small></header><input class="scientificDisplay85" value="0" readonly aria-label="Calculator display"><div class="scientificKeys85">'+['sin','cos','tan','√','x²','(',')','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','π','+','C','⌫','='].map(k=>`<button type="button" class="${'+−×÷='.includes(k)?'operator':''}" data-sci="${k}">${k}</button>`).join('')+'</div>';card.prepend(calc);const display=calc.querySelector('.scientificDisplay85');let expr='';const safe=()=>expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π',String(Math.PI)).replace(/√\(([^()]*)\)/g,'Math.sqrt($1)').replace(/sin\(([^()]*)\)/g,'Math.sin($1)').replace(/cos\(([^()]*)\)/g,'Math.cos($1)').replace(/tan\(([^()]*)\)/g,'Math.tan($1)').replace(/\^2/g,'**2');calc.querySelectorAll('[data-sci]').forEach(b=>b.onclick=()=>{const k=b.dataset.sci;if(k==='C')expr='';else if(k==='⌫')expr=expr.slice(0,-1);else if(k==='='){try{expr=String(Function(`"use strict";return (${safe()})`)())}catch{display.value='Error';return}}else if(['sin','cos','tan','√'].includes(k))expr+=k+'(';else if(k==='x²')expr+='^2';else expr+=k;display.value=expr||'0'});const answer=card.querySelector('.calcAnswer'),pad=card.querySelector('.calcPad');if(answer&&pad){pad.classList.add('answerPad85');pad.hidden=true;const reveal=document.createElement('button');reveal.type='button';reveal.className='answerReveal85';reveal.textContent='Enter final answer';answer.before(reveal);reveal.onclick=()=>{pad.hidden=false;reveal.hidden=true;answer.querySelector('input')?.focus()};answer.querySelector('input')?.addEventListener('focus',()=>{pad.hidden=false;reveal.hidden=true})}}
 document.addEventListener('click',event=>{const tab=event.target.closest('[data-learn-tab="cbt"],[data-learn-tab="nclex"],[data-learn-tab="ielts"]');if(tab&&eligible(tab.dataset.learnTab)&&!premium()){event.preventDefault();event.stopImmediatePropagation();openPremium()}},true);
 function install(){exams();explore();premiumBadge();menu();wallet();scientific()}
 let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install()})}).observe(document.documentElement,{childList:true,subtree:true});
 install();setTimeout(install,500);setTimeout(install,1600);window.addEventListener('btv:membership',install);window.addEventListener('btv:profile-changed',install);window.addEventListener('storage',install);
})();
