(function(){
 'use strict';
 if(window.__btvIELTSV31)return;window.__btvIELTSV31=true;
 const sb=window.btvSupabase,B=window.BTVIELTSBank;let premium=localStorage.getItem('btv-premium')==='yes',section='listening',index=0;
 const names={listening:'Listening',reading:'Reading',writing:'Writing',speaking:'Speaking'};
 const icon={listening:'◉',reading:'▤',writing:'✎',speaking:'◌'};
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function loadCss(){if(!document.querySelector('link[href^="ielts-v31.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="ielts-v31.css?v=31">')}
 function progress(){try{return JSON.parse(localStorage.getItem('btv-ielts-progress')||'{}')}catch{return{}}}
 function saveResult(id,result){const p=progress();p[id]={band:result.band,correct:result.correct,at:new Date().toISOString()};localStorage.setItem('btv-ielts-progress',JSON.stringify(p))}
 function openPremium(){document.querySelector('[data-open-premium]')?.click()||document.querySelector('[data-premium-request]')?.click()}
 function addTab(){const tabs=document.querySelector('.learnTabs');if(!tabs||tabs.querySelector('[data-learn-tab="ielts"]'))return false;const btn=document.createElement('button');btn.type='button';btn.dataset.learnTab='ielts';btn.innerHTML='IELTS <small class="premiumMini">Premium</small>';const cv=tabs.querySelector('[data-learn-tab="cv"]');tabs.insertBefore(btn,cv||null);const panel=document.createElement('section');panel.id='ieltsLesson';panel.className='learnPanel ieltsPanel';(document.getElementById('cvLesson')||tabs.parentElement).before?document.getElementById('cvLesson')?.before(panel):tabs.after(panel);if(!panel.parentElement)tabs.parentElement.append(panel);btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('.learnTabs button').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.learnPanel').forEach(x=>x.classList.toggle('active',x===panel));render()},true);render();return true}
 function locked(){return `<div class="ieltsHero"><span class="ieltsEyebrow">IELTS PREPARATION</span><h2>Four skills. One focused preparation space.</h2><p>Practise Listening, Reading, Writing and Speaking with 2,000 original IELTS-style tasks and Gemini-powered feedback.</p><div class="ieltsHeroMeta"><span>500 tasks per skill</span><span>Progress tracking</span><span>AI marking</span></div></div><div class="ieltsPremium"><div class="lock">◆</div><span class="ieltsEyebrow">PREMIUM LEARNING</span><h2>IELTS preparation is included with Premium</h2><p>Unlock all four skill banks, personalised marking, band guidance and improvement actions.</p><button data-ielts-premium>View Premium membership</button></div><p class="ieltsDisclaimer">Original practice content for preparation only. Beyond The Visa is not affiliated with or endorsed by IELTS, its owners or test partners.</p>`}
 function answerControl(q){if(q.options?.length)return `<div class="ieltsOptions">${q.options.map((o,i)=>`<label><input type="radio" name="ieltsAnswer" value="${escape(o)}"><span>${String.fromCharCode(65+i)}. ${escape(o)}</span></label>`).join('')}</div>`;const short=['listening','reading'].includes(q.section);return `<textarea id="ieltsResponse" class="ieltsAnswer ${short?'short':''}" placeholder="${short?'Type your answer':'Write or paste your full response here for marking'}"></textarea>`}
 function render(){const panel=document.getElementById('ieltsLesson');if(!panel||!B)return;if(!premium){panel.innerHTML=locked();panel.querySelector('[data-ielts-premium]')?.addEventListener('click',openPremium);return}const bank=B.bank(section),q=bank[index%bank.length],p=progress(),done=Object.keys(p).filter(k=>k.startsWith(section+'-')).length;panel.innerHTML=`<div class="ieltsHero"><span class="ieltsEyebrow">PREMIUM IELTS PREPARATION</span><h2>Prepare with purpose.</h2><p>Use realistic task formats, immediate objective checks and Gemini feedback aligned to the four IELTS skill areas.</p><div class="ieltsHeroMeta"><span>${B.total().toLocaleString()} original tasks</span><span>${done} ${names[section]} completed</span><span>Gemini marking</span></div></div><div class="ieltsSkills">${B.sections.map(s=>`<button class="ieltsSkill ${s===section?'active':''}" data-ielts-section="${s}"><b>${icon[s]} ${names[s]}</b><small>500 practice tasks</small></button>`).join('')}</div><article class="ieltsQuestion"><div class="ieltsToolbar"><div><span class="ieltsEyebrow">${escape(q.type)} · ${q.part?'PART '+q.part:''}</span><h2>${escape(q.title)}</h2></div><span class="ieltsProgress">${index+1} / ${bank.length}</span></div>${q.source?`<div class="ieltsListeningPlay"><button class="secondary" data-play-listening>▶ Play once</button><small>The practice audio is generated from an original script.</small></div><details><summary>Show transcript after attempting</summary><div class="ieltsSource">${escape(q.source)}</div></details>`:''}${q.passage?`<div class="ieltsSource">${escape(q.passage)}</div>`:''}<p class="ieltsPrompt">${escape(q.prompt)}</p>${q.minimumWords?`<p><b>Minimum:</b> ${q.minimumWords} words</p>`:''}${answerControl(q)}<div class="ieltsActions"><button data-mark-ielts>Mark with Gemini</button><button class="secondary" data-next-ielts>Next task</button></div><div id="ieltsResult" class="ieltsResult" hidden></div></article><p class="ieltsDisclaimer">AI feedback is formative and cannot issue an official IELTS band score. Verify the current test format and official preparation resources with IELTS.</p>`;wire(q)}
 function responseValue(){const radio=document.querySelector('input[name="ieltsAnswer"]:checked');return radio?.value||document.getElementById('ieltsResponse')?.value.trim()||''}
 function showResult(r){const box=document.getElementById('ieltsResult');if(!box)return;box.hidden=false;box.innerHTML=`<div class="ieltsResultGrid"><div class="ieltsBand">${escape(r.band||'—')}</div><div><h3>${r.correct===true?'Correct':r.correct===false?'Review this answer':'Formative band guidance'}</h3><p>${escape(r.summary||'Your response has been reviewed.')}</p>${r.strengths?.length?`<b>Strengths</b><ul>${r.strengths.map(x=>`<li>${escape(x)}</li>`).join('')}</ul>`:''}${r.improvements?.length?`<b>Next improvements</b><ul>${r.improvements.map(x=>`<li>${escape(x)}</li>`).join('')}</ul>`:''}</div></div>`;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
 async function mark(q){const answer=responseValue();if(!answer){alert('Enter or select an answer first.');return}const btn=document.querySelector('[data-mark-ielts]');btn.disabled=true;btn.textContent='Gemini is reviewing…';try{if(!sb)throw Error('Secure marking service is unavailable.');const {data,error}=await sb.functions.invoke('ielts-marker',{body:{questionId:q.id,section:q.section,testType:q.type,prompt:q.prompt,passage:q.passage||'',transcript:q.source||'',referenceAnswer:q.answer||'',candidateAnswer:answer,rubric:q.rubric||[]}});if(error)throw error;if(!data?.result)throw Error(data?.error||'No marking result was returned.');showResult(data.result);saveResult(q.id,data.result)}catch(err){if(q.answer){const correct=answer.trim().toLowerCase()===String(q.answer).trim().toLowerCase();const r={band:correct?'Correct':'Review',correct,summary:correct?q.explanation:`The expected answer is “${q.answer}”. ${q.explanation}`,strengths:correct?['You located the relevant detail.']:[],improvements:correct?[]:['Check the exact wording and required answer format.']};showResult(r);saveResult(q.id,r)}else alert(err?.message||'Gemini marking is not available yet. Deploy the ielts-marker Edge Function.')}finally{btn.disabled=false;btn.textContent='Mark with Gemini'}}
 function wire(q){document.querySelectorAll('[data-ielts-section]').forEach(b=>b.onclick=()=>{section=b.dataset.ieltsSection;index=0;render()});document.querySelector('[data-next-ielts]').onclick=()=>{index=(index+1)%B.count(section);render()};document.querySelector('[data-mark-ielts]').onclick=()=>mark(q);document.querySelector('[data-play-listening]')?.addEventListener('click',()=>{if(!('speechSynthesis'in window))return alert('Audio playback is not supported in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.source);u.rate=.9;u.lang='en-GB';speechSynthesis.speak(u)})}
 function apply(){loadCss();addTab()}
 window.addEventListener('btv:membership',e=>{premium=!!e.detail?.active;render()});
 if(sb)sb.auth.getUser().then(async({data})=>{if(!data.user)return;const {data:p}=await sb.from('profiles').select('account_type').eq('id',data.user.id).maybeSingle();premium=p?.account_type==='premium';render()}).catch(()=>{});
 new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',apply):apply();setTimeout(apply,900);
})();
