const sb=window.btvSupabase,$=id=>document.getElementById(id);
let user=null,questions=[],current=null,selected=new Set(),answeredCurrent=false,bookmarks=new Set();
let session=[],sessionIndex=0,sessionCorrect=0,sessionAnswers=[],sessionMode='mock',adaptiveDifficulty='medium';
let timerId=null,remaining=1800,startedAt=0;
const order={easy:0,medium:1,hard:2};
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
async function init(){const {data:{session:s}}=await sb.auth.getSession();if(!s){location.href='index.html';return}user=s.user;$('loading').hidden=true;$('app').hidden=false;await Promise.all([loadQuestions(),loadBookmarks(),refreshStats(),loadHistory()]);bind();populateCategories();if(!restoreMock())showPractice()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('category').onchange=showPractice;$('difficulty').onchange=showPractice;$('loadPractice').onclick=showPractice;$('startAdaptive').onclick=startAdaptive;$('startMock').onclick=startMock;$('logout').onclick=async()=>{await sb.auth.signOut();location.href='index.html'}}
async function loadQuestions(){const {data,error}=await sb.from('nclex_questions').select('*').eq('is_active',true);if(error){toast(error.message);return}questions=data||[]}
async function loadBookmarks(){const {data}=await sb.from('nclex_bookmarks').select('question_id').eq('user_id',user.id);bookmarks=new Set((data||[]).map(x=>x.question_id))}
function populateCategories(){const cats=[...new Set(questions.map(q=>q.category))].sort();$('category').innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('')}
function eligible(category='all',difficulty='all'){return questions.filter(q=>(category==='all'||q.category===category)&&(difficulty==='all'||q.difficulty===difficulty))}
function pick(pool,exclude=[]){const available=pool.filter(q=>!exclude.includes(q.id));const source=available.length?available:pool;return source[Math.floor(Math.random()*source.length)]}
function showPractice(){const pool=eligible($('category').value,$('difficulty').value);if(!pool.length){$('practiceCard').innerHTML='<p>No NCLEX questions found. Run BTV-NCLEX-SETUP.sql in Supabase first.</p>';return}current=pick(pool,current?[current.id]:[]);answeredCurrent=false;selected.clear();renderQuestion($('practiceCard'),current,'practice')}
function optionsFor(q){return ['A','B','C','D','E','F'].filter(k=>q['option_'+k.toLowerCase()])}
function renderQuestion(box,q,mode){selected.clear();const multi=q.question_type==='select_all';box.innerHTML=`<div class="questionMeta"><span>${esc(q.category)} · ${esc(q.client_need)}</span><span>${esc(q.difficulty)}</span></div><h2>${esc(q.question_text)}</h2>${multi?'<div class="typeHint">Select all that apply</div>':''}<div class="options">${optionsFor(q).map(k=>`<button class="option" data-option="${k}"><b>${k}.</b> ${esc(q['option_'+k.toLowerCase()])}</button>`).join('')}</div><div class="explanation" hidden></div><div class="actions">${mode==='practice'?`<button class="bookmark">${bookmarks.has(q.id)?'★ Bookmarked':'☆ Bookmark'}</button>`:''}${multi?'<button class="submitAnswer">Submit answer</button>':''}${mode==='practice'?'<button class="next">Next question</button>':''}</div>`;
box.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{if(answeredCurrent)return;const k=b.dataset.option;if(multi){selected.has(k)?selected.delete(k):selected.add(k);b.classList.toggle('selected',selected.has(k))}else submitAnswer(mode,[k])});
if(multi)box.querySelector('.submitAnswer').onclick=()=>{if(!selected.size){toast('Select at least one option.');return}submitAnswer(mode,[...selected])};
if(mode==='practice'){box.querySelector('.next').onclick=showPractice;box.querySelector('.bookmark').onclick=toggleBookmark}}
function sameSet(a,b){return a.length===b.length&&[...a].sort().every((x,i)=>x===[...b].sort()[i])}
async function submitAnswer(mode,choices){if(answeredCurrent)return;answeredCurrent=true;const q=mode==='practice'?current:session[sessionIndex],ok=sameSet(choices,q.correct_options||[]);markAnswer(mode==='practice'?$('practiceCard'):mode==='adaptive'?$('adaptiveCard'):$('mockCard'),q,choices,mode==='practice');
const {error}=await sb.from('nclex_attempts').insert({user_id:user.id,question_id:q.id,selected_options:choices,is_correct:ok,mode});if(error)toast(error.message);
if(mode==='practice'){await refreshStats();return}sessionAnswers.push({q,choices,ok});if(ok)sessionCorrect++;setTimeout(()=>advanceSession(mode,ok),500)}
function markAnswer(box,q,choices,explain){box.querySelectorAll('.option').forEach(b=>{b.disabled=true;const k=b.dataset.option;if(q.correct_options.includes(k))b.classList.add('correct');else if(choices.includes(k))b.classList.add('wrong')});box.querySelector('.submitAnswer')?.setAttribute('disabled','disabled');if(explain){const e=box.querySelector('.explanation');e.hidden=false;e.innerHTML=`<b>${sameSet(choices,q.correct_options)?'Correct':'Not quite'}.</b> ${esc(q.rationale)}${q.test_strategy?`<span class="strategy"><b>Test strategy:</b> ${esc(q.test_strategy)}</span>`:''}`}}
async function toggleBookmark(){if(!current)return;const on=bookmarks.has(current.id);if(on){await sb.from('nclex_bookmarks').delete().eq('user_id',user.id).eq('question_id',current.id);bookmarks.delete(current.id)}else{await sb.from('nclex_bookmarks').insert({user_id:user.id,question_id:current.id});bookmarks.add(current.id)}$('practiceCard').querySelector('.bookmark').textContent=bookmarks.has(current.id)?'★ Bookmarked':'☆ Bookmark';await refreshStats()}
function readinessBand(pct){if(pct>=80)return'High';if(pct>=65)return'Moderate';if(pct>=50)return'Developing';return'Foundation'}
async function refreshStats(){const {data:a}=await sb.from('nclex_attempts').select('is_correct').eq('user_id',user.id);const list=a||[],correct=list.filter(x=>x.is_correct).length,pct=list.length?Math.round(correct/list.length*100):0;$('answered').textContent=list.length;$('accuracy').textContent=pct+'%';$('readiness').textContent=list.length<5?'New':readinessBand(pct);$('bookmarked').textContent=bookmarks.size;const {count}=await sb.from('nclex_exam_results').select('*',{count:'exact',head:true}).eq('user_id',user.id);$('mockCount').textContent=count||0}
function switchView(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));if(v==='history')loadHistory()}
function startAdaptive(){const length=Number($('adaptiveLength').value);if(questions.length<3){toast('Add more questions in Supabase first.');return}sessionMode='adaptive';session=[];sessionIndex=0;sessionCorrect=0;sessionAnswers=[];adaptiveDifficulty='medium';startedAt=Date.now();const first=pick(eligible('all','medium').length?eligible('all','medium'):questions);session.push(first);$('adaptiveIntro').hidden=true;$('adaptiveResult').hidden=true;$('adaptiveExam').hidden=false;$('adaptiveExam').dataset.length=String(length);renderAdaptive()}
function renderAdaptive(){answeredCurrent=false;$('adaptiveProgress').textContent=`Question ${sessionIndex+1} of ${$('adaptiveExam').dataset.length}`;$('adaptiveLevel').textContent=`${adaptiveDifficulty} difficulty`;renderQuestion($('adaptiveCard'),session[sessionIndex],'adaptive')}
function advanceSession(mode,ok){if(mode==='adaptive'){const length=Number($('adaptiveExam').dataset.length);const n=Math.max(0,Math.min(2,order[adaptiveDifficulty]+(ok?1:-1)));adaptiveDifficulty=['easy','medium','hard'][n];sessionIndex++;if(sessionIndex>=length){finishSession('adaptive');return}const used=session.map(q=>q.id),pool=eligible('all',adaptiveDifficulty);session.push(pick(pool.length?pool:questions,used));renderAdaptive();return}sessionIndex++;saveMockState();if(sessionIndex>=session.length)finishSession('mock');else renderMock()}
function saveMockState(){if(sessionMode!=='mock'||!session.length)return;localStorage.setItem('btv-nclex-mock-resume',JSON.stringify({ids:session.map(q=>q.id),index:sessionIndex,correct:sessionCorrect,answers:sessionAnswers.map(x=>({id:x.q.id,choices:x.choices,ok:x.ok})),remaining,startedAt}))}
function clearMockState(){localStorage.removeItem('btv-nclex-mock-resume')}
function restoreMock(){try{const s=JSON.parse(localStorage.getItem('btv-nclex-mock-resume')||'null');if(!s?.ids?.length||s.remaining<=0)return false;sessionMode='mock';session=s.ids.map(id=>questions.find(q=>String(q.id)===String(id))).filter(Boolean);if(!session.length)return false;sessionIndex=Math.min(s.index,session.length-1);sessionCorrect=s.correct||0;sessionAnswers=(s.answers||[]).map(x=>({q:questions.find(q=>String(q.id)===String(x.id)),choices:x.choices,ok:x.ok})).filter(x=>x.q);remaining=s.remaining;startedAt=s.startedAt||Date.now();$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;switchView('mock');renderMock();renderTimer();timerId=setInterval(()=>{remaining--;if(remaining%5===0)saveMockState();renderTimer();if(remaining<=0)finishSession('mock')},1000);return true}catch{return false}}
function startMock(){if(questions.length<3){toast('Add more questions in Supabase first.');return}sessionMode='mock';session=[...questions].sort(()=>Math.random()-.5).slice(0,Math.min(15,questions.length));sessionIndex=0;sessionCorrect=0;sessionAnswers=[];remaining=Number($('mockMinutes').value)*60;startedAt=Date.now();saveMockState();$('mockIntro').hidden=true;$('mockResult').hidden=true;$('mockExam').hidden=false;renderMock();renderTimer();timerId=setInterval(()=>{remaining--;renderTimer();if(remaining<=0)finishSession('mock')},1000)}
function renderMock(){answeredCurrent=false;$('mockProgress').textContent=`Question ${sessionIndex+1} of ${session.length}`;renderQuestion($('mockCard'),session[sessionIndex],'mock')}
function renderTimer(){const m=Math.floor(remaining/60),s=remaining%60;$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`}
function topicSummary(rows){const map={};rows.forEach(x=>{const n=x.q?.category||'General',r=map[n]||(map[n]={ok:0,total:0});r.total++;if(x.ok)r.ok++});return Object.entries(map).sort((a,b)=>(a[1].ok/a[1].total)-(b[1].ok/b[1].total))}
function reviewList(rows){return rows.filter(x=>!x.ok).slice(0,8).map(x=>'<li><b>'+esc(x.q.question_text)+'</b><br><span>'+esc(x.q.rationale)+'</span></li>').join('')||'<li>No incorrect answers to review.</li>'}
async function finishSession(mode){if(mode==='mock')clearMockState();if(timerId){clearInterval(timerId);timerId=null}const total=mode==='adaptive'?Number($('adaptiveExam').dataset.length):session.length,pct=total?Math.round(sessionCorrect/total*100):0,duration=Math.max(0,Math.round((Date.now()-startedAt)/1000)),band=readinessBand(pct);const {error}=await sb.from('nclex_exam_results').insert({user_id:user.id,exam:'NCLEX-RN',mode,total_questions:total,correct_answers:sessionCorrect,percentage:pct,readiness_band:band,duration_seconds:duration});if(error)toast(error.message);if(mode==='mock'&&new URLSearchParams(location.search).get('tier')==='short')await window.BTVCoins?.complete('nclex_short',pct,total,{time_used_seconds:duration,answers:sessionAnswers.map(x=>({question_id:x.q.id,selected:x.choices,correct:x.ok,topic:x.q.category}))});else if(mode==='mock')await window.BTVCoins?.complete('nclex_full',pct,total,{time_used_seconds:duration,answers:sessionAnswers.map(x=>({question_id:x.q.id,selected:x.choices,correct:x.ok,topic:x.q.category}))});const result=mode==='adaptive'?$('adaptiveResult'):$('mockResult'),exam=mode==='adaptive'?$('adaptiveExam'):$('mockExam');exam.hidden=true;result.hidden=false;const topics=topicSummary(sessionAnswers),weak=topics.slice(0,3),strong=[...topics].reverse().slice(0,3);result.innerHTML=`<span class="band">${esc(band)} readiness</span><h2>${pct}%</h2><p>You answered ${sessionCorrect} of ${total} correctly in ${Math.ceil(duration/60)} minutes.</p><div class="resultGrid78"><article><b>Strongest client needs</b><p>${strong.map(x=>esc(x[0])+' '+Math.round(x[1].ok/x[1].total*100)+'%').join('<br>')||'More answers needed'}</p></article><article><b>Revision priorities</b><p>${weak.map(x=>esc(x[0])+' '+Math.round(x[1].ok/x[1].total*100)+'%').join('<br>')||'More answers needed'}</p></article></div><details><summary>Review incorrect answers</summary><ol class="incorrectReview78">${reviewList(sessionAnswers)}</ol></details><button class="primary" id="restartSession">Try another ${mode==='adaptive'?'adaptive session':'mock'}</button>`;$('restartSession').onclick=()=>{result.hidden=true;(mode==='adaptive'?$('adaptiveIntro'):$('mockIntro')).hidden=false};await refreshStats();await loadHistory()}
async function loadHistory(){const {data,error}=await sb.from('nclex_exam_results').select('*').eq('user_id',user.id).order('completed_at',{ascending:false}).limit(20);if(error){$('historyList').textContent=error.message;return}const rows=data||[];$('historyList').innerHTML=rows.length?rows.map(r=>`<div class="historyRow"><div><b>${Number(r.percentage).toFixed(0)}% · ${esc(r.mode)}</b><small>${new Date(r.completed_at).toLocaleString()}</small></div><div><span class="band">${esc(r.readiness_band)}</span> <b>${r.correct_answers}/${r.total_questions}</b></div></div>`).join(''):'<p>No NCLEX sessions completed yet.</p>'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init();
