(()=>{
const $=id=>document.getElementById(id);const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const defaultPosts=[{name:'Ama K.',group:'CBT study group',text:'My tip: revise prioritisation and professional values every day, not only clinical facts.',likes:18,time:'Today'},{name:'Community team',group:'General community',text:'Welcome. Please protect patient confidentiality and never post identifiable workplace information.',likes:31,time:'Today'}];
const defaultJobs=[{id:1,title:'Band 5 Staff Nurse — Medicine',employer:'North Coast NHS Trust',location:'Newcastle',profession:'Nurse',type:'Full time',saved:false},{id:2,title:'Registered Midwife',employer:'Riverside Women’s Hospital',location:'Manchester',profession:'Midwife',type:'Full time',saved:false},{id:3,title:'International Nurse Preceptorship',employer:'Green Valley Health',location:'Leeds',profession:'Nurse',type:'Permanent',saved:false}];
let posts=read('btv-posts',defaultPosts),jobs=read('btv-jobs',defaultJobs),reviews=read('btv-reviews',[{employer:'Example NHS Trust',rating:4,text:'Supportive preceptorship and friendly ward team. Accommodation information could have been clearer.',time:'Recently'}]);
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderPosts(){if(!$('communityFeed'))return;$('communityFeed').innerHTML=posts.map((p,i)=>`<article class="postCard"><div class="postMeta"><span>${esc(p.name)} · ${esc(p.group)}</span><span>${esc(p.time)}</span></div><p>${esc(p.text)}</p><div class="postActions"><button data-like="${i}">♡ ${p.likes}</button><button data-reply="${i}">Reply</button></div></article>`).join('');document.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>{posts[b.dataset.like].likes++;write('btv-posts',posts);renderPosts()})}
$('postForm')?.addEventListener('submit',e=>{e.preventDefault();posts.unshift({name:read('btv-profile',{}).name||'You',group:$('postGroup').value,text:$('postText').value.trim(),likes:0,time:'Just now'});write('btv-posts',posts);$('postText').value='';renderPosts();updateStats()});
function renderJobs(){if(!$('jobList'))return;const q=($('jobSearch')?.value||'').toLowerCase(),t=$('jobType')?.value||'all';const shown=jobs.filter(j=>(t==='all'||j.profession===t)&&(`${j.title} ${j.employer} ${j.location}`.toLowerCase().includes(q)));$('jobList').innerHTML=shown.map(j=>`<article class="jobCard"><div class="jobMeta"><span class="badge">${esc(j.profession)}</span><span>${esc(j.type)}</span></div><h3>${esc(j.title)}</h3><p>${esc(j.employer)} · ${esc(j.location)}</p><div class="jobActions"><button data-savejob="${j.id}">${j.saved?'★ Saved':'☆ Save job'}</button><button data-apply="${j.id}">View application</button></div></article>`).join('')||'<div class="notice">No matching roles found.</div>';document.querySelectorAll('[data-savejob]').forEach(b=>b.onclick=()=>{let j=jobs.find(x=>x.id==b.dataset.savejob);j.saved=!j.saved;write('btv-jobs',jobs);renderJobs();updateStats()});document.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>alert('Demo vacancy: connect this button to the employer or NHS Jobs application page when publishing live roles.'))}
$('jobSearch')?.addEventListener('input',renderJobs);$('jobType')?.addEventListener('change',renderJobs);
function renderReviews(){if(!$('reviewList'))return;$('reviewList').innerHTML=reviews.map(r=>`<article class="reviewCard"><div class="reviewMeta"><b>${esc(r.employer)}</b><span>${esc(r.time)}</span></div><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>${esc(r.text)}</p></article>`).join('')}
$('reviewForm')?.addEventListener('submit',e=>{e.preventDefault();reviews.unshift({employer:$('reviewEmployer').value.trim(),rating:+$('reviewRating').value,text:$('reviewText').value.trim(),time:'Just now'});write('btv-reviews',reviews);e.target.reset();renderReviews();updateStats()});
const interviewQs=['Tell us about a time you recognised and escalated a deteriorating patient.','Describe a situation where you challenged unsafe practice.','How do you prioritise care when several patients need attention?','Tell us how you support dignity, inclusion and person-centred care.','Describe a medication error or near miss and what you learned.'];let qi=0;function showQ(){$('interviewQuestion').textContent=interviewQs[qi%interviewQs.length]}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));['cv','statement','interview'].forEach(x=>$('tool'+x[0].toUpperCase()+x.slice(1)).hidden=x!==b.dataset.tool)});
$('generateCv')?.addEventListener('click',()=>{const role=$('cvRole').value.trim()||'registered nurse or midwife',exp=$('cvExperience').value.trim();$('cvOutput').textContent=`Compassionate and accountable ${role} with experience delivering safe, person-centred care in busy clinical environments. Skilled in multidisciplinary communication, recognising deterioration, medicines safety, documentation and supporting patients through complex care journeys. ${exp?`Key evidence includes: ${exp}`:'Add your strongest measurable achievements to personalise this profile.'}`});
$('generateStatement')?.addEventListener('click',()=>{const role=$('statementRole').value.trim()||'the advertised role',spec=$('statementSpec').value.trim(),ev=$('statementEvidence').value.trim();$('statementOutput').textContent=`I am applying for ${role} because I am committed to safe, compassionate and evidence-based care. My experience has strengthened my clinical judgement, communication and ability to work responsibly within a multidisciplinary team.\n\nEvidence from my practice: ${ev||'Add a genuine example showing your actions, outcome and learning.'}\n\nI understand the role requires: ${spec||'Paste the person specification and address each essential criterion honestly.'}\n\nI would bring professionalism, curiosity and a strong commitment to continuous improvement. I will practise within my competence, escalate concerns promptly and uphold the NMC Code.`});
$('newInterviewQ')?.addEventListener('click',()=>{qi++;showQ();$('interviewAnswer').value='';$('interviewFeedback').textContent=''});$('scoreInterview')?.addEventListener('click',()=>{const a=$('interviewAnswer').value.trim(),words=a.split(/\s+/).filter(Boolean).length;let score=Math.min(100,20+(a.match(/\b(I|my)\b/gi)||[]).length*3+(a.match(/\b(patient|safety|escalat|communicat|reflect|outcome|learn)/gi)||[]).length*7+(words>80?25:words>40?15:5));$('interviewFeedback').textContent=`Estimated structure score: ${score}%\n\n${words<40?'Your answer is too brief. Use Situation, Task, Action and Result, then explain what you learned.':'Good length. Strengthen it with your exact actions, the patient-safety impact and a clear reflection.'}\n\nThis is coaching feedback, not an employer assessment.`});
$('upgradeBtn')?.addEventListener('click',()=>{localStorage.setItem('btv-premium-demo','true');renderPremium()});$('employerInterest')?.addEventListener('click',()=>alert('Interest recorded in demo mode. A live version would send this to your employer onboarding form.'));function renderPremium(){if(!$('premiumStatus'))return;const on=localStorage.getItem('btv-premium-demo')==='true';$('premiumStatus').textContent=on?'Premium demo is active on this device. AI tools and advanced learning are shown as unlocked.':'You are currently using the Free plan.';$('upgradeBtn').textContent=on?'Premium demo active':'Start demo premium'}
$('adminJobForm')?.addEventListener('submit',e=>{e.preventDefault();jobs.unshift({id:Date.now(),title:$('adminJobTitle').value.trim(),employer:$('adminEmployer').value.trim(),location:$('adminLocation').value.trim(),profession:$('adminProfession').value,type:'New vacancy',saved:false});write('btv-jobs',jobs);e.target.reset();renderJobs();updateStats();alert('Vacancy added to the demo jobs board.')});function updateStats(){if(!$('statPosts'))return;$('statPosts').textContent=posts.length;$('statSaved').textContent=jobs.filter(j=>j.saved).length;$('statReviews').textContent=reviews.length;$('statMembers').textContent=Math.max(1,read('btv-users',[]).length||1)}
renderPosts();renderJobs();renderReviews();renderPremium();updateStats();showQ();
})();
