(()=>{
 'use strict';
 const sb=window.btvSupabase;if(!sb)return;
 if(!document.querySelector('link[href^="platform-v30.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="platform-v30.css?v=30">');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const state={user:null,profile:null,notifications:[],courses:[],lessons:[],progress:[],services:[],bookings:[],articles:[]};
 const q=s=>document.querySelector(s);
 const status=(id,msg,bad=false)=>{const el=q(id);if(el){el.textContent=msg;el.className='btvNotice'+(bad?' error':'')}};
 function shell(){
  document.body.insertAdjacentHTML('beforeend',`<button class="btvPlatformButton" id="btvPlatformOpen">Explore & book <span id="btvUnreadBadge" class="btvBadge" hidden>0</span></button><section class="btvPlatform" id="btvPlatform" hidden aria-label="Beyond The Visa member centre"><header class="btvPlatformHeader"><button id="btvPlatformClose" aria-label="Close member centre">←</button><div><small>BEYOND THE VISA</small><h2>Member centre</h2></div></header><nav class="btvPlatformNav" aria-label="Member centre sections"><button class="active" data-btv-pane="discover">Guides</button><button data-btv-pane="learn">Video learning</button><button data-btv-pane="book">Bookings</button><button data-btv-pane="notify">Notifications <span id="btvNavBadge" class="btvBadge" hidden>0</span></button><button data-btv-pane="prefs">Preferences</button></nav><main class="btvPlatformMain"><section id="btv-discover" class="btvPane active"></section><section id="btv-learn" class="btvPane"></section><section id="btv-book" class="btvPane"></section><section id="btv-notify" class="btvPane"></section><section id="btv-prefs" class="btvPane"></section></main></section><dialog class="btvPlatformDialog" id="btvPlatformDialog"><div class="btvDialogBody" id="btvDialogBody"></div></dialog>`);
  q('#btvPlatformOpen').onclick=open;q('#btvPlatformClose').onclick=close;
  document.querySelectorAll('[data-btv-pane]').forEach(b=>b.onclick=()=>pane(b.dataset.btvPane));
 }
 async function session(){const {data:{user}}=await sb.auth.getUser();state.user=user;if(!user)return false;const [{data:p},{data:s}]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).maybeSingle(),sb.from('user_status').select('status,reason').eq('user_id',user.id).maybeSingle()]);if(s?.status==='suspended'){await sb.auth.signOut();alert('This account is suspended. Contact support if you believe this is a mistake.');location.reload();return false}state.profile=p||{};return true}
 async function open(){if(!await session()){alert('Please sign in to use the member centre.');return}q('#btvPlatform').hidden=false;document.body.style.overflow='hidden';await loadAll()}
 function close(){q('#btvPlatform').hidden=true;document.body.style.overflow=''}
 function pane(id){document.querySelectorAll('[data-btv-pane]').forEach(b=>b.classList.toggle('active',b.dataset.btvPane===id));document.querySelectorAll('.btvPane').forEach(x=>x.classList.toggle('active',x.id==='btv-'+id))}
 async function loadAll(){
  const calls=await Promise.all([sb.from('articles').select('*').eq('status','published').order('published_at',{ascending:false}),sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(100),sb.from('video_courses').select('*').eq('status','published').order('sort_order'),sb.from('video_lessons').select('*').eq('status','published').order('sort_order'),sb.from('video_progress').select('*'),sb.from('booking_services').select('*').eq('is_active',true),sb.from('bookings').select('*,booking_services(name,duration_minutes,currency,price_minor)').order('starts_at',{ascending:false})]);
  const keys=['articles','notifications','courses','lessons','progress','services','bookings'];calls.forEach((r,i)=>{state[keys[i]]=r.error?[]:(r.data||[])});renderAll();
 }
 function renderAll(){renderArticles();renderLearning();renderBookings();renderBookingActions();renderNotifications();renderPreferences();badges()}
 function rescheduleBooking(id){const min=new Date(Date.now()+36e5).toISOString().slice(0,16);q('#btvDialogBody').innerHTML=`<div class="btvDialogHead"><h2>Reschedule booking</h2><button data-close>Close</button></div><form class="btvForm" id="btvReschedule"><label>New start time<input name="start" type="datetime-local" min="${min}" required></label><button class="btvPrimary">Save new time</button><p id="btvRescheduleStatus"></p></form>`;q('#btvPlatformDialog').showModal();q('#btvDialogBody [data-close]').onclick=()=>q('#btvPlatformDialog').close();q('#btvReschedule').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);status('#btvRescheduleStatus','Checking availability…');const {error}=await sb.rpc('manage_own_booking',{p_booking:id,p_action:'reschedule',p_new_start:new Date(f.get('start')).toISOString()});if(error)return status('#btvRescheduleStatus',error.message,true);q('#btvPlatformDialog').close();await loadAll()}}
 function renderBookingActions(){const active=state.bookings.filter(b=>['pending_payment','confirmed'].includes(b.status)&&new Date(b.starts_at)>new Date());if(!active.length)return;const card=document.createElement('div');card.className='btvCard';card.innerHTML=`<h3>Change an upcoming booking</h3>${active.map(b=>`<div class="btvRow"><div><b>${esc(b.booking_services?.name||'Booking')}</b><small><br>${new Date(b.starts_at).toLocaleString()}</small></div><div><button class="secondary" data-reschedule-booking="${b.id}">Reschedule</button> <button class="secondary" data-cancel-booking="${b.id}">Cancel</button></div></div>`).join('')}`;q('#btv-book').append(card);card.querySelectorAll('[data-reschedule-booking]').forEach(b=>b.onclick=()=>rescheduleBooking(b.dataset.rescheduleBooking));card.querySelectorAll('[data-cancel-booking]').forEach(b=>b.onclick=async()=>{if(!confirm('Cancel this booking? The service cancellation deadline applies.'))return;const {error}=await sb.rpc('manage_own_booking',{p_booking:b.dataset.cancelBooking,p_action:'cancel',p_new_start:null});if(error)return alert(error.message);await loadAll()})}
 function renderArticles(){const dest=String(state.profile?.destination||'').toLowerCase();const list=state.articles.filter(a=>!a.country||a.country.toLowerCase()===dest);q('#btv-discover').innerHTML=`<div class="btvHero"><h3>Your trusted relocation library</h3><p>Current guides selected for ${esc(state.profile?.destination||'your destination')} and your professional journey.</p></div><div class="btvFilters"><input id="btvArticleSearch" type="search" placeholder="Search guides and articles"><select id="btvArticleCategory"><option value="">All categories</option>${[...new Set(list.map(x=>x.category).filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="btvGrid" id="btvArticleGrid"></div>`;const draw=()=>{const s=q('#btvArticleSearch').value.toLowerCase(),c=q('#btvArticleCategory').value;q('#btvArticleGrid').innerHTML=list.filter(a=>(!c||a.category===c)&&(a.title+' '+a.summary).toLowerCase().includes(s)).map(a=>`<article class="btvCard"><small>${esc(a.category||'GUIDE')} · ${esc(a.access_level)}</small><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><button data-article="${a.id}">Read guide</button></article>`).join('')||'<div class="btvEmpty">No published guides match this selection yet.</div>';document.querySelectorAll('[data-article]').forEach(b=>b.onclick=()=>showArticle(list.find(x=>x.id===b.dataset.article)))};q('#btvArticleSearch').oninput=draw;q('#btvArticleCategory').onchange=draw;draw()}
 function showArticle(a){q('#btvDialogBody').innerHTML=`<div class="btvDialogHead"><h2>${esc(a.title)}</h2><button data-close>Close</button></div><p>${esc(a.summary)}</p><div>${esc(a.body).replace(/\n/g,'<br>')}</div>`;q('#btvPlatformDialog').showModal();q('#btvDialogBody [data-close]').onclick=()=>q('#btvPlatformDialog').close();track('article_view','article',a.id)}
 function renderLearning(){const p=new Map(state.progress.map(x=>[x.lesson_id,x]));q('#btv-learn').innerHTML=`<div class="btvHero"><h3>Video learning centre</h3><p>Continue where you stopped and build confidence one lesson at a time.</p></div><div class="btvFilters"><input id="btvLessonSearch" type="search" placeholder="Search lessons"><select id="btvLessonCat"><option value="">All categories</option>${[...new Set(state.courses.map(x=>x.category).filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="btvGrid" id="btvLessonGrid"></div>`;const draw=()=>{const s=q('#btvLessonSearch').value.toLowerCase(),cat=q('#btvLessonCat').value;q('#btvLessonGrid').innerHTML=state.lessons.filter(l=>{const c=state.courses.find(x=>x.id===l.course_id);return (!cat||c?.category===cat)&&(l.title+' '+l.description).toLowerCase().includes(s)}).map(l=>{const pr=p.get(l.id),pct=l.duration_seconds?Math.min(100,Math.round((pr?.seconds_watched||0)/l.duration_seconds*100)):pr?.completed?100:0;return `<article class="btvCard"><small>${esc(l.presenter||'Beyond The Visa')} · ${Math.ceil(l.duration_seconds/60)} min</small><h3>${esc(l.title)}</h3><p>${esc(l.description)}</p><div class="btvProgress"><span style="width:${pct}%"></span></div><p>${pr?.completed?'Completed':pct+'% watched'}</p><button data-lesson="${l.id}">${pct?'Continue':'Watch lesson'}</button></article>`}).join('')||'<div class="btvEmpty">No published video lessons match yet.</div>';document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>lesson(state.lessons.find(x=>x.id===b.dataset.lesson)))};q('#btvLessonSearch').oninput=draw;q('#btvLessonCat').onchange=draw;draw()}
 function embed(url){try{const u=new URL(url);if(u.hostname.includes('youtu')){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v');return `https://www.youtube-nocookie.com/embed/${encodeURIComponent(id||'')}`}if(u.hostname.includes('vimeo.com'))return `https://player.vimeo.com/video/${encodeURIComponent(u.pathname.split('/').filter(Boolean).pop())}`;return u.href}catch{return ''}}
 function lesson(l){const src=embed(l.video_url);q('#btvDialogBody').innerHTML=`<div class="btvDialogHead"><h2>${esc(l.title)}</h2><button data-close>Close</button></div>${src?`<iframe class="btvVideo" src="${esc(src)}" title="${esc(l.title)}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`:'<div class="btvNotice error">This lesson URL is not valid.</div>'}<p>${esc(l.description)}</p>${l.transcript?`<details><summary>Transcript</summary><p>${esc(l.transcript)}</p></details>`:''}<button class="btvPrimary" data-complete>Mark lesson complete</button>`;q('#btvPlatformDialog').showModal();q('#btvDialogBody [data-close]').onclick=()=>q('#btvPlatformDialog').close();q('#btvDialogBody [data-complete]').onclick=async()=>{const {error}=await sb.from('video_progress').upsert({user_id:state.user.id,lesson_id:l.id,seconds_watched:l.duration_seconds,completed:true,last_watched_at:new Date().toISOString()});if(error)return alert(error.message);await loadAll();q('#btvPlatformDialog').close()};track('video_view','lesson',l.id)}
 function renderBookings(){q('#btv-book').innerHTML=`<div class="btvHero"><h3>Book expert support</h3><p>Choose a service, then select an available future time in your own timezone.</p></div><div class="btvGrid">${state.services.map(s=>`<article class="btvCard"><small>${s.duration_minutes} minutes</small><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><strong>${s.price_minor?new Intl.NumberFormat(undefined,{style:'currency',currency:s.currency}).format(s.price_minor/100):'Free'}</strong><p><button data-service="${s.id}">Choose this service</button></p></article>`).join('')||'<div class="btvEmpty">No services are available right now.</div>'}</div><h3>My bookings</h3><div class="btvCard">${state.bookings.map(b=>`<div class="btvRow"><div><b>${esc(b.booking_services?.name||'Booking')}</b><small><br>${new Date(b.starts_at).toLocaleString()} · ${esc(b.status.replaceAll('_',' '))}</small></div><span>${esc(b.payment_status)}</span></div>`).join('')||'<p>No bookings yet.</p>'}</div>`;document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>bookingForm(state.services.find(x=>x.id===b.dataset.service)))}
 function bookingForm(s){const min=new Date(Date.now()+36e5).toISOString().slice(0,16);q('#btvDialogBody').innerHTML=`<div class="btvDialogHead"><h2>Book ${esc(s.name)}</h2><button data-close>Close</button></div><form class="btvForm" id="btvBookingForm"><label>Name<input name="name" required value="${esc(state.profile.full_name||'')}"></label><label>Email<input name="email" type="email" required value="${esc(state.user.email||'')}"></label><label>Start time<input name="start" type="datetime-local" min="${min}" required></label><label>Role or band<input name="role" maxlength="80"></label><label>What would you like help with?<textarea name="notes" maxlength="1200"></textarea></label><button class="btvPrimary">${s.price_minor?'Continue to secure payment':'Confirm free booking'}</button><p id="btvBookingStatus"></p></form>`;q('#btvPlatformDialog').showModal();q('#btvDialogBody [data-close]').onclick=()=>q('#btvPlatformDialog').close();q('#btvBookingForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);status('#btvBookingStatus','Saving your booking…');const {data:id,error}=await sb.rpc('create_booking',{p_service:s.id,p_starts:new Date(f.get('start')).toISOString(),p_name:f.get('name'),p_email:f.get('email'),p_role:f.get('role')||null,p_notes:f.get('notes')||null});if(error)return status('#btvBookingStatus',error.message,true);if(s.price_minor){const {data:{session}}=await sb.auth.getSession();const response=await fetch(`${window.BTV_SUPABASE_URL||'https://wuvgktmzkzrdvbpqfmek.supabase.co'}/functions/v1/booking-checkout`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({bookingId:id})});const out=await response.json();if(!response.ok)return status('#btvBookingStatus',out.error||'Payment could not start.',true);location.href=out.authorization_url}else{status('#btvBookingStatus','Booking confirmed.');setTimeout(async()=>{q('#btvPlatformDialog').close();await loadAll()},900)}}}
 function renderNotifications(){q('#btv-notify').innerHTML=`<div class="btvHero"><h3>Notification centre</h3><p>Deadlines, booking updates and new learning content in one place.</p><button class="btvPrimary" id="btvReadAll">Mark all as read</button></div><div>${state.notifications.map(n=>`<article class="btvCard ${n.read_at?'':'btvUnread'}" data-notification="${n.id}"><small>${new Date(n.created_at).toLocaleString()} · ${esc(n.category)}</small><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p>${n.action_url?`<button data-action="${esc(n.action_url)}">Open</button>`:''}</article>`).join('')||'<div class="btvEmpty">You have no notifications yet.</div>'}</div>`;q('#btvReadAll').onclick=async()=>{await sb.rpc('mark_all_notifications_read');await loadAll()};document.querySelectorAll('[data-notification]').forEach(x=>x.onclick=async()=>{if(!state.notifications.find(n=>n.id===x.dataset.notification)?.read_at){await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',x.dataset.notification);await loadAll()}})}
 function renderPreferences(){q('#btv-prefs').innerHTML=`<div class="btvHero"><h3>Notification preferences</h3><p>You decide which updates you receive. In-app notifications remain available if browser push is unavailable.</p></div><form class="btvCard btvForm" id="btvPrefs"><label class="btvSwitch"><input type="checkbox" name="push"> Enable browser push notifications</label>${[['cbt','New CBT questions'],['nclex','New NCLEX questions'],['study','Study reminders'],['journey','Journey deadlines'],['documents','Document expiry'],['bookings','Booking reminders'],['payments','Payment confirmations'],['subscriptions','Subscription changes'],['content','New articles and videos'],['announcements','Admin announcements']].map(([k,l])=>`<label class="btvSwitch"><input type="checkbox" name="${k}" checked> ${l}</label>`).join('')}<button class="btvPrimary">Save preferences</button><p id="btvPrefsStatus"></p></form>`;loadPrefs();q('#btvPrefs').onsubmit=savePrefs}
 async function loadPrefs(){const {data}=await sb.from('notification_preferences').select('*').eq('user_id',state.user.id).maybeSingle();if(!data)return;const f=q('#btvPrefs');f.push.checked=data.push_enabled;Object.entries(data.categories||{}).forEach(([k,v])=>{if(f[k])f[k].checked=!!v})}
 async function savePrefs(e){e.preventDefault();const f=e.currentTarget,categories={};['cbt','nclex','study','journey','documents','bookings','payments','subscriptions','content','announcements'].forEach(k=>categories[k]=f[k].checked);let push=f.push.checked;if(push){if(!('serviceWorker'in navigator)||!('PushManager'in window)){push=false;f.push.checked=false;return status('#btvPrefsStatus','Browser push is unsupported here. In-app notifications remain active.',true)}if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission!=='granted'){push=false;f.push.checked=false;return status('#btvPrefsStatus','Push permission was not granted. In-app notifications remain active.',true)}const reg=await navigator.serviceWorker.ready;const key=document.querySelector('meta[name="btv-vapid-key"]')?.content;if(!key)return status('#btvPrefsStatus','Push is not configured by the site administrator yet.',true);const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlKey(key)});const j=sub.toJSON();await sb.from('push_subscriptions').upsert({user_id:state.user.id,endpoint:j.endpoint,p256dh:j.keys.p256dh,auth_key:j.keys.auth,user_agent:navigator.userAgent,enabled:true},{onConflict:'endpoint'})}const {error}=await sb.from('notification_preferences').upsert({user_id:state.user.id,push_enabled:push,categories,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});status('#btvPrefsStatus',error?error.message:'Preferences saved.',!!error)}
 function urlKey(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b),a=new Uint8Array(r.length);for(let i=0;i<r.length;i++)a[i]=r.charCodeAt(i);return a}
 function badges(){const n=state.notifications.filter(x=>!x.read_at).length;['#btvUnreadBadge','#btvNavBadge'].forEach(id=>{const el=q(id);el.hidden=!n;el.textContent=n>99?'99+':n})}
 async function track(name,type,id){if(state.user)await sb.from('app_events').insert({user_id:state.user.id,event_name:name,entity_type:type,entity_id:String(id)})}
 document.addEventListener('DOMContentLoaded',async()=>{shell();if(await session()){const {count}=await sb.from('notifications').select('id',{count:'exact',head:true}).is('read_at',null);if(count){q('#btvUnreadBadge').hidden=false;q('#btvUnreadBadge').textContent=count}}});
})();
