(()=>{
 'use strict';
 if(window.__btvPremiumAccessV304)return;window.__btvPremiumAccessV304=true;
 const sb=window.btvSupabase;
 if(!document.querySelector('link[href^="premium-access-v30.4.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="premium-access-v30.4.css?v=30.4">');
 let premium=localStorage.getItem('btv-premium')==='yes';
 const examTabs='[data-learn-tab="cbt"],[data-learn-tab="nclex"]';
 function openPremium(){document.querySelector('[data-open-premium]')?.click()||document.querySelector('[data-premium-request]')?.click()}
 function protectTab(button){if(!button)return;button.dataset.premiumLocked=String(!premium);if(premium)return;const id=button.dataset.learnTab,panel=document.getElementById(id+'Lesson');if(panel&&!panel.querySelector('.premiumFeatureMessage'))panel.innerHTML=`<div class="premiumFeatureMessage"><span>PREMIUM EXAM PREPARATION</span><h2>${id==='cbt'?'CBT':'NCLEX'} learning is included with Premium</h2><p>Unlock the complete question bank, mock examinations, explanations, performance insights and personalised readiness reports.</p><button data-open-exam-premium>View Premium membership</button></div>`}
 function protectLaunchers(){document.querySelectorAll('[data-cbt-centre],[data-nclex-centre]').forEach(card=>{card.classList.toggle('premiumExamLock',!premium);const link=card.querySelector('a');if(link&&!premium)link.textContent='Premium · Unlock learning centre →'})}
 function protectAdvanced(){const dashboard=document.getElementById('dashboardV3');if(dashboard&&!premium){const targets=[dashboard.querySelector('.readinessRing'),dashboard.querySelector('.dashboardStats article:nth-child(2)'),dashboard.querySelector('.dashboardColumns .dashboardPanel:nth-child(2)')];targets.forEach((target,i)=>{if(!target||target.querySelector('.premiumLockOverlay'))return;target.classList.add('premiumProtectedBlock');const overlay=document.createElement('div');overlay.className='premiumLockOverlay';overlay.innerHTML=`<div><b>${i===0?'Personalised readiness report':i===1?'Advanced exam performance':'Weak-topic learning insights'}</b><small>Available with Premium membership</small><button data-open-exam-premium>Unlock Premium</button></div>`;target.append(overlay)})}document.querySelector('[data-learn-tab="interview"]')?.setAttribute('data-premium-locked',String(!premium));document.querySelector('[data-learn-tab="cv"]')?.setAttribute('data-premium-locked',String(!premium));document.querySelectorAll('.planCompare li').forEach(li=>{if(li.textContent.includes('Daily practice questions'))li.lastChild.textContent='Essential relocation guides'})}
 function apply(){document.querySelectorAll(examTabs).forEach(protectTab);protectLaunchers();protectAdvanced()}
 document.addEventListener('click',event=>{const target=event.target.closest(`${examTabs},[data-cbt-centre] a,[data-nclex-centre] a,[data-open-exam-premium]`);if(!target)return;if(target.matches('[data-open-exam-premium]')){event.preventDefault();event.stopImmediatePropagation();openPremium();return}if(premium){if(target.matches(examTabs)){event.preventDefault();event.stopImmediatePropagation();location.href=target.dataset.learnTab==='cbt'?'cbt.html':'nclex.html'}return}event.preventDefault();event.stopImmediatePropagation();openPremium();setTimeout(()=>alert('Complete CBT and NCLEX preparation is reserved for Premium members.'),120)},true);
 document.addEventListener('click',event=>{const tab=event.target.closest('[data-learn-tab="interview"],[data-learn-tab="cv"]');if(!tab||premium)return;event.preventDefault();event.stopImmediatePropagation();openPremium();setTimeout(()=>alert('Premium CV and interview learning resources are included with Premium membership.'),120)},true);
 window.addEventListener('btv:membership',event=>{premium=!!event.detail?.active;apply()});
 let scheduled=false;new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;apply()})}).observe(document.documentElement,{childList:true,subtree:true});
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',apply):apply();
 setTimeout(apply,800);setTimeout(apply,1800);
 if(new URLSearchParams(location.search).get('premium')==='open')setTimeout(openPremium,700);
 if(sb)sb.auth.getUser().then(async({data})=>{if(!data.user)return;const {data:profile}=await sb.from('profiles').select('account_type').eq('id',data.user.id).maybeSingle();premium=profile?.account_type==='premium';apply()}).catch(()=>{});
})();
