(function(){
  'use strict';
  if(window.__btvPremiumV29)return;window.__btvPremiumV29=true;
  if(!document.querySelector('link[href^="premium-v29.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='premium-v29.css?v=29';document.head.append(link)}
  const sb=window.btvSupabase,$=s=>document.querySelector(s),premiumKey='btv-premium';
  let membership={plan:'free',active:false,subscription:null},price=null,loading=false;
  const symbols={GHS:'GH₵',NGN:'₦',KES:'KSh',ZAR:'R',UGX:'USh',GBP:'£',USD:'US$',CAD:'C$',AUD:'A$',NZD:'NZ$',EUR:'€'};
  function currency(){try{return window.serviceMarket?.().currency||'USD'}catch{return'USD'}}
  function money(p){return p?`${symbols[p.currency]||p.currency+' '}${Number(p.amount).toLocaleString('en-GB',{maximumFractionDigits:2})}`:'Regional price'}
  function fmtDate(value){return value?new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):'—'}
  async function invoke(name,body={}){const {data,error}=await sb.functions.invoke(name,{body});if(error){try{const detail=await error.context?.clone().json();throw Error(detail?.error||detail?.message||error.message)}catch(e){if(e.message!==error.message)throw e;throw Error(error.message)}}return data}
  function build(){
    if($('#premium'))return;
    const s=document.createElement('section');s.id='premium';s.className='screen premiumV29';s.innerHTML=`<div class="pageTitle"><button class="back" data-premium-back>←</button><div><span>BEYOND THE VISA PREMIUM</span><h1>Move forward with confidence</h1></div></div><div id="premiumBody"></div>`;document.querySelector('main').append(s);s.querySelector('[data-premium-back]').onclick=()=>window.openScreen?.('home');
    const quick=$('.quick');if(quick&&!quick.querySelector('[data-open-premium]')){const card=document.createElement('button');card.dataset.openPremium='';card.innerHTML='<i>◆</i><span>Premium membership</span><small>Advanced tools and support</small>';quick.append(card)}
    render()
  }
  function featureRows(){return['Advanced CBT and NCLEX performance insights','Personalised readiness reports','AI study-plan builder','Premium CV and interview resources','Priority support and early access'].map(x=>`<li><span>✓</span>${x}</li>`).join('')}
  function freeView(){return `<div class="premiumHeroV29"><span>YOUR INTERNATIONAL CAREER, ORGANISED</span><h2>Everything you need to prepare, progress and arrive ready.</h2><p>Keep the essential app free. Upgrade when you want deeper exam insight, personalised planning and priority support.</p><div class="trustStrip"><span>Secure Paystack checkout</span><span>Cancel renewal anytime</span><span>Regional pricing</span></div></div><div class="planCompare"><article><div class="planHead"><span>FREE</span><h2>Free plan</h2><b>£0 <small>forever</small></b></div><ul><li><span>✓</span>Core journey checklist</li><li><span>✓</span>Cost planner</li><li><span>✓</span>Job search and saved jobs</li><li><span>✓</span>Daily practice questions</li><li><span>✓</span>Basic Zibur guidance</li></ul><button class="planCurrent" disabled>Your current plan</button></article><article class="premiumPlan"><div class="popularLabel">MOST COMPLETE</div><div class="planHead"><span>PREMIUM</span><h2>Premium plan</h2><b id="premiumPrice">${money(price)} <small>/ month</small></b><p id="premiumMarket">${price?`Regional price for ${price.market}`:'Loading your regional price…'}</p></div><ul>${featureRows()}</ul><button data-start-premium>Upgrade securely</button><small>Recurring monthly membership through Paystack. Recurring methods depend on the member’s country and Paystack availability.</small></article></div><div class="premiumAssurance"><article><b>Protected account access</b><p>Premium is activated only after Paystack verifies the transaction.</p></article><article><b>No browser-only unlock</b><p>Membership status comes from your secure Supabase account.</p></article><article><b>Clear control</b><p>See renewal details and cancel from the membership page.</p></article></div>`}
  function premiumView(){const sub=membership.subscription||{},cancel=sub.cancel_at_period_end;return `<div class="memberWelcome"><div><span>◆ PREMIUM MEMBER</span><h2>Your complete preparation toolkit is active.</h2><p>Use your advanced resources, monitor readiness and keep your plan under control.</p></div><div class="memberSeal">◆<small>PREMIUM</small></div></div><div class="memberGrid"><article><span>MEMBERSHIP</span><h3>${cancel?'Renewal cancelled':'Premium monthly'}</h3><p>${cancel?`Access remains available until ${fmtDate(sub.current_period_end)}.`:`Next renewal period ends ${fmtDate(sub.current_period_end)}.`}</p><button data-manage-membership>${cancel?'View membership':'Manage renewal'}</button></article><article><span>READINESS REPORT</span><h3>Personalised next actions</h3><p>Combine journey progress and learning performance into one focused view.</p><button data-premium-action="readiness">Open readiness report</button></article><article><span>AI STUDY PLAN</span><h3>Study with structure</h3><p>Create a weekly plan around your exam, available time and weak topics.</p><button data-premium-action="study">Build study plan</button></article><article><span>PRIORITY SUPPORT</span><h3>Get help faster</h3><p>Send a question directly to the support inbox with Premium priority.</p><button data-premium-action="support">Contact support</button></article></div><div class="premiumLibrary"><span>PREMIUM LIBRARY</span><h2>Tools designed to save time</h2><div><article><b>Interview answer workbook</b><small>STAR structure, values and clinical scenarios</small></article><article><b>CV evidence checklist</b><small>Registration, impact statements and role alignment</small></article><article><b>Arrival planner</b><small>First-week and first-month practical actions</small></article><article><b>Exam weak-topic review</b><small>Turn performance data into a revision list</small></article></div></div>`}
  function render(){const box=$('#premiumBody');if(!box)return;box.innerHTML=membership.active?premiumView():freeView();box.querySelector('[data-start-premium]')?.addEventListener('click',checkout);box.querySelector('[data-manage-membership]')?.addEventListener('click',manage);box.querySelectorAll('[data-premium-action]').forEach(b=>b.onclick=()=>action(b.dataset.premiumAction))}
  async function loadPrice(){const wanted=currency();let {data}=await sb.from('premium_prices').select('code,market,currency,amount,interval').eq('currency',wanted).eq('active',true).maybeSingle();if(!data)({data}=await sb.from('premium_prices').select('code,market,currency,amount,interval').eq('currency','USD').eq('active',true).maybeSingle());price=data||null;render()}
  async function status(){try{const data=await invoke('subscription-status');membership=data;localStorage.setItem(premiumKey,data.active?'yes':'no');window.dispatchEvent(new CustomEvent('btv:membership',{detail:data}));badge();render();return data}catch(error){console.warn('Membership:',error.message);localStorage.setItem(premiumKey,'no');badge();render();return membership}}
  async function checkout(){if(loading)return;loading=true;const button=$('[data-start-premium]'),old=button?.textContent;if(button){button.disabled=true;button.textContent='Opening Paystack…'}try{await window.BTVManagerInbox?.record('premium_request','Premium membership checkout','User started Paystack Premium checkout.',{currency:currency()},'normal');const data=await invoke('premium-checkout',{currency:currency()});if(!data?.url)throw Error('Paystack did not return a checkout link.');location.assign(data.url)}catch(error){alert(error.message||'Premium checkout is unavailable.');if(button){button.disabled=false;button.textContent=old}}finally{loading=false}}
  function manage(){const sub=membership.subscription||{},box=$('#premiumBody');if(sub.cancel_at_period_end)return alert(`Your renewal is cancelled. Premium remains active until ${fmtDate(sub.current_period_end)}.`);if(!confirm('Cancel Premium renewal? You will keep access until the end of your current paid period.'))return;const button=$('[data-manage-membership]');button.disabled=true;button.textContent='Cancelling…';invoke('cancel-subscription').then(data=>{alert(data.message);return status()}).catch(error=>{alert(error.message);button.disabled=false;button.textContent='Manage renewal'})}
  function action(kind){if(kind==='study'){document.querySelector('.aiPlanCard')?.click();return}if(kind==='support'){document.querySelector('[data-open="contact"]')?.click();setTimeout(()=>{const reason=$('#contactReason');if(reason)reason.value='General question'},100);return}if(kind==='readiness'){window.openScreen?.('home');window.renderDashboardInsights?.();setTimeout(()=>document.querySelector('.careerDashboard')?.scrollIntoView({behavior:'smooth'}),200)}}
  function badge(){let b=$('#premiumSecureBadge');if(!membership.active){b?.remove();return}if(!b){b=document.createElement('button');b.id='premiumSecureBadge';b.innerHTML='◆ <span>PREMIUM</span>';b.onclick=open;(document.querySelector('.brand')||document.querySelector('header')).after(b)}}
  function open(){build();render();window.openScreen?.('premium')}
  function paymentReturn(){const p=new URLSearchParams(location.search);if(p.get('premium')!=='return')return;open();const box=$('#premiumBody');if(box)box.innerHTML='<div class="paymentVerifying"><span>◆</span><h2>Confirming your membership</h2><p>Paystack is securely verifying the payment. This normally takes only a moment.</p></div>';let attempts=0,timer=setInterval(async()=>{attempts++;const data=await status();if(data.active||attempts>=8){clearInterval(timer);if(!data.active)alert('Payment confirmation is still pending. Refresh this page shortly.')}},2500)}
  document.addEventListener('click',event=>{const target=event.target.closest('[data-premium-request],[data-open-premium]');if(!target)return;event.preventDefault();event.stopImmediatePropagation();open()},true);
  document.addEventListener('click',event=>{const feature=event.target.closest('.aiPlanCard,[data-premium-feature]');if(!feature||membership.active)return;event.preventDefault();event.stopImmediatePropagation();open();setTimeout(()=>alert('This advanced tool is included with Premium membership.'),150)},true);
  function start(){build();loadPrice();status().then(paymentReturn);setInterval(status,300000)}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start()
})();
