const verifiedDate='11 July 2026';
const stagePricing={
 uk:{
  'Passport':['Varies by issuing country','Variable','Check renewal and priority fees with the authority that issued your passport.','https://www.gov.uk/browse/abroad/passports'],
  'English language evidence':['IELTS UKVI about £257; OET AU$587','Official test prices','Confirm which evidence and scores your professional regulator accepts before booking.','https://ielts.org/test-centres/british-council-e-assessment'],
  'Professional registration':['Nurses: £140 evaluation + £153 registration','Official NMC fees','Other professions use different regulators and fees. Nurses requiring the full Test of Competence may pay about £1,170 before resits.','https://www.nmc.org.uk/registration/information-for-internationally-trained-applicants/'],
  'Competence tests':['NMC nurses: £83 CBT + £794 OSCE','Official NMC fees','Only applies where the regulator requires a Test of Competence. Resits cost extra.','https://www.nmc.org.uk/registration/joining-the-register/toc/toc-nursing-and-midwifery/'],
  'Police clearance':['Varies by issuing country','Variable','Issuing country, delivery speed and authentication affect the cost.','https://www.gov.uk/government/publications/criminal-records-checks-for-overseas-applicants'],
  'Job offer and sponsorship':['Usually £0 to the applicant','Employer-led','A genuine sponsor manages the Certificate of Sponsorship. Never pay someone to guarantee a job.','https://www.gov.uk/health-care-worker-visa/your-job'],
  'Visa application':['£324 up to 3 years; £628 over 3 years','Official visa fee','Each dependant applies separately. Eligible Health and Care Worker applicants do not pay the immigration health surcharge.','https://www.gov.uk/health-care-worker-visa/how-much-it-costs'],
  'Travel':['Plan £500–£1,200','Planning estimate','Airfare varies by departure city, season, baggage and booking date. Replace this with a live quote.','https://www.gov.uk/foreign-travel-advice'],
  'Accommodation':['Plan £1,000–£2,500 initially','Planning estimate','Allow for a deposit, advance rent and temporary accommodation. Location makes a large difference.','https://www.gov.uk/private-renting'],
  'Settle in':['Plan £300–£800','Planning estimate','Transport, a SIM, household basics and emergency funds vary by location and employer support.','https://www.gov.uk/moving-to-uk']
 },
 au:{'Professional registration':['Check the current regulator fee schedule','Official calculator required','Registration cost depends on profession and assessment route.','https://www.ahpra.gov.au/Registration/Registration-Process/Fees.aspx'],'Visa application':['Skilled Nominated 190 example: A$6,140','Official visa example','Australia has several visa routes. Use the official estimator for your exact subclass and family.','https://immi.homeaffairs.gov.au/visas/visa-pricing-estimator']},
 ca:{'Immigration route':['Work permit C$155 + biometrics C$85 if required','Official federal fees','An open work permit can add C$100. Provincial registration and residence routes have separate fees.','https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit-outside.html']},
 nz:{'Visa application':['AEWV example: NZ$480 + NZ$1,060 levy','Official fee-guide example','Citizenship, location and visa type can affect the amount. Confirm with the official tool.','https://www.immigration.govt.nz/process-to-apply/applying-for-a-visa/fees-processing-times-and-refunds/how-much-visa-applications-cost-and-when-to-pay/']},
 ie:{'Employment permit or visa':['Critical Skills or General permit: usually €1,000','Official permit fee','A General Employment Permit for six months or less is €500. Refund rules depend on who applies.','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/fees/']},
 us:{'Employer and immigration route':['Petition-based visa application: US$205','Official visa-fee example','Employer petition, credential evaluation, state licensing and legal costs are separate.','https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/fees/fees-visa-services.html']}
};
function priceFor(title){return stagePricing[state.country]?.[title]||['Add your estimate','Variable stage','Profession, location and pathway determine this cost. Verify it with the linked authority before paying.',{uk:'https://www.gov.uk/health-care-worker-visa',au:'https://immi.homeaffairs.gov.au/',ca:'https://www.canada.ca/en/services/immigration-citizenship.html',nz:'https://www.immigration.govt.nz/',ie:'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/',us:'https://travel.state.gov/content/travel/en/us-visas/employment.html'}[state.country]]}
function showStepDetail(title,description){const m=priceFor(title);let d=document.getElementById('stepDialog');if(!d){d=document.createElement('dialog');d.id='stepDialog';d.innerHTML='<form method="dialog"><button class="closeStep" value="cancel">×</button><span class="stepVerified"></span><h2 class="stepName"></h2><p class="stepDesc"></p><div class="stepPrice"><small>PLANNING COST</small><strong></strong><em></em></div><p class="stepDetail"></p><a class="officialLink" target="_blank" rel="noopener">Open official source ↗</a><p class="stepWarning">Check the source again before paying. Fees and eligibility can change.</p></form>';document.body.append(d);const css=document.createElement('style');css.textContent='#stepDialog{border:0;border-radius:22px;padding:0;max-width:min(92vw,480px);background:transparent}#stepDialog::backdrop{background:#071c1fc0}#stepDialog form{position:relative;background:var(--card);color:var(--ink);padding:24px;border-radius:22px}.closeStep{position:absolute;right:14px;top:14px;width:36px;height:36px;border:0;border-radius:11px;background:var(--mint);font-size:22px}.stepVerified{font-size:10px;letter-spacing:.12em;color:var(--teal);font-weight:900}.stepName{font-family:Georgia,serif;margin:7px 45px 8px 0}.stepDesc,.stepDetail{color:var(--muted);line-height:1.5}.stepPrice{background:var(--mint);padding:15px;border-radius:16px;margin:14px 0}.stepPrice small,.stepPrice strong,.stepPrice em{display:block}.stepPrice strong{font-size:20px;margin:5px 0}.stepPrice em{font-style:normal;color:var(--muted);font-size:11px}.officialLink{display:block;text-align:center;padding:12px;border-radius:12px;background:var(--brand);color:#fff;text-decoration:none;font-weight:800}.stepWarning{font-size:10px;text-align:center;color:var(--muted)}';document.head.append(css)}d.querySelector('.stepVerified').textContent='VERIFIED ONLINE · '+verifiedDate;d.querySelector('.stepName').textContent=title;d.querySelector('.stepDesc').textContent=description;d.querySelector('.stepPrice strong').textContent=m[0];d.querySelector('.stepPrice em').textContent=m[1];d.querySelector('.stepDetail').textContent=m[2];d.querySelector('.officialLink').href=m[3];d.showModal()}
renderChecklist=function(){const c=country();state.done[state.country]=state.done[state.country]||{};$('checklistItems').innerHTML='';c.steps.forEach((s,i)=>{const m=priceFor(s[0]),row=document.createElement('div');row.className='checkItem';row.innerHTML=`<input id="step-${i}" type="checkbox" ${state.done[state.country][i]?'checked':''}><label for="step-${i}"><b>${s[0]}</b><small>${s[1]}</small><button type="button" class="priceHint">${m[0]} · Details →</button></label>`;row.querySelector('input').onchange=e=>{state.done[state.country][i]=e.target.checked;save();render();if(e.target.checked)toast('Step completed')};row.querySelector('.priceHint').onclick=e=>{e.preventDefault();showStepDetail(s[0],s[1])};$('checklistItems').append(row)});document.querySelectorAll('.priceHint').forEach(b=>b.style.cssText='display:block;border:0;background:transparent;color:var(--teal);font-size:12px;font-weight:800;padding:7px 0 0;text-align:left')};
render();
