(()=>{'use strict';
if(window.__btvV68)return;window.__btvV68=true;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function profile(){for(const key of ['btv-v1','btv-profile']){try{const value=JSON.parse(localStorage.getItem(key)||'{}');if(Object.keys(value).length)return value}catch{}}return {}}
function installBrand(){const brand=$('.authBrand');if(!brand||brand.dataset.v68)return;brand.dataset.v68='yes';brand.innerHTML='<img class="signupEmblemV68" src="signup-emblem-v68.png?v=68" alt="Beyond The Visa"><h1 class="v68SrOnly">Beyond The Visa</h1>'}
function communityMarkup(){return `<div class="communityV68"><section class="communityHeroV68"><span>COMMUNITY HUB</span><h2>Connect beyond borders</h2><p>Meet nurses and midwives around the world who share your ambition and are preparing for the same destination. Build friendships, study together and support one another through every stage.</p><div class="communityHeroMetaV68"><b>Global professional network</b><b>Country-specific connections</b><b>Designed for nurses and midwives</b></div></section><section class="communitySoonV68"><div class="communitySoonBadgeV68">COMING SOON</div><h3>A safer, focused place to connect</h3><p>Community is being carefully built and tested. Join the early-access list and we will notify you when it launches.</p><button type="button" data-community-notify>Notify me when it is available</button><p class="communityNotifyStatusV68" role="status"></p></section><div class="communityGridV68"><article><i>🤝</i><h3>Find your people</h3><ul><li>Find study partners</li><li>Friend requests</li><li>Search users</li><li>Profile pictures</li></ul></article><article><i>💬</i><h3>Private conversations</h3><ul><li>Private messaging</li><li>Online and offline status</li><li>Typing indicators</li><li>Read receipts</li></ul></article><article><i>🌍</i><h3>Shared destinations</h3><ul><li>Country-specific groups</li><li>CBT and OSCE discussion rooms</li><li>Accountability partners</li><li>Wider global audience</li></ul></article><article><i>🛡️</i><h3>Safety by design</h3><ul><li>Block a user</li><li>Report concerns</li><li>Professional community standards</li><li>Privacy-conscious controls</li></ul></article></div></div>`}
function installCommunity(){const screen=$('#community');if(!screen||screen.dataset.v68)return false;screen.dataset.v68='yes';screen.innerHTML=communityMarkup();return true}
function toast(text){if(typeof window.toast==='function')window.toast(text)}
async function notify(button){const status=button.closest('.communitySoonV68,.ieltsSoon')?.querySelector('.communityNotifyStatusV68')||button.parentElement?.querySelector('[role="status"]');button.disabled=true;button.textContent='Saving your interest…';try{if(!window.btvSupabase)throw Error('Please wait for the secure connection and try again.');const {data,error}=await window.btvSupabase.auth.getUser();if(error)throw error;if(!data.user)throw Error('Please sign in first so we know where to send your invitation.');const p=profile(),source=button.closest('.ieltsSoon')?'ielts-coming-soon':'community';const row={user_id:data.user.id,email:data.user.email,destination:p.country||p.destination||null,source,updated_at:new Date().toISOString()};const result=await window.btvSupabase.from('community_waitlist').upsert(row,{onConflict:'user_id,source'});if(result.error)throw result.error;button.textContent='You are on the early-access list ✓';if(status)status.textContent='Thank you. We will notify you when this feature is ready.';toast('Early-access interest saved.')}catch(e){button.disabled=false;button.textContent='Notify me when it is available';if(status)status.textContent=e.message||'We could not save your request.';toast(e.message||'We could not save your request.')}}
function openZibur(prefill=''){if(typeof window.BTVFloatingZiburToggle==='function'){window.BTVFloatingZiburToggle(true);requestAnimationFrame(()=>{const input=$('#ziburFloatInput');if(input&&prefill){input.value=prefill;input.focus()}});return}toast('Zibur is still loading. Please try again in a moment.')}
function route(event){const notifyButton=event.target.closest('[data-community-notify]');if(notifyButton){event.preventDefault();event.stopImmediatePropagation();notify(notifyButton);return}const zibur=event.target.closest('[data-open="assistant"],[data-open-target="assistant"],[data-open-zibur],[data-ask-life]');if(zibur&&!zibur.closest('#ziburFloatPanel')){event.preventDefault();event.stopImmediatePropagation();openZibur(zibur.matches('[data-ask-life]')?'Please explain the next step in my relocation journey.':'');return}const country=event.target.closest('.country');if(country)setTimeout(()=>window.BTVIELTS?.refresh?.(),0);const learn=event.target.closest('[data-open="learn"],[data-open-target="learn"],[data-target="learn"]');if(learn)setTimeout(()=>window.BTVIELTS?.refresh?.(),0)}
function installIcons(){if(!document.querySelector('link[data-v68-style]')){const style=document.createElement('link');style.rel='stylesheet';style.href='release-library-v68.css?v=68';style.dataset.v68Style='yes';document.head.append(style)}if(document.querySelector('link[data-v68-icon]'))return;for(const rel of ['icon','apple-touch-icon']){const link=document.createElement('link');link.rel=rel;link.href='brand-emblem-v68.png?v=68';link.type='image/png';link.dataset.v68Icon='yes';document.head.append(link)}}
function installLibrary(){const learn=$('#learn'),tabs=learn?.querySelector('.learnTabs'),book=learn?.querySelector('[data-btv-books]');if(!learn||!tabs||!book)return false;let tab=tabs.querySelector('[data-learn-tab="library"]'),panel=$('#libraryLesson');if(!tab){tab=document.createElement('button');tab.dataset.learnTab='library';tab.textContent='Library';tabs.append(tab)}if(!panel){panel=document.createElement('section');panel.id='libraryLesson';panel.className='learnPanel libraryLessonV68';learn.append(panel)}if(!panel.dataset.v68){panel.dataset.v68='yes';panel.innerHTML='<div class="learningLibraryHeroV68"><span>LEARNING LIBRARY</span><h2>Professional resources in one place</h2><p>Open books selected for your pathway without interrupting your learning session.</p></div><div class="learningLibraryGridV68"></div>';panel.querySelector('.learningLibraryGridV68').append(book);book.innerHTML='<span>▤</span><div><b>Book library</b><small>Published books matched to your pathway and access level</small></div><i>Open library →</i>'}tab.onclick=()=>window.showLearningTab?.('library');return true}
function init(){installIcons();installBrand();installCommunity();installLibrary();window.BTVIELTS?.refresh?.()}
document.addEventListener('click',route,true);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();setTimeout(init,500);setTimeout(init,1600);
})();
