(()=>{
 'use strict';
 if(window.__btvReleaseV33)return;window.__btvReleaseV33=true;
 const q=s=>document.querySelector(s),sb=window.btvSupabase;
 function buildChat(){let panel=q('#ziburFloatPanel');if(panel)return panel;panel=document.createElement('aside');panel.id='ziburFloatPanel';panel.className='ziburFloatPanel';panel.hidden=true;panel.setAttribute('aria-label','Ask Zibur chat');panel.innerHTML='<header class="ziburFloatHead"><div class="ziburFloatMark">Z</div><div><b>Ask Zibur</b><small>Journey guidance without leaving this page</small></div><button type="button" aria-label="Close floating chat">×</button></header><div class="ziburFloatChat" aria-live="polite"><article class="ziburFloatMessage">Hi, I’m Zibur. What would you like help with today?</article></div><form class="ziburFloatForm"><label class="sr" for="ziburFloatQuestion">Ask Zibur</label><input id="ziburFloatQuestion" maxlength="1500" placeholder="Ask about your journey…" autocomplete="off"><button aria-label="Send message">↑</button><small class="ziburFloatNote">General guidance only. Verify official, legal, immigration and clinical decisions.</small></form>';document.body.append(panel);panel.querySelector('.ziburFloatHead button').onclick=()=>toggle(false);panel.querySelector('form').onsubmit=send;return panel}
 function toggle(force){const panel=buildChat(),show=force??panel.hidden;panel.hidden=!show;q('#btvPlatformOpen')?.setAttribute('aria-expanded',String(show));if(show)setTimeout(()=>q('#ziburFloatQuestion')?.focus(),30)}window.BTVFloatingZiburToggle=toggle;
 function bubble(text,user=false,thinking=false){const box=q('.ziburFloatChat'),a=document.createElement('article');a.className='ziburFloatMessage'+(user?' user':'')+(thinking?' thinking':'');a.textContent=text;box.append(a);box.scrollTop=box.scrollHeight;return a}
 function context(){try{return typeof window.ziburContext==='function'?window.ziburContext():{profile:JSON.parse(localStorage.getItem('btv-profile')||'null'),journey:JSON.parse(localStorage.getItem('btv-v1')||'{}')}}catch{return{}}}
 async function send(event){event.preventDefault();const input=q('#ziburFloatQuestion'),question=input.value.trim();if(!question)return;input.value='';bubble(question,true);const wait=bubble('Zibur is thinking…',false,true),history=JSON.parse(localStorage.getItem('btv-zibur-history')||'[]');let answer='';try{if(sb){const result=await sb.functions.invoke('zibur-chat',{body:{question,history:history.slice(-10),context:context()}});if(!result.error)answer=result.data?.answer||''}}catch{}if(!answer){try{answer=typeof window.contextualZibur==='function'?window.contextualZibur(question):''}catch{}}answer=answer||'I cannot reach the secure service just now. Open Journey to review your next unchecked step and its official source.';wait.textContent=answer;wait.classList.remove('thinking');history.push({role:'user',content:question},{role:'assistant',content:answer});localStorage.setItem('btv-zibur-history',JSON.stringify(history.slice(-20)))}
 function wireFloating(){const button=q('#btvPlatformOpen');if(!button)return;button.dataset.floatChatReady='yes';button.setAttribute('aria-controls','ziburFloatPanel');if(!button.hasAttribute('aria-expanded'))button.setAttribute('aria-expanded','false');button.onclick=event=>{event.preventDefault();event.stopPropagation();toggle()}}
 function jobsShortcut(){const quick=[...document.querySelectorAll('#home .quick button')],button=quick.find(x=>x.dataset.uniqueShortcut==='jobs')||quick.find(x=>x.textContent.toLowerCase().includes('my documents'));if(!button)return;if(button.dataset.jobsReplacement!=='yes'){button.dataset.jobsReplacement='yes';button.dataset.uniqueShortcut='jobs';button.innerHTML='<i>⌕</i><span>Job search</span><small>Find roles and review saved jobs</small>';button.onclick=()=>{window.openScreen?.('jobs');window.renderJobs?.()};button.dataset.open='jobs'}button.hidden=false;quick.filter(x=>x!==button&&x.textContent.toLowerCase().includes('job search')).forEach(x=>{x.hidden=true;x.dataset.duplicateNavigation='true'})}
 function wire(){wireFloating();jobsShortcut()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',wire):wire();setTimeout(wire,600);setTimeout(wire,1700);new MutationObserver(wire).observe(document.documentElement,{childList:true,subtree:true});
})();
