(()=>{
 'use strict';
 if(window.__btvReleaseV37)return;window.__btvReleaseV37=true;
 function calculationPractice(){
  const panel=document.getElementById('calculationsLesson');if(!panel||typeof calculations==='undefined')return;
  const c=calculations[calcIndex];
  panel.innerHTML=`<div class="calcCard drugCalcCard"><div class="calcMeta"><span>Question ${calcIndex+1} of ${calculations.length}</span><span>Score ${calcScore}/${calcIndex}</span></div><h2>Drug calculation practice</h2><p class="calcQuestion">${c.q}</p><section class="workingCalculator" aria-label="On-screen calculator"><div class="workingCalculatorHead"><div><b>On-screen calculator</b><small>Use this for your working</small></div><output id="workingCalcDisplay" aria-live="polite">0</output></div><div class="workingCalcKeys">${['7','8','9','÷','4','5','6','×','1','2','3','−','.','0','⌫','+'].map(x=>`<button type="button" data-working-key="${x}" class="${'÷×−+'.includes(x)?'operator':''}">${x}</button>`).join('')}<button type="button" data-working-key="clear" class="utility">Clear</button><button type="button" data-working-key="equals" class="equals">=</button></div></section><form class="calcAnswer"><label for="calcInput">Your final answer</label><div class="calcAnswerRow"><input id="calcInput" type="text" inputmode="none" readonly required placeholder="Tap to enter answer" aria-controls="answerNumberPad" aria-expanded="false"><span>${c.u}</span><button>Check</button></div></form><div id="answerNumberPad" class="calcPad answerNumberPad" hidden>${['7','8','9','4','5','6','1','2','3','.','0','⌫'].map(x=>`<button type="button" data-answer-key="${x}" class="${x==='⌫'?'action':''}">${x}</button>`).join('')}<button type="button" data-answer-key="clear" class="action">Clear</button><button type="button" data-answer-key="hide" class="action">Hide keypad</button></div><div id="calcFeedback" class="calcFeedback">Use the calculator for your working, then tap the answer box to enter your final answer.</div></div><p class="notice">Education only. Always follow local medicines policy and independent checking requirements in clinical practice.</p>`;
  const input=panel.querySelector('#calcInput'),pad=panel.querySelector('#answerNumberPad'),display=panel.querySelector('#workingCalcDisplay');let expression='',locked=false;
  const showPad=()=>{pad.hidden=false;input.setAttribute('aria-expanded','true');pad.querySelector('button')?.focus()};
  const hidePad=()=>{pad.hidden=true;input.setAttribute('aria-expanded','false')};
  input.addEventListener('click',showPad);input.addEventListener('focus',()=>{if(pad.hidden)showPad()});
  panel.querySelectorAll('[data-answer-key]').forEach(button=>button.onclick=()=>{const key=button.dataset.answerKey;if(key==='hide'){hidePad();return}if(key==='clear')input.value='';else if(key==='⌫')input.value=input.value.slice(0,-1);else if(key!=='.'||!input.value.includes('.'))input.value+=key});
  const updateDisplay=()=>{display.textContent=expression||'0'};
  panel.querySelectorAll('[data-working-key]').forEach(button=>button.onclick=()=>{const key=button.dataset.workingKey;if(key==='clear'){expression='';updateDisplay();return}if(key==='⌫'){expression=expression.slice(0,-1);updateDisplay();return}if(key==='equals'){if(!expression)return;try{const safe=expression.replaceAll('÷','/').replaceAll('×','*').replaceAll('−','-');if(!/^[0-9+*/.()\-\s]+$/.test(safe))throw new Error();const result=Function(`"use strict";return (${safe})`)();expression=Number.isFinite(result)?String(Math.round((result+Number.EPSILON)*1000000)/1000000):'';display.textContent=expression||'Error'}catch{expression='';display.textContent='Error'}return}const operator='÷×−+'.includes(key);if(operator&&(!expression||'÷×−+'.includes(expression.slice(-1))))expression=expression.slice(0,-1)+key;else if(key!=='.'||!expression.split(/[÷×−+]/).pop().includes('.'))expression+=key;updateDisplay()});
  const check=()=>{if(locked)return;const value=Number(input.value),feedback=panel.querySelector('#calcFeedback');if(input.value!==''&&Math.abs(value-c.a)<0.001){locked=true;calcScore++;hidePad();feedback.className='calcFeedback good';feedback.innerHTML=`<b>Correct — ${c.a} ${c.u}.</b><br>Loading the next example…`;setTimeout(()=>{calcIndex=(calcIndex+1)%calculations.length;if(calcIndex===0)calcScore=0;calculationPractice()},1300)}else{feedback.className='calcFeedback bad';feedback.innerHTML=`<b>Not quite. Try again.</b><br>Hint: ${c.hint}`}};
  panel.querySelector('.calcAnswer').onsubmit=event=>{event.preventDefault();check()};
 }
 window.renderCalculator=calculationPractice;
 if(document.getElementById('calculationsLesson'))calculationPractice();
})();
