const visitGuides={uk:['London','Edinburgh','Belfast','Cardiff','Lake District'],au:['Sydney','Melbourne','Blue Mountains','Great Barrier Reef'],ca:['Toronto','Vancouver','Banff','Montréal'],nz:['Auckland','Wellington','Rotorua','Queenstown'],ie:['Dublin','Galway','Cliffs of Moher','Killarney'],us:['New York City','Washington, D.C.','Grand Canyon','San Francisco']};
const thinkingHints=['What tells you how many tablets make the prescribed dose?','Identify how much medicine is contained in the stated liquid volume.','Which unit must your answer use? Make both quantities use that unit first.','Think about how many smaller units fit inside one milligram.','If the volume is shared evenly across the hours, what does one hour receive?','Which time unit must match drops per minute before you begin?','What does “per kilogram” ask you to do with the patient’s weight?','How many concentration-sized portions reach the prescribed dose?','Convert the volume into the pump’s unit before considering time.','What fraction of the whole ampoule dose is needed? Estimate first.','Make the prescribed dose and capsule strength use the same unit.','Should an hourly rate be larger than 250 mL when the infusion lasts only half an hour?'];
calculations.forEach((x,i)=>x.hint=thinkingHints[i]||'List what you know, choose the required unit and estimate the likely size of the answer.');

function profileExtra(){return JSON.parse(localStorage.getItem('btv-profile-extra')||'{}')}
function syncDestination(){const p=userProfile?.();if(p&&p.destination!==state.country){p.destination=state.country;if(state.country!=='uk')delete p.region;localStorage.setItem('btv-profile',JSON.stringify(p))}if(typeof renderCoachingPackages==='function'&&document.getElementById('coachPackages'))renderCoachingPackages();if(typeof renderCvLesson==='function')renderCvLesson();const icon=document.querySelector('[data-open="costs"] i');if(icon)icon.textContent=country().symbol;refreshRegionalLabels?.()}
const v14Countries=renderCountries;renderCountries=function(){v14Countries();document.querySelectorAll('#countryGrid .country').forEach(b=>b.addEventListener('click',()=>{syncDestination();render();toast(`${country().name} selected · currency changed to ${country().currency}`)}))};

let guideMuted=localStorage.getItem('btv-guide-muted')==='yes';
function addMute(){const controls=document.querySelector('.videoControls');if(!controls||controls.querySelector('[data-guide-mute]'))return;const b=document.createElement('button');b.type='button';b.dataset.guideMute='';b.textContent=guideMuted?'🔇':'🔊';b.title=guideMuted?'Unmute Zibur':'Mute Zibur';b.onclick=()=>{guideMuted=!guideMuted;localStorage.setItem('btv-guide-muted',guideMuted?'yes':'no');if(guideMuted)speechSynthesis.cancel();toast(guideMuted?'Zibur muted':'Zibur voice on');renderGuide()};controls.append(b)}
new MutationObserver(addMute).observe(document.getElementById('guideLesson'),{subtree:true,childList:true});document.addEventListener('click',e=>{if(guideMuted&&e.target.matches('[data-video-play]'))speechSynthesis.cancel()},true);addMute();

function avatar(name){const n=(name||'U').trim()[0]?.toUpperCase()||'U';return`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><rect width="120" height="120" rx="30" fill="#dcefed"/><text x="60" y="78" text-anchor="middle" font-size="56" font-family="Georgia" fill="#0d5558">${n}</text></svg>`)}`}
function updateProfileButton(){let b=document.getElementById('headerProfile');if(!b){b=document.createElement('button');b.id='headerProfile';b.className='headerProfile';b.onclick=()=>openScreen('profile');document.querySelector('.headerActions').prepend(b)}const d=profileExtra(),name=d.preferred||authAccount?.()?.name||'User';b.innerHTML=`<img src="${d.photo||avatar(name)}" alt="Open ${name}'s profile">`}
function buildProfile(){if(document.getElementById('profile'))return;const s=document.createElement('section');s.id='profile';s.className='screen';s.innerHTML=`<div class="pageTitle"><button class="back">←</button><div><span>PERSONALISE YOUR SUPPORT</span><h1>Your profile</h1></div></div><div class="profileHero"><label class="photoPicker"><img id="pfPhoto"><span>＋</span><input id="pfFile" type="file" accept="image/*"></label><div><h2 id="pfName"></h2><p>These answers help Zibur understand your goals.</p></div></div><form id="profileForm" class="profileForm"><label>Preferred name<input id="pfPreferred"></label><label>Clinical specialty<input id="pfSpecialty" placeholder="e.g. Adult nursing"></label><label>Experience<select id="pfExperience"><option>Student or newly qualified</option><option>Under 2 years</option><option>2–5 years</option><option>6–10 years</option><option>More than 10 years</option></select></label><label>Target arrival<input id="pfArrival" type="month"></label><label>Learning preference<select id="pfLearning"><option>Short step-by-step guidance</option><option>Detailed explanations</option><option>Videos and demonstrations</option><option>Practice questions</option></select></label><label>Priority support<select id="pfSupport"><option>Registration and documents</option><option>Finding a job</option><option>Interview confidence</option><option>Budgeting and relocation</option><option>Workplace culture</option></select></label><label class="wide">My goal<textarea id="pfGoal" rows="4"></textarea></label><button>Save profile</button></form>`;document.querySelector('main').append(s);s.querySelector('.back').onclick=()=>openScreen('home');const d=profileExtra(),a=authAccount?.();pfName.textContent=d.preferred||a?.name||'Your profile';pfPhoto.src=d.photo||avatar(a?.name);[['pfPreferred','preferred'],['pfSpecialty','specialty'],['pfExperience','experience'],['pfArrival','arrival'],['pfLearning','learning'],['pfSupport','support'],['pfGoal','goal']].forEach(([id,k])=>document.getElementById(id).value=d[k]||document.getElementById(id).value);pfFile.onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>1500000)return toast('Choose an image smaller than 1.5 MB');const r=new FileReader();r.onload=()=>{const x=profileExtra();x.photo=r.result;localStorage.setItem('btv-profile-extra',JSON.stringify(x));pfPhoto.src=r.result;updateProfileButton()};r.readAsDataURL(f)};profileForm.onsubmit=e=>{e.preventDefault();const old=profileExtra(),x={...old,preferred:pfPreferred.value.trim(),specialty:pfSpecialty.value.trim(),experience:pfExperience.value,arrival:pfArrival.value,learning:pfLearning.value,support:pfSupport.value,goal:pfGoal.value.trim()};localStorage.setItem('btv-profile-extra',JSON.stringify(x));pfName.textContent=x.preferred||a?.name;updateProfileButton();toast('Profile saved')}}

function supportReply(q){const t=q.toLowerCase();if(/interview|mock/.test(t))return'Book from Learning → Interview. I can help you choose a trial or full session.';if(/cv|resume/.test(t))return'Open Learning → CV for training, review and writing-service requests.';if(/visa|registration|document/.test(t))return'Open the relevant Journey step for its guide and official source. Confirm eligibility with the authority.';if(/human|agent|person|call/.test(t))return'Complete the contact form above to save a request for the support team. Human live-chat routing requires the secure messaging backend.';return'I can guide you with journey steps, costs, interviews, CVs or workplace culture. Which area do you need?'}
function bubble(text,mine){const m=document.createElement('div');m.className='supportBubble'+(mine?' mine':'');m.textContent=text;liveChatMessages.append(m);liveChatMessages.scrollTop=liveChatMessages.scrollHeight}
function buildLiveChat(){const f=document.getElementById('contactForm');if(!f||document.getElementById('liveSupport'))return;const c=document.createElement('div');c.id='liveSupport';c.className='liveSupport';c.innerHTML='<div class="liveHead"><b>Live support chat</b><small>Guided support · online</small></div><div id="liveChatMessages"><div class="supportBubble">Hi! What can we help you with today?</div></div><form id="liveChatForm"><input id="liveChatInput" required placeholder="Write a message…"><button>Send</button></form>';f.closest('.card').append(c);liveChatForm.onsubmit=e=>{e.preventDefault();const q=liveChatInput.value.trim();if(!q)return;bubble(q,true);liveChatInput.value='';setTimeout(()=>bubble(supportReply(q)),300)}}

function arrivalWelcome(){const places=visitGuides[state.country];if(!places)return;const o=document.createElement('div');o.className='arrivalWelcome';o.innerHTML=`<div class="arrivalCard"><div class="arrivalFlag">${country().flag}</div><span class="coachTag">JOURNEY COMPLETE</span><h1>Welcome to ${country().name}!</h1><p>You completed every preparation step. Settle safely, learn your local services and celebrate this new chapter.</p><h3>Places to discover when you are settled</h3><div class="places">${places.map(p=>`<article><b>${p}</b><small>Explore responsibly after checking local travel advice, opening times and costs.</small></article>`).join('')}</div><button>Start my new chapter</button></div>`;document.body.append(o);o.querySelector('button').onclick=()=>o.remove()}
document.addEventListener('change',e=>{if(!e.target.matches('.checkItem input[type="checkbox"]')||!e.target.checked)return;setTimeout(()=>{const k=`btv-arrival-${state.country}`;if(completed()===country().steps.length&&!localStorage.getItem(k)){localStorage.setItem(k,'shown');arrivalWelcome()}},50)});

const oldZibur=contextualZibur;contextualZibur=function(question){const q=question.toLowerCase(),c=ziburContext(),p=c.profile||{},d=profileExtra(),last=[...ziburHistory].reverse().find(x=>x.role==='assistant')?.content;if(/why|explain|more|what do you mean|how do i do that|and then/.test(q)&&last)return`Let’s continue from my last answer: ${last} Tell me which part you want broken into smaller actions and I will work through it with you.`;if(/goal|about me|profile|remember/.test(q))return`I remember you as ${d.preferred||authAccount?.()?.name||'a healthcare professional'}: ${p.profession||'healthcare professional'}${d.specialty?' specialising in '+d.specialty:''}, qualified in ${p.qualificationCountry||'your origin country'} and preparing for ${c.country||'your destination'}${p.region?' ('+p.region+')':''}.${d.experience?' Experience: '+d.experience+'.':''}${d.arrival?' Target arrival: '+d.arrival+'.':''}${d.goal?' Your goal is: '+d.goal:''}`;if(/stress|worried|anxious|overwhelmed|scared/.test(q))return`This journey can feel overwhelming. We do not need to solve everything today. Focus on the first unchecked Journey step. Would you like me to turn it into three smaller actions?`;if(/plan|timeline|schedule/.test(q))return`Build the plan around prerequisites: evidence and registration first, then tests and applications, followed by immigration, notice periods, travel and contingency.${d.arrival?' Your saved target is '+d.arrival+'.':''} Add deadlines inside Journey so I can help prioritise them.`;return oldZibur(question)};

const style=document.createElement('style');style.textContent='.headerProfile{width:42px!important;height:42px!important;border-radius:14px!important;overflow:hidden;padding:0!important}.headerProfile img{width:100%;height:100%;object-fit:cover}.profileHero{display:flex;gap:16px;align-items:center;background:linear-gradient(135deg,var(--brand),#287578);color:#fff;border-radius:22px;padding:20px;margin-bottom:14px}.photoPicker{position:relative;width:90px;height:90px;flex:0 0 90px;border-radius:28px;overflow:hidden;background:var(--mint)}.photoPicker img{width:100%;height:100%;object-fit:cover}.photoPicker span{position:absolute;right:5px;bottom:5px;background:var(--gold);border-radius:50%;padding:4px 7px}.photoPicker input{display:none}.profileForm{display:grid;grid-template-columns:1fr 1fr;gap:12px;background:var(--card);padding:18px;border-radius:20px}.profileForm label{display:grid;gap:6px;font-size:11px;font-weight:900;color:var(--muted)}.profileForm input,.profileForm select,.profileForm textarea{padding:11px;border:1px solid var(--line);border-radius:11px;background:var(--bg);color:var(--ink)}.profileForm .wide,.profileForm button{grid-column:1/-1}.profileForm button,.liveSupport button,.arrivalCard button{border:0;border-radius:11px;background:var(--teal);color:#fff;padding:12px;font-weight:900}.liveSupport{margin-top:16px;border:1px solid var(--line);border-radius:18px;overflow:hidden}.liveHead{display:flex;justify-content:space-between;background:var(--brand);color:#fff;padding:13px}.liveHead small{color:#c9e2e0}#liveChatMessages{height:220px;overflow:auto;padding:12px;background:var(--bg);display:grid;align-content:start;gap:8px}.supportBubble{max-width:85%;padding:9px 11px;border-radius:13px;background:var(--card)}.supportBubble.mine{margin-left:auto;background:var(--brand);color:#fff}.liveSupport form{display:flex;gap:7px;padding:10px}.liveSupport input{flex:1;min-width:0;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--bg);color:var(--ink)}.arrivalWelcome{position:fixed;inset:0;z-index:130;background:#06282ddd;display:grid;place-items:center;padding:18px}.arrivalCard{max-width:560px;max-height:90vh;overflow:auto;background:var(--card);color:var(--ink);border-radius:28px;padding:24px;text-align:center}.arrivalFlag{font-size:70px}.places{display:grid;grid-template-columns:1fr 1fr;gap:9px;text-align:left}.places article{padding:12px;background:var(--bg);border-radius:13px}.places b,.places small{display:block}.places small{color:var(--muted);margin-top:4px}@media(max-width:520px){.profileForm,.places{grid-template-columns:1fr}.profileForm .wide,.profileForm button{grid-column:auto}}';document.head.append(style);
buildProfile();updateProfileButton();buildLiveChat();syncDestination();
