import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { createRequire } from "node:module";

const require=createRequire(import.meta.url);
const careerjet=require("../api/_lib/careerjet-core.ts");
const read=(path)=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
const response=(status,body,headers={})=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json",...headers}});
const rawJob=(overrides={})=>({title:"Registered Nurse",company:"St Mary's Hospital",date:"Fri, 01 Aug 2026 09:00:00 GMT",description:"Permanent registered nurse vacancy with hybrid training.",locations:"London, Greater London",salary:"GBP 35000 - 42000 per year",salary_currency_code:"GBP",salary_min:35000,salary_max:42000,salary_type:"Y",site:"hospital.example",url:"https://jobviewtrack.com/v2/registered-nurse-123",contract_type:"permanent",work_hours:"full-time",...overrides});

test("Careerjet uses the official v4 endpoint and keeps the credential out of the URL",async()=>{let call;const result=await careerjet.requestPage({affiliateId:"server-secret",country:"gb",keywords:"registered nurse",pageSize:10,retries:0,cacheTtlMs:0,userIp:"203.0.113.4",userAgent:"Test agent",fetchImpl:async(url,options)=>{call={url,options};return response(200,{type:"JOBS",hits:1,pages:1,jobs:[rawJob()]});}});assert.match(call.url,/^https:\/\/search\.api\.careerjet\.net\/v4\/query\?/);assert.doesNotMatch(call.url,/server-secret/);assert.equal(call.options.method,"GET");assert.equal(call.options.headers.Authorization,`Basic ${btoa("server-secret:")}`);assert.match(call.url,/locale_code=en_GB/);assert.match(call.url,/user_ip=203\.0\.113\.4/);assert.equal(result.body.jobs.length,1);});

test("missing Careerjet credential fails before a network request",async()=>{let calls=0;await assert.rejects(()=>careerjet.requestPage({affiliateId:"",country:"gb",keywords:"nurse",fetchImpl:async()=>{calls+=1;return response(200,{})}}),/CAREERJET_AFFILIATE_ID is required/);assert.equal(calls,0);const result=await careerjet.testConnection({affiliateId:"",country:"gb"});assert.equal(result.authentication_succeeded,false);});

test("rate limiting retries with Retry-After and structured safe events",async()=>{const statuses=[429,200],waits=[],events=[];const result=await careerjet.requestPage({affiliateId:"secret",country:"ca",keywords:"staff nurse",retries:1,cacheTtlMs:0,wait:async(ms)=>waits.push(ms),logger:(event)=>events.push(event),fetchImpl:async()=>response(statuses.shift(),statuses.length?{}:{type:"JOBS",hits:0,pages:0,jobs:[]},{"retry-after":"1"})});assert.equal(result.requestsMade,2);assert.deepEqual(waits,[1000]);assert.equal(events[0].provider,"careerjet");assert.equal(events[0].status,429);assert.doesNotMatch(JSON.stringify(events),/secret/);});

test("malformed Careerjet responses are rejected",async()=>{await assert.rejects(()=>careerjet.requestPage({affiliateId:"secret",country:"au",keywords:"midwife",retries:0,cacheTtlMs:0,fetchImpl:async()=>response(200,{type:"JOBS",hits:"wrong",pages:1,jobs:{}})}),/malformed response/);});

test("only verified Careerjet country locales are configured",()=>{assert.deepEqual(Object.fromEntries(Object.values(careerjet.COUNTRIES).map((country)=>[country.code,country.locale])),{GB:"en_GB",US:"en_US",CA:"en_CA",AU:"en_AU",NZ:"en_NZ",IE:"en_IE",AE:"en_AE",SA:"en_SA"});assert.throws(()=>careerjet.countryFor("fr"),/Unsupported Careerjet country/);});

test("Careerjet jobs map into the shared schema",()=>{const mapped=careerjet.mapJob(rawJob(),"gb",new Date("2026-08-01T10:00:00Z"));assert.deepEqual(mapped.errors,[]);assert.equal(mapped.job.source_name,"careerjet");assert.equal(mapped.job.country_code,"GB");assert.equal(mapped.job.country_name,"United Kingdom");assert.equal(mapped.job.currency,"GBP");assert.equal(mapped.job.salary_period,"year");assert.equal(mapped.job.profession,"nurse");assert.equal(mapped.job.raw_source_metadata.remote_status,"remote");assert.equal(mapped.job.application_url,rawJob().url);});

test("pagination validates and deduplicates Careerjet results",async()=>{let calls=0;const result=await careerjet.fetchCountryJobs({affiliateId:"secret",country:"gb",keywordBatches:["registered nurse"],maxPages:2,pageSize:2,maxJobs:10,retries:0,cacheTtlMs:0,fetchImpl:async()=>{calls+=1;return calls===1?response(200,{type:"JOBS",hits:3,pages:2,jobs:[rawJob(),rawJob()]}):response(200,{type:"JOBS",hits:3,pages:2,jobs:[rawJob({title:"Staff Nurse",url:"https://jobviewtrack.com/v2/staff-nurse-456"})]});}});assert.equal(calls,2);assert.equal(result.records.length,2);assert.equal(result.duplicates,1);assert.equal(result.jobsReceived,3);});

test("the controlled sample is UK registered nurse with a maximum of ten jobs",()=>{const importer=read("api/global-jobs-import.js"),routes=read("vercel.json"),migration=read("supabase/migrations/20260801190000_careerjet_jobs_v286.sql");assert.match(importer,/sample\?\["registered nurse"\]:CAREERJET_SEARCH_BATCHES/);assert.match(importer,/pageSize:sample\?10:20,maxJobs:sample\?10:400/);assert.match(routes,/provider=careerjet&mode=sample-import&country=gb/);assert.match(migration,/maximum_jobs',10/);assert.match(migration,/'careerjet'[\s\S]+false,'approved'/);});

test("scheduler and manual endpoints require existing authentication",()=>{const importer=read("api/global-jobs-import.js"),routes=JSON.parse(read("vercel.json")),pkg=JSON.parse(read("package.json"));assert.ok(importer.indexOf("const caller = await authenticate(req)")<importer.indexOf('toLowerCase()==="careerjet"'));assert.match(importer,/careerjet-core\.cjs/);assert.match(importer,/name:"careerjet", run:\(\)=>syncCareerjetCountries/);assert.ok(routes.rewrites.some((route)=>route.source==="/api/careerjet-jobs-import"));assert.equal(routes.crons.filter((cron)=>cron.path==="/api/global-jobs-import").length,1);assert.match(pkg.scripts["build:careerjet"],/careerjet-core\.ts[\s\S]*careerjet-core\.cjs/);});

test("Careerjet deduplication and cautious expiry span all existing sources",()=>{const importer=read("api/global-jobs-import.js");assert.match(importer,/const existing=await rest\(`btv_jobs\?select=/);assert.match(importer,/urls\.get\(url\)\|\|identities\.get\(identity\)/);assert.match(importer,/sourceLinks\.push/);assert.match(importer,/source_missing_runs\|\|0\)\+1>=3/);assert.match(importer,/14\*86400000/);assert.doesNotMatch(importer,/source_name=eq\.careerjet[^\n]+method:"DELETE"/);});

test("destination UIs preserve cards, filtering, saving and Careerjet attribution",()=>{const uk=read("web/jobs-centre-v272.js"),global=read("web/global-jobs-v168.js"),usa=read("web/usa-jobs-v155.js");assert.match(uk,/\["NHS Jobs","REED","ADZUNA","jooble","careerjet"\]/);assert.match(uk,/eq\("country_code","GB"\)/);assert.match(uk,/Careerjet/);assert.match(global,/isCareerjet/);assert.match(global,/data-save-job/);assert.match(usa,/careerjet/);assert.match(usa,/Careerjet/);});

test("admin exposes Careerjet metrics and secure manual controls",()=>{const admin=read("web/admin-opportunity-centre-v138.js"),enhancer=read("web/admin-opportunity-imports-v142.js"),fallback=read("web/admin-careerjet-v286.js"),html=read("web/admin.html");for(const value of ["Last sync","next","API calls","imported","updated","duplicates","inactive","failures","Sync Careerjet Now"])assert.match(admin,new RegExp(value));assert.match(enhancer,/data-sync-careerjet/);assert.match(enhancer,/careerjet-jobs-connection-test/);assert.match(fallback,/data-admin-careerjet286/);assert.match(fallback,/CAREERJET API/);assert.match(html,/admin-careerjet-v286\.js\?v=286/);});

test("Careerjet credential is server-only",()=>{const files=["api/_lib/careerjet-core.ts","api/global-jobs-import.js",".env.example","supabase/migrations/20260801190000_careerjet_jobs_v286.sql"].map(read).join("\n");assert.match(files,/CAREERJET_AFFILIATE_ID/);for(const file of ["web/jobs-centre-v272.js","web/global-jobs-v168.js","web/usa-jobs-v155.js","web/admin-opportunity-centre-v138.js","web/admin-opportunity-imports-v142.js","web/admin-careerjet-v286.js"])assert.doesNotMatch(read(file),/CAREERJET_AFFILIATE_ID|server-secret/);assert.doesNotMatch(files,/NEXT_PUBLIC_CAREERJET/);});

test("Careerjet connection failures are surfaced instead of reported as successful zero-work runs",()=>{const importer=read("api/global-jobs-import.js"),admin=read("web/admin-careerjet-v286.js"),enhancer=read("web/admin-opportunity-imports-v142.js");assert.match(importer,/providerCredentialIssue\("careerjet"\)/);assert.match(importer,/test\.authentication_succeeded\?200:502/);assert.match(admin,/result\.authentication_succeeded===false/);assert.match(enhancer,/!response\.ok\|\|result\.authentication_succeeded===false/);});
