import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const migration=fs.readFileSync('supabase/migrations/202607180002_beyond_coins_exam_platform_v87.sql','utf8');
const start=fs.readFileSync('supabase/functions/start-mock/index.ts','utf8');
const attempt=fs.readFileSync('supabase/functions/exam-attempt/index.ts','utf8');
const webhook=fs.readFileSync('supabase/functions/paystack-webhook/index.ts','utf8');
const verify=fs.readFileSync('supabase/functions/coin-verify/index.ts','utf8');
const client=fs.readFileSync('web/coin-exam-service-v87.js','utf8');
const admin=fs.readFileSync('web/admin-v87.js','utf8');
const has=r=>assert.match(migration,r);
test('1 welcome award is exactly 150 BC and uniquely referenced',()=>{has(/balance=balance\+150/);has(/'welcome-bonus'/);has(/on conflict\(user_id,idempotency_key\) do nothing/)});
test('2 repeated bootstrap checks the immutable welcome entry',()=>has(/select id into v_tx.*idempotency_key='welcome-bonus'/s));
test('3 atomic exam debit calculates the new balance',()=>{has(/v_after:=v_before-v_product\.coin_cost/);has(/for update/)});
test('4 attempt stores its product and exact source',()=>has(/exam_product_id uuid.*question_source text/s));
test('5 thirty-question product is configured as 30',()=>has(/'cbt_short'.*25,30,30/s));
test('6 sixty-question product is configured as 60',()=>has(/'cbt_full'.*50,60,60/s));
test('7 active attempts are resumed before charging',()=>has(/exam_product_id=v_product\.id and status='active'.*resumed',true/s));
test('8 idempotency prevents a double-click duplicate attempt',()=>{has(/unique\(user_id,idempotency_key\)/);assert.match(client,/sessionStorage\.getItem\(storageKey\)/)});
test('9 wallet row locking protects simultaneous spend',()=>has(/from btv_wallets where user_id=v_user for update/));
test('10 insufficient balance happens before debit and attempt',()=>{has(/if v_wallet\.balance<v_product\.coin_cost then raise exception/);has(/INSUFFICIENT_COINS/)});
test('11 start runs as one PostgreSQL transaction',()=>{has(/create or replace function public\.btv_start_paid_exam/);has(/insert into btv_exam_attempts/);has(/update btv_wallets/)});
test('12 failed checkout records zero-credit failed status',()=>{const checkout=fs.readFileSync('supabase/functions/coin-checkout/index.ts','utf8');assert.match(checkout,/status:'failed'/);assert.match(checkout,/failure_reason/)});
test('13 verified payment validates status amount and currency',()=>{assert.match(verify,/status!=='success'/);assert.match(verify,/result\.data\.amount/);assert.match(verify,/result\.data\.currency/)});
test('14 replayed webhook cannot credit twice',()=>{assert.match(webhook,/x-paystack-signature/);has(/if v_purchase\.status='paid' then return v_wallet\.balance/);has(/payment_reference_uq/)});
test('15 clients cannot mutate wallet or ledger',()=>has(/revoke insert,update,delete on public\.btv_wallets,public\.btv_wallet_transactions/));
test('16 users can only select their own attempts',()=>has(/user_id=auth\.uid\(\) or btv_is_admin\(\)/));
test('17 pre-submission attempt payload strips answers and rationales',()=>{has(/v_q:=v_q-'correct_option'-'explanation'/);has(/v_q:=v_q-'correct_options'-'rationale'-'test_strategy'/);assert.match(attempt,/btv_get_exam_attempt/)});
test('18 inactive products cannot launch',()=>has(/if not v_product\.is_active then raise exception/));
test('19 incomplete banks fail before a wallet deduction',()=>{has(/QUESTION_BANK_INCOMPLETE/);has(/array_length\(v_ids,1\).*question_count/)});
test('20 admin refund is a separate idempotent credit ledger entry',()=>{has(/create or replace function public\.btv_admin_refund_exam/);has(/'exam_refund'/);has(/'exam-refund:'\|\|v_attempt\.id/)});
test('shared service exposes all required wallet exam and payment methods',()=>{for(const name of ['getWallet','getWalletTransactions','getExamProduct','getActiveAttempt','startPaidExam','resumeExam','submitExam','createPayment','verifyPayment','getPaymentStatus'])assert.match(client,new RegExp(name))});
test('admin manages products packages attempts and refunds',()=>{for(const x of ['Exam products','Coin packages','Attempts & refunds','btv_admin_refund_exam'])assert.match(admin,new RegExp(x))});
test('paid exam function is invoked through authenticated edge layer',()=>{assert.match(start,/btv_start_paid_exam/);assert.match(start,/Authorization/)});
