import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read=path=>fs.readFileSync(path,"utf8");
const dashboard=read("web/dashboard-premium-v73.js"),client=read("web/immigration-news-v228.js"),api=read("api/immigration-news.js"),migration=read("supabase/migrations/20260730190000_immigration_news_centre.sql"),config=read("vercel.json");
test("homepage rotating information is replaced by a destination news tile",()=>{assert.match(dashboard,/data-immigration-news-tile/);assert.match(dashboard,/setupImmigrationNewsTile/);assert.match(dashboard,/IMMIGRATION NEWS/);assert.doesNotMatch(dashboard,/data-dashboard-carousel tabindex/);});
test("Immigration News menu opens a responsive country-filtered centre",()=>{assert.match(dashboard,/\["Immigration news", "immigration-news"\]/);assert.match(dashboard,/BTVImmigrationNews/);assert.match(dashboard,/"united arab emirates": "ae"/);assert.match(dashboard,/"saudi arabia": "sa"/);for(const code of ["uk","us","au","ca","nz","ie","ae","sa"])assert.match(client,new RegExp(`${code}:`));assert.match(client,/data-news-country/);});
test("daily backend imports, deduplicates and safely links original reporting",()=>{assert.match(api,/on_conflict=canonical_url/);assert.match(api,/CRON_SECRET/);assert.match(api,/canonical_url:url/);assert.match(config,/"path": "\/api\/immigration-news"/);assert.match(config,/"45 4 \* \* \*"/);});
test("Supabase news records are indexed and public reads are publication-only",()=>{for(const table of ["btv_immigration_news_sources","btv_immigration_news_items","btv_immigration_news_runs"])assert.match(migration,new RegExp(`create table if not exists public\\.${table}`));assert.match(migration,/using\(status='published'\)/);assert.match(migration,/unique/);assert.match(migration,/country_code,published_at desc/);});
