import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization'),secret=Deno.env.get('PAYSTACK_SECRET_KEY');if(!auth||!secret)throw Object.assign(Error('Verification is unavailable.'),{status:503});
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,userDb=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,service,{auth:{persistSession:false}}),{data:{user}}=await userDb.auth.getUser();if(!user)throw Object.assign(Error('Sign in is required.'),{status:401});
 const {reference}=await req.json(),{data:purchase}=await admin.from('btv_coin_purchases').select('*').eq('provider_reference',reference).eq('user_id',user.id).single();if(!purchase)throw Object.assign(Error('Purchase not found.'),{status:404});
 const response=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${secret}`}}),result=await response.json();if(!response.ok||result.data?.status!=='success'||Number(result.data.amount)!==Number(purchase.amount_minor)||result.data.currency!==purchase.currency)throw Object.assign(Error('Payment has not been verified.'),{status:409});
 const {data:balance,error}=await admin.rpc('btv_confirm_coin_purchase',{p_reference:reference,p_provider_payload:result.data});if(error)throw error;return reply({verified:true,balance});
}catch(e:any){return reply({error:e?.message||'Verification failed.'},e?.status||400)}});
