create table if not exists public.btv_ai_interactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,feature text not null default 'assistant',question_hash text not null,status text not null default 'started' check(status in('started','completed','provider_error','blocked')),model_alias text,latency_ms integer,created_at timestamptz not null default now(),completed_at timestamptz);
create index if not exists btv_ai_interactions_user_recent on public.btv_ai_interactions(user_id,created_at desc);
alter table public.btv_ai_interactions enable row level security;
drop policy if exists "own AI activity readable" on public.btv_ai_interactions;
create policy "own AI activity readable" on public.btv_ai_interactions for select using(auth.uid()=user_id);
create or replace function public.btv_begin_ai_request(p_feature text,p_question_hash text) returns uuid language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid();v_id uuid;begin if v_user is null then raise exception 'Sign in required';end if;if(select count(*) from btv_ai_interactions where user_id=v_user and created_at>now()-interval '1 minute')>=12 then raise exception 'Please wait a moment before asking another question';end if;insert into btv_ai_interactions(user_id,feature,question_hash)values(v_user,left(coalesce(p_feature,'assistant'),60),left(p_question_hash,128))returning id into v_id;return v_id;end $$;
create or replace function public.btv_finish_ai_request(p_id uuid,p_status text,p_model_alias text,p_latency_ms integer) returns void language plpgsql security definer set search_path=public as $$ begin update btv_ai_interactions set status=case when p_status in('completed','provider_error','blocked')then p_status else 'provider_error'end,model_alias=left(p_model_alias,80),latency_ms=greatest(0,p_latency_ms),completed_at=now() where id=p_id and user_id=auth.uid();end $$;
revoke all on function public.btv_begin_ai_request(text,text) from public;revoke all on function public.btv_finish_ai_request(uuid,text,text,integer) from public;
grant execute on function public.btv_begin_ai_request(text,text) to authenticated;grant execute on function public.btv_finish_ai_request(uuid,text,text,integer) to authenticated;
