const crypto=require("node:crypto");
const env=name=>process.env[name]||"";
const send=(res,status,body)=>res.status(status).setHeader("cache-control","public, s-maxage=21600, stale-while-revalidate=86400").setHeader("content-type","application/json; charset=utf-8").send(JSON.stringify(body));
const countries={uk:"United Kingdom",us:"United States",au:"Australia",ca:"Canada",nz:"New Zealand",ie:"Ireland",ae:"United Arab Emirates",sa:"Saudi Arabia"};
const feeds={
 uk:["https://www.gov.uk/search/news-and-communications.atom?organisations%5B%5D=uk-visas-and-immigration&order=updated-newest","https://news.google.com/rss/search?q=United%20Kingdom%20immigration%20visa%20work%20permit&hl=en-GB&gl=GB&ceid=GB:en"],
 us:["https://news.google.com/rss/search?q=United%20States%20immigration%20visa%20work%20permit&hl=en-US&gl=US&ceid=US:en"],
 au:["https://news.google.com/rss/search?q=Australia%20immigration%20visa%20work%20permit&hl=en-AU&gl=AU&ceid=AU:en"],
 ca:["https://api.io.canada.ca/io-server/gc/news/en/v2?dept=departmentofcitizenshipandimmigration&sort=publishedDate&orderBy=desc&pick=50&format=atom&atomtitle=Immigration%20Refugees%20and%20Citizenship%20Canada","https://news.google.com/rss/search?q=Canada%20immigration%20visa%20work%20permit&hl=en-CA&gl=CA&ceid=CA:en"],
 nz:["https://news.google.com/rss/search?q=New%20Zealand%20immigration%20visa%20work%20permit&hl=en-NZ&gl=NZ&ceid=NZ:en"],
 ie:["https://news.google.com/rss/search?q=Ireland%20immigration%20employment%20permit%20visa&hl=en-IE&gl=IE&ceid=IE:en"],
 ae:["https://news.google.com/rss/search?q=UAE%20immigration%20residence%20work%20visa&hl=en&gl=AE&ceid=AE:en"],
 sa:["https://news.google.com/rss/search?q=Saudi%20Arabia%20immigration%20residence%20work%20visa&hl=en&gl=SA&ceid=SA:en"]
};
const text=value=>String(value||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim();
const tag=(block,name)=>text(block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"i"))?.[1]);
const link=block=>text(block.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||block.match(/<link>([\s\S]*?)<\/link>/i)?.[1]);
function parse(xml,country){
 const blocks=[...(xml.match(/<item[\s\S]*?<\/item>/gi)||[]),...(xml.match(/<entry[\s\S]*?<\/entry>/gi)||[])];
 return blocks.map(block=>{let title=tag(block,"title"),publisher="";const split=title.match(/\s+-\s+([^-]+)$/);if(split){publisher=split[1].trim();title=title.slice(0,split.index).trim()}const url=link(block),published=tag(block,"pubDate")||tag(block,"published")||tag(block,"updated"),summary=tag(block,"description")||tag(block,"summary")||tag(block,"content");return{country_code:country,title:title.slice(0,400),summary:summary.slice(0,1200),publisher:publisher.slice(0,180),canonical_url:url,published_at:published&&Number.isFinite(Date.parse(published))?new Date(published).toISOString():null,fetched_at:new Date().toISOString(),status:"published",content_hash:crypto.createHash("sha256").update(`${title}|${url}`).digest("hex")}}).filter(x=>x.title&&/^https:\/\//.test(x.canonical_url));
}
function headers(prefer){const secret=env("SUPABASE_SECRET_KEY")||env("SUPABASE_SERVICE_ROLE_KEY"),h={apikey:secret,Authorization:`Bearer ${secret}`,"content-type":"application/json"};if(prefer)h.Prefer=prefer;return h}
async function rest(path,options={}){const base=env("SUPABASE_URL"),secret=env("SUPABASE_SECRET_KEY")||env("SUPABASE_SERVICE_ROLE_KEY");if(!base||!secret)throw Error("Database unavailable");const response=await fetch(`${base}/rest/v1/${path}`,{method:options.method||"GET",headers:headers(options.prefer),body:options.body?JSON.stringify(options.body):undefined}),body=await response.text();if(!response.ok)throw Error(body.slice(0,300));return body?JSON.parse(body):null}
async function live(country){const settled=await Promise.allSettled((feeds[country]||feeds.uk).map(async url=>{const response=await fetch(url,{headers:{"user-agent":"BeyondTheVisa-News/1.0"},signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error(`Feed ${response.status}`);return parse(await response.text(),country)}));const unique=new Map();settled.flatMap(x=>x.status==="fulfilled"?x.value:[]).forEach(item=>unique.set(item.canonical_url,item));return [...unique.values()].sort((a,b)=>Date.parse(b.published_at||0)-Date.parse(a.published_at||0)).slice(0,40)}
async function importAll(){const errors=[];let count=0;for(const country of Object.keys(countries)){try{const items=await live(country);count+=items.length;if(items.length)await rest("btv_immigration_news_items?on_conflict=canonical_url",{method:"POST",prefer:"resolution=merge-duplicates,return=minimal",body:items})}catch(error){errors.push({country,error:error.message})}}return{success:errors.length<Object.keys(countries).length,items_upserted:count,errors,completed_at:new Date().toISOString()}}
module.exports=async(req,res)=>{try{const secret=env("CRON_SECRET"),auth=String(req.headers.authorization||""),isCron=Boolean(secret)&&auth===`Bearer ${secret}`;if(isCron)return send(res,200,await importAll());if(req.method==="POST")return send(res,401,{error:"Unauthorised"});if(req.method!=="GET")return send(res,405,{error:"Method not allowed"});const country=countries[String(req.query.country||"").toLowerCase()]?String(req.query.country).toLowerCase():"uk",limit=Math.min(40,Math.max(1,Number(req.query.limit)||20));let items=[];try{items=await rest(`btv_immigration_news_items?select=id,country_code,title,summary,publisher,canonical_url,published_at,fetched_at,is_featured&country_code=eq.${country}&status=eq.published&order=is_featured.desc,published_at.desc&limit=${limit}`)}catch{}if(!items?.length)items=(await live(country)).slice(0,limit);return send(res,200,{country,country_name:countries[country],items,updated_at:new Date().toISOString(),source_notice:"Headlines link to their original publishers. Always verify immigration decisions with the responsible official authority."})}catch(error){console.error("Immigration news failed",error);return send(res,502,{error:"Immigration news is temporarily unavailable."})}};
