(()=>{'use strict';
if(window.__btvV86)return;window.__btvV86=true;
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],norm=v=>String(v||'').trim().toLowerCase();
const profile=()=>{try{return window.userProfile?.()||JSON.parse(localStorage.getItem('btv-profile')||'{}')}catch{return{}}};
function eligibility(){const p=profile();let d=norm(window.state?.country||p.destination||p.destinationCountry||p.countryDestination),r=norm(p.profession||p.role||p.pathway);d=({'united kingdom':'uk',england:'uk',scotland:'uk','northern ireland':'uk','united states':'us',usa:'us',australia:'au',canada:'ca'}[d]||d);return{cbt:d==='uk'&&(r.includes('nurse')||r.includes('midwi')),nclex:r.includes('nurse')&&['us','ca','au'].includes(d),ielts:['uk','au','ca','nz','ie'].includes(d)}}
function cleanLearn(){const e=eligibility();all('#learn .learnPanel').forEach(panel=>{if(!['cbtLesson','nclexLesson'].includes(panel.id))panel.querySelectorAll('[data-go="cbt"],[data-go="nclex"],[data-feature="cbt"],[data-feature="nclex"],.cbtTile,.nclexTile,.cbtBlock,.nclexBlock').forEach(x=>x.remove())});[['cbt',e.cbt],['nclex',e.nclex],['ielts',e.ielts]].forEach(([k,ok])=>{const t=$(`[data-learn-tab="${k}"]`),p=$(`#${k}Lesson`);[t,p].forEach(x=>{if(x){x.hidden=!ok;x.setAttribute('aria-hidden',String(!ok))}})});const a=$('.learnPanel.active[aria-hidden="true"]');if(a)$('[data-learn-tab="guide"]')?.click()}
function choice(exam,url){const p=$(`#${exam}Lesson`);if(!p)return;let box=p.querySelector('.mockAccess85');if(box)box.remove();box=document.createElement('section');box.className='mockAccess85';box.innerHTML=`<div class="freePractice86"><i>10</i><div><b>Daily free practice</b><small>Answer up to 10 ${exam.toUpperCase()} questions every day. No Beyond Coins required.</small></div></div><header><span>TIMED MOCK EXAMINATIONS</span><h3>Choose your ${exam.toUpperCase()} mock</h3><p>Your selection opens the exact timed exam and charges the displayed amount once through the secure wallet.</p></header><div><button type="button" data-v86-tier="short"><b>Focused mock</b><small>30 questions · 30 minutes · 25 BC</small></button><button type="button" data-v86-tier="full"><b>Full mock</b><small>60 questions · 60 minutes · 50 BC</small></button></div>`;p.prepend(box);box.querySelectorAll('[data-v86-tier]').forEach(b=>b.onclick=()=>location.href=`${url}?tier=${b.dataset.v86Tier}&mode=mock&v=86`)}
function ielts(){const p=$('#ieltsLesson');if(!p)return;let box=p.querySelector('.mockAccess85');if(box)box.remove();box=document.createElement('section');box.className='mockAccess85';box.innerHTML='<div class="freePractice86"><i>10</i><div><b>Daily free IELTS Academic practice</b><small>Complete up to 10 Reading or Writing questions each day without using coins.</small></div></div><header><span>IELTS ACADEMIC TIMED ACCESS</span><h3>Reading and Writing mock sessions</h3><p>Select the session you want. Listening and Speaking remain marked as coming soon while their assessment experience is completed.</p></header><div><button type="button" data-v86-ielts="short"><b>Focused Academic mock</b><small>30 questions · 30 minutes · 25 BC</small></button><button type="button" data-v86-ielts="full"><b>Full Academic mock</b><small>60 questions · 60 minutes · 50 BC</small></button></div>';p.prepend(box);box.querySelectorAll('[data-v86-ielts]').forEach(b=>b.onclick=async()=>{const tier=b.dataset.v86Ielts,code=`ielts_${tier}`;await window.BTVCoins?.start?.(code,()=>{sessionStorage.setItem('btv-ielts-paid-session',JSON.stringify({tier,count:tier==='short'?30:60,startedAt:new Date().toISOString()}));p.querySelector('[data-ielts-section="reading"]')?.click()})})}
function cleanExplore(){all('#home .quick>button').forEach(b=>{const text=norm(b.textContent);if(text.includes('privacy')||text.includes('feedback')||text.includes('contact us'))b.remove()})}
function menu(){const p=$('.shortcutPanel83');if(!p)return;p.querySelectorAll('[data-shortcut83="admin"],.shortcutAdmin83,[data-vroute="admin"]').forEach(x=>x.remove());const g=p.querySelector('.supportMenu85');if(g)g.querySelectorAll('button').forEach(x=>x.classList.add('supportCard86'))}
async function legal(){const body=$('#policyBody');if(!body||body.querySelector('.legalAcceptance86'))return;let user=null;try{user=(await window.btvSupabase?.auth?.getUser())?.data?.user}catch{}const m=user?.user_metadata||{},stamp=m.combined_legal_accepted_at||m.terms_accepted_at||m.privacy_acknowledged_at||m.cookie_understood_at||user?.created_at;const card=document.createElement('div');card.className='legalAcceptance86';card.innerHTML=`<span>RECORDED AGREEMENT</span><b>${stamp?'Accepted '+new Date(stamp).toLocaleString('en-GB',{dateStyle:'long',timeStyle:'short'}):'Acceptance record unavailable'}</b><small>${stamp?'Terms, Privacy Policy and Cookie Policy were accepted together for this account.':'Older accounts may require fresh acceptance when the policies are next updated.'}</small>`;body.prepend(card)}
function install(){cleanLearn();choice('cbt','cbt.html');choice('nclex','nclex.html');ielts();cleanExplore();menu();if($('#legal')?.classList.contains('active'))legal()}
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install()})}).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-open="legal"],[data-policy]'))setTimeout(legal,80)});install();setTimeout(install,500);setTimeout(install,1600);
})();
