(()=>{'use strict';
const $=s=>document.querySelector(s),db=()=>window.btvSupabase,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={user:null,mode:'hub',question:null,seen:[],index:0,total:10,correct:0,answers:{},questions:[],attempt:null,payload:null,timer:null,remaining:0,calc:'',answered:false};
const sections=['#numLoading','#numHub','#numPractice','#numResult'];
function show(id){sections.forEach(s=>$(s).hidden=s!==id);scrollTo({top:0,behavior:'smooth'})}
function label(v){return String(v||'Calculation').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function errorText(e){const m=String(e?.message||e||'Something went wrong.');if(m.includes('DAILY_FREE_LIMIT_REACHED'))return 'You have completed today’s 10 free questions. Choose a timed simulation or return tomorrow.';return m.replaceAll('_',' ')}
async function rpc(name,args={}){const {data,error}=await db().rpc(name,args);if(error)throw error;return data}
async function init(){try{const session=(await db().auth.getSession()).data.session;if(!session){location.assign('index.html');return}state.user=session.user;try{const wallet=await window.BTVExam.getWallet();$('#coinBalance').innerHTML=`<span>◆</span> ${Number(wallet.balance).toLocaleString()} BC`}catch{}const catalog=await rpc('btv_numeracy_catalog');$('#bankCount').textContent=Number(catalog.total||3000).toLocaleString();bind();const attempt=new URLSearchParams(location.search).get('attempt');if(attempt)await loadAttempt(attempt);else show('#numHub')}catch(e){$('#numLoading').innerHTML=`<h1>Numeracy Studio unavailable</h1><p>${esc(errorText(e))}</p><a class="numSecondary" href="index.html?screen=learn">Back to Learn</a>`}}
function bind(){document.querySelectorAll('[data-start-free]').forEach(b=>b.onclick=startFree);document.querySelectorAll('[data-start-paid]').forEach(b=>b.onclick=()=>window.BTVCoins.start(b.dataset.startPaid,a=>location.assign(`numeracy.html?attempt=${encodeURIComponent(a.attempt_id)}`)));document.querySelectorAll('[data-exit],[data-return-hub]').forEach(b=>b.onclick=()=>{clearInterval(state.timer);history.replaceState({},'',location.pathname);state.mode='hub';show('#numHub')});$('#answerForm').onsubmit=submitAnswer;$('#nextQuestion').onclick=next;$('#previousQuestion').onclick=previous;$('#calcKeys').onclick=calcKey;$('[data-calc-clear]').onclick=()=>setCalc('')}
async function startFree(){state.mode='free';state.index=0;state.correct=0;state.seen=[];state.answers={};state.total=10;$('#sessionMode').textContent='DAILY PRACTICE';$('#sessionClock').textContent='Untimed';show('#numPractice');await nextFree()}
async function nextFree(){try{lock(true);state.question=await rpc('btv_numeracy_next_question',{p_category:null,p_exclude_ids:state.seen});state.seen.push(state.question.id);renderQuestion()}catch(e){finish(state.index?Math.round(state.correct/state.index*100):0,errorText(e))}finally{lock(false)}}
async function loadAttempt(id){try{state.mode='paid';state.payload=await window.BTVExam.resumeExam(id);state.attempt=state.payload.attempt;state.questions=state.payload.questions||[];state.total=state.questions.length;state.index=0;state.answers={};$('#sessionMode').textContent=state.payload.product?.title?.toUpperCase()||'TIMED SIMULATION';show('#numPractice');renderQuestion();startClock()}catch(e){throw e}}
function current(){return state.mode==='paid'?state.questions[state.index]:state.question}
function renderQuestion(){const q=current();if(!q)return;state.answered=state.mode==='paid'&&Object.hasOwn(state.answers,q.id);state.calc='';setCalc('');$('#questionNumber').textContent=`QUESTION ${state.index+1} OF ${state.total}`;$('#questionCategory').textContent=label(q.category).toUpperCase();$('#questionText').textContent=q.question_text||q.question;$('#answerUnit').textContent=q.answer_unit||'';$('#answerInput').value=state.answers[q.id]??'';$('#answerInput').disabled=false;$('#checkAnswer').disabled=false;$('#feedback').hidden=true;$('#nextQuestion').hidden=true;$('#previousQuestion').hidden=state.mode!=='paid'||state.index===0;$('#sideProgress').textContent=`${state.index+1} / ${state.total}`;$('#progressBar').style.width=`${Math.round(state.index/state.total*100)}%`;$('#sideMessage').textContent='Answer carefully. Your response will stay on screen until you choose Next.';drawVisual(q);$('#answerInput').focus()}
function drawVisual(q){const host=$('#visualHost'),canvas=$('#clinicalVisual'),type=q.visual_type||'none';host.hidden=type==='none';if(type==='none')return;canvas.setAttribute('aria-label',`${label(type)} measurement diagram for this question`);const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,d=q.visual_data||{};c.clearRect(0,0,w,h);c.fillStyle='#f2f7f3';c.fillRect(0,0,w,h);c.strokeStyle='#173f42';c.fillStyle='#173f42';c.lineWidth=3;c.font='700 18px Inter, sans-serif';
 if(type==='syringe'){c.fillText(`Syringe capacity ${d.capacity_ml||5} mL`,30,34);c.strokeRect(90,78,420,70);c.fillStyle='#b6dfd2';c.fillRect(93,81,210,64);c.strokeStyle='#517679';for(let i=0;i<=20;i++){const x=90+i*21;c.beginPath();c.moveTo(x,148);c.lineTo(x,148-(i%5===0?28:14));c.stroke()}c.strokeStyle='#173f42';c.beginPath();c.moveTo(510,113);c.lineTo(610,113);c.stroke();c.strokeRect(35,92,55,42)}
 else if(type==='medicine_cup'){c.fillText('Graduated medicine cup',30,34);c.beginPath();c.moveTo(230,55);c.lineTo(200,175);c.lineTo(440,175);c.lineTo(410,55);c.closePath();c.stroke();c.fillStyle='#b6dfd2';c.fillRect(216,120,208,52);c.strokeStyle='#54777a';for(let i=0;i<6;i++){const y=65+i*20;c.beginPath();c.moveTo(400,y);c.lineTo(430,y);c.stroke();c.fillStyle='#173f42';c.fillText(`${Math.max(0,Number(d.capacity_ml||10)-i*2)}`,445,y+6)}}
 else if(type==='iv_bag'){c.fillText('IV infusion label',30,34);c.roundRect(190,50,260,130,20);c.stroke();c.fillStyle='#d5ebe2';c.fill();c.fillStyle='#173f42';c.textAlign='center';c.font='800 32px Georgia, serif';c.fillText(`${d.bag_ml||500} mL`,320,112);c.font='700 17px Inter, sans-serif';c.fillText(`Prescribed over ${d.hours||4} hours`,320,146);c.textAlign='left'}
 else if(type==='fluid_chart'){c.fillText('Fluid balance chart',30,34);c.font='700 16px Inter, sans-serif';c.fillText('INTAKE',90,72);c.fillText('OUTPUT',390,72);const intake=d.intake||[],output=d.output||[];c.font='600 25px ui-monospace, monospace';c.fillText(`${intake[0]||0} mL`,85,116);c.fillText(`+ ${intake[1]||0} mL`,85,153);c.fillText(`${output[0]||0} mL`,385,116);c.fillText(`+ ${output[1]||0} mL`,385,153)} }
async function submitAnswer(e){e.preventDefault();const input=Number($('#answerInput').value);if(!Number.isFinite(input))return;const q=current();if(state.mode==='free'){try{lock(true);const result=await rpc('btv_submit_numeracy_answer',{p_question_id:q.id,p_answer:input});state.index++;if(result.correct)state.correct++;state.answered=true;$('#answerInput').disabled=true;$('#checkAnswer').disabled=true;const box=$('#feedback');box.className=`numFeedback ${result.correct?'correct':'incorrect'}`;box.innerHTML=`<strong>${result.correct?'Correct — well calculated.':'Not quite. The answer is '+esc(result.answer)+' '+esc(result.unit||'')+'.'}</strong><span>${esc(result.rationale)}</span>`;box.hidden=false;$('#nextQuestion').hidden=false;$('#nextQuestion').textContent=state.index>=state.total||Number(result.remaining_today)<=0?'View session result →':'Next question →';$('#sideMessage').textContent=`${result.remaining_today} free question${Number(result.remaining_today)===1?'':'s'} remaining today.`}catch(err){alert(errorText(err))}finally{lock(false)}}else{state.answers[q.id]=input;state.answered=true;$('#feedback').className='numFeedback correct';$('#feedback').innerHTML='<strong>Answer saved.</strong><span>Review it now, then choose Next when you are ready. Correct answers are revealed after submission.</span>';$('#feedback').hidden=false;$('#nextQuestion').hidden=false;$('#nextQuestion').textContent=state.index===state.total-1?'Submit simulation →':'Next question →';$('#sideMessage').textContent='Answer saved. It will not move until you choose Next.'}}
async function next(){if(state.mode==='free'){if(state.index>=state.total)return finish(Math.round(state.correct/state.total*100));await nextFree();return}if(state.index>=state.total-1)return submitMock();state.index++;renderQuestion()}
function previous(){if(state.mode==='paid'&&state.index>0){state.index--;renderQuestion()}}
async function submitMock(force=false){if(!force&&!confirm('Submit this simulation now? Unanswered questions will be marked incorrect.'))return;try{lock(true);clearInterval(state.timer);const result=await window.BTVExam.submitExam(state.attempt.id,state.answers);const score=Number(result.score??result.attempt?.score??0);finish(score,`${result.correct_count??Math.round(score*state.total/100)} of ${state.total} calculations correct. Your secure Beyond Coins transaction and result are recorded.`)}catch(e){alert(errorText(e));startClock()}finally{lock(false)}}
function startClock(){clearInterval(state.timer);const expires=new Date(state.attempt.expires_at).getTime();const tick=()=>{state.remaining=Math.max(0,Math.floor((expires-Date.now())/1000));$('#sessionClock').textContent=`${String(Math.floor(state.remaining/60)).padStart(2,'0')}:${String(state.remaining%60).padStart(2,'0')}`;if(state.remaining<=0){clearInterval(state.timer);submitMock(true)}};tick();state.timer=setInterval(tick,1000)}
function finish(score,message){clearInterval(state.timer);$('#resultScore').textContent=`${score}%`;$('#resultTitle').textContent=score>=80?'Excellent calculation control':score>=60?'A solid session completed':'Keep building calculation confidence';$('#resultCopy').textContent=message||`${state.correct} of ${state.total} calculations correct. Review the worked methods and return for a fresh random set.`;$('#progressBar').style.width='100%';show('#numResult')}
function calcKey(e){const b=e.target.closest('button');if(!b)return;const v=b.textContent.trim();if(v==='=')return calculate();const mapped={'÷':'/','×':'*','−':'-'}[v]||v;if(state.calc.length<32)setCalc(state.calc+mapped)}
function calculate(){if(!state.calc)return;try{if(!/^[0-9+\-*/().\s]+$/.test(state.calc))throw Error();const value=Function(`"use strict";return (${state.calc})`)();if(!Number.isFinite(value))throw Error();setCalc(String(Math.round(value*1000000)/1000000))}catch{setCalc('Error')}}
function setCalc(v){state.calc=v;$('#calcDisplay').textContent=v||'0'}function lock(on){$('#checkAnswer').disabled=on;$('#nextQuestion').disabled=on}
init();
})();
