(function () {
  'use strict';

  const CBT_CATEGORIES = [
    'Infection Prevention', 'Medicines Management', 'Professional Values',
    'Prioritisation', 'Documentation', 'Mental Health', 'Child Nursing', 'Adult Nursing',
    'Anatomy and Physiology'
  ];
  const NCLEX_CATEGORIES = [
    'Management of Care', 'Safety and Infection Prevention and Control',
    'Health Promotion and Maintenance', 'Psychosocial Integrity', 'Basic Care and Comfort',
    'Pharmacological and Parenteral Therapies', 'Reduction of Risk Potential', 'Physiological Adaptation'
  ];
  const IELTS_CATEGORIES = ['reading', 'listening', 'writing', 'speaking'];
  const cbtDomain={
    'Infection Prevention':'Professional values','Medicines Management':'Nursing practice and decision making',
    'Professional Values':'Professional values','Prioritisation':'Leadership, management and team working',
    'Documentation':'Communication and interpersonal skills','Mental Health':'Nursing practice and decision making',
    'Child Nursing':'Nursing practice and decision making','Adult Nursing':'Nursing practice and decision making'
  };
  const nclexNeed={
    'Safety and Infection Control':'Safety and Infection Prevention and Control','Pharmacological Therapies':'Pharmacological and Parenteral Therapies',
    'Fundamentals of Care':'Basic Care and Comfort','Psychosocial Integrity':'Psychosocial Integrity',
    'Maternal-Newborn Nursing':'Health Promotion and Maintenance','Paediatric Nursing':'Health Promotion and Maintenance',
    'Medical-Surgical Nursing':'Physiological Adaptation','Management of Care':'Management of Care','Prioritisation':'Reduction of Risk Potential'
  };
  const pad = n => String(n).padStart(4, '0');

  const cbtSeeds = [
    ['Infection Prevention', 'A patient develops diarrhoea that may be infectious. What should the nurse do first?', ['Wait for laboratory confirmation before taking precautions', 'Apply appropriate isolation precautions and perform a risk assessment', 'Move the patient without informing the receiving area', 'Give an antidiarrhoeal medicine without assessment'], 'B', 'Use standard precautions plus transmission-based precautions when infection is suspected; do not wait for confirmation before reducing risk.'],
    ['Infection Prevention', 'After removing gloves following personal care, what action is required?', ['Hand hygiene', 'Put on a second pair of gloves', 'Document the glove brand', 'Clean hands only if visibly soiled'], 'A', 'Gloves do not replace hand hygiene. Perform hand hygiene after glove removal.'],
    ['Medicines Management', 'A prescription is unclear and the dose appears unusual. What is the safest action?', ['Administer it because it is signed', 'Ask another patient what dose they receive', 'Withhold the dose and clarify the prescription with an authorised prescriber', 'Change the dose to the usual amount'], 'C', 'Do not administer from an unclear or potentially unsafe prescription. Clarify and document the action taken.'],
    ['Medicines Management', 'Which check is essential immediately before administering a medicine?', ['The patient identity against the prescription and allergy status', 'Whether the medicine trolley is full', 'The patient room number only', 'Whether another nurse knows the medicine name'], 'A', 'Correct identification, prescription checks and allergy status are core medicines-safety controls.'],
    ['Professional Values', 'A patient asks the nurse not to share information with a relative. What should the nurse do?', ['Tell the relative everything', 'Respect confidentiality unless a lawful or safety-based exception applies', 'Avoid documenting the request', 'Ask another patient to decide'], 'B', 'Respect confidentiality and consent, escalating only where there is a lawful justification or serious safety concern.'],
    ['Professional Values', 'A nurse realises they made a mistake that caused potential harm. What is required?', ['Hide the error if no complaint was made', 'Be open, report it promptly and follow duty-of-candour procedures', 'Alter the record', 'Wait until the next appraisal'], 'B', 'Act openly and honestly, protect the patient, escalate, document accurately and follow local incident procedures.'],
    ['Prioritisation', 'Which patient should be assessed first?', ['A stable patient asking about discharge transport', 'A patient with sudden breathing difficulty', 'A patient requesting a routine dressing change', 'A patient waiting for a menu'], 'B', 'Use an ABCDE approach. An acute breathing problem takes priority over stable or routine needs.'],
    ['Prioritisation', 'During handover, which finding needs the most urgent escalation?', ['A new oxygen saturation of 84%', 'A request for a blanket', 'A routine medicine due in four hours', 'A family member asking visiting times'], 'A', 'Severe new hypoxaemia is an immediate threat and requires urgent assessment and escalation.'],
    ['Documentation', 'Which entry best meets professional record-keeping standards?', ['Patient okay', '14:10: pain 7/10 in lower abdomen; observations recorded; prescriber informed', 'Write the entry later from memory', 'Use an erasable pencil'], 'B', 'Records should be timely, factual, specific, attributable and include actions and escalation.'],
    ['Documentation', 'A nurse notices an error in a paper record. What should they do?', ['Erase it completely', 'Use correction fluid', 'Correct it according to policy while keeping the original entry legible', 'Remove the page'], 'C', 'Corrections must preserve an audit trail and follow the organisation’s documentation policy.'],
    ['Mental Health', 'A patient says they intend to harm themselves tonight. What is the first priority?', ['Promise to keep it secret', 'Complete an immediate safety assessment and escalate for urgent support', 'Tell them to discuss it next week', 'Leave them alone to calm down'], 'B', 'Take statements of self-harm seriously, maintain safety, assess immediate risk and escalate according to local policy.'],
    ['Mental Health', 'Which response is most therapeutic when a distressed patient describes hearing voices?', ['The voices are not real, so ignore them', 'That sounds frightening. Can you tell me what the voices are saying?', 'You should stop talking about this', 'I hear them too'], 'B', 'Acknowledge distress without reinforcing the experience, assess content and risk, and seek appropriate support.'],
    ['Child Nursing', 'A child’s condition is worsening and the parent says the child is “not themselves.” What should the nurse do?', ['Ignore the parent because observations are normal', 'Include parental concern in an urgent reassessment and escalation', 'Ask the parent to leave', 'Wait until the next routine round'], 'B', 'Parents often recognise subtle deterioration. Combine their concern with structured assessment and escalate when indicated.'],
    ['Child Nursing', 'Before a procedure, how should a nurse involve a school-age child?', ['Speak only to the parent', 'Give an age-appropriate explanation and seek the child’s assent alongside valid consent', 'Avoid answering questions', 'Use technical language only'], 'B', 'Children should receive developmentally appropriate information and be involved in decisions while valid consent requirements are followed.'],
    ['Adult Nursing', 'An adult patient becomes acutely confused. What is the best initial approach?', ['Assume dementia', 'Assess for delirium and reversible causes using a structured assessment', 'Apply restraint immediately', 'Wait several days'], 'B', 'Acute confusion may indicate delirium. Assess promptly for physiological causes, medicines, pain, infection and other triggers.'],
    ['Adult Nursing', 'A patient reports central chest pain with sweating. What should the nurse do first?', ['Arrange a routine appointment', 'Begin an immediate ABCDE assessment and summon urgent help', 'Offer food', 'Ask the patient to walk'], 'B', 'Possible acute coronary syndrome requires immediate assessment, monitoring and urgent escalation.'],
    ['Infection Prevention', 'A nurse is about to insert a urinary catheter. Which action best reduces infection risk?', ['Skip hand hygiene if sterile gloves are used', 'Use aseptic technique and sterile equipment', 'Use tap water to clean the catheter tip', 'Disconnect the drainage system each shift'], 'B', 'Catheter-associated infection risk is reduced by aseptic insertion and a closed sterile system.'],
    ['Infection Prevention', 'Which item should be cleaned between patients according to local decontamination policy?', ['Single-use tissue', 'Shared blood pressure cuff', 'Patient discharge summary', 'Disposable apron'], 'B', 'Reusable patient equipment must be cleaned and decontaminated between patients.'],
    ['Infection Prevention', 'A patient with a productive cough is awaiting transfer. What should the nurse do before transport?', ['Send the patient immediately with no precautions', 'Apply source-control measures and inform the receiving team', 'Delay transport for 48 hours', 'Give antibiotics without prescription'], 'B', 'Source control and handover communication reduce transmission during movement.'],
    ['Infection Prevention', 'Which action is correct when disposing of a used sharps needle?', ['Recap the needle with two hands', 'Dispose of it immediately at point of use in an approved sharps container', 'Leave it on a tray for collection', 'Break the needle before disposal'], 'B', 'Sharps should be disposed of immediately without recapping to prevent needlestick injury.'],
    ['Infection Prevention', 'During an outbreak, what is the most appropriate first step when a patient develops fever and rash?', ['Move the patient to a shared bay', 'Isolate, assess and escalate according to outbreak policy', 'Wait for evening round', 'Offer only oral fluids'], 'B', 'Suspected contagious illness requires immediate isolation and escalation.'],
    ['Infection Prevention', 'What is the best sequence for donning personal protective equipment for contact precautions?', ['Gloves then gown', 'Gown then gloves', 'Mask then gloves only', 'Apron then remove immediately'], 'B', 'For contact precautions, gown is applied before gloves to protect clothing and skin.'],
    ['Medicines Management', 'A patient refuses a prescribed medicine. What is the safest professional action?', ['Hide medicine in food', 'Explore concerns, provide information and document refusal', 'Force administration', 'Discard the dose without record'], 'B', 'Informed refusal should be respected, documented and escalated if clinically significant.'],
    ['Medicines Management', 'A nurse prepares insulin for one patient and is interrupted. What should happen next?', ['Administer it quickly to avoid delay', 'Re-check patient, insulin type, dose and timing before administration', 'Ask a visitor to confirm', 'Leave insulin at bedside'], 'B', 'High-alert medicines require full re-check after interruption before administration.'],
    ['Medicines Management', 'Which prescription abbreviation should be clarified before administration?', ['PO', 'OD', 'mg', 'mL'], 'B', 'Ambiguous abbreviations can cause errors and should be clarified before giving medicine.'],
    ['Medicines Management', 'A patient has renal impairment. Why should medicine doses be reviewed?', ['Renal impairment has no effect on medicines', 'Some medicines accumulate and may require dose adjustment', 'Only IV medicines are affected', 'All doses should be doubled'], 'B', 'Reduced renal clearance can increase toxicity risk unless dose/frequency is adjusted.'],
    ['Medicines Management', 'Which action supports safe IV medicine administration?', ['Infuse without checking compatibility', 'Verify route, dilution, rate and compatibility before infusion', 'Use any cannula size for all drugs', 'Skip monitoring during infusion'], 'B', 'IV safety requires route, dilution, compatibility and rate checks with monitoring.'],
    ['Medicines Management', 'What should the nurse do when an anaphylaxis reaction occurs after medicine administration?', ['Continue medicine slowly', 'Stop administration, call emergency help and follow anaphylaxis protocol', 'Document later and observe', 'Offer oral water only'], 'B', 'Suspected anaphylaxis is an emergency requiring immediate cessation and escalation.'],
    ['Professional Values', 'A colleague documents care they did not provide. What should the nurse do?', ['Ignore it to maintain team harmony', 'Escalate concern through appropriate professional channels', 'Edit records silently', 'Discuss only with patients'], 'B', 'Falsification of records is a serious professional and safety issue requiring escalation.'],
    ['Professional Values', 'A patient lacks capacity for a decision today. What principle should guide care?', ['Family preference always overrides all factors', 'Act in the patient’s best interests using legal and policy frameworks', 'Delay urgent care indefinitely', 'Proceed without assessment'], 'B', 'When capacity is lacking, decisions must follow best-interest and legal processes.'],
    ['Professional Values', 'Which action best demonstrates person-centred care?', ['Using one plan for every patient', 'Respecting preferences, values and informed choices in care planning', 'Avoiding shared decision-making', 'Prioritising ward routine over patient needs'], 'B', 'Person-centred care integrates patient values and preferences into decisions.'],
    ['Professional Values', 'A nurse is asked to perform a skill they are not competent in. What is the correct response?', ['Proceed to avoid delay', 'Decline, explain limits and seek competent support', 'Ask a student to do it', 'Document competence after performing'], 'B', 'Professional codes require nurses to practise within competence and seek support.'],
    ['Professional Values', 'How should a nurse respond to discriminatory language from a visitor?', ['Ignore it', 'Challenge it respectfully and escalate according to policy', 'Agree to avoid conflict', 'Move the patient without explanation'], 'B', 'Discriminatory behaviour should be addressed and escalated to protect dignity and safety.'],
    ['Professional Values', 'Which approach best protects confidentiality during handover?', ['Discuss loudly in public corridor', 'Share relevant information in an appropriate private setting', 'Text details to non-clinical contacts', 'Leave records open at reception'], 'B', 'Confidential information should be shared on a need-to-know basis in suitable environments.'],
    ['Prioritisation', 'Which newly observed sign requires first response from the nurse?', ['Mild hunger before lunch', 'Airway noise with reduced oxygen saturation', 'Request for visitor pass', 'Need for routine mouth care'], 'B', 'Airway compromise is an immediate life threat and takes priority.'],
    ['Prioritisation', 'The nurse has four tasks. Which should be completed first?', ['Reorder stock cupboards', 'Assess a patient with new confusion and hypotension', 'Complete annual e-learning', 'Answer a non-urgent phone message'], 'B', 'Acute deterioration signs require urgent assessment before administrative tasks.'],
    ['Prioritisation', 'During medication round, a patient activates emergency call bell saying severe chest pain. What should happen first?', ['Finish current paperwork', 'Stop and assess immediately while calling for urgent assistance', 'Ask patient to wait 20 minutes', 'Refer to outpatient clinic'], 'B', 'Possible cardiac emergency must be addressed immediately.'],
    ['Prioritisation', 'Which patient can be seen last?', ['Patient with stridor', 'Patient with acute unilateral weakness', 'Patient requesting replacement slippers', 'Patient with active bleeding'], 'C', 'Non-clinical comfort requests can wait behind unstable clinical presentations.'],
    ['Prioritisation', 'A postoperative patient has sudden drop in blood pressure and tachycardia. What is the best first action?', ['Offer oral fluids only', 'Begin urgent assessment and escalate possible shock', 'Document and recheck in four hours', 'Prepare discharge papers'], 'B', 'Possible shock requires immediate assessment and escalation.'],
    ['Prioritisation', 'Which handover item is highest priority?', ['Pending TV repair', 'New seizure lasting over 5 minutes', 'Menu preference for dinner', 'Request for extra pillow'], 'B', 'Prolonged seizure is time-critical and requires urgent intervention.'],
    ['Documentation', 'What is the best way to record a medication administration delay?', ['Do not record to avoid blame', 'Record factual reason, time and actions taken', 'Record only if patient complains', 'Change administration time to match schedule'], 'B', 'Accurate, contemporaneous and factual entries maintain safety and accountability.'],
    ['Documentation', 'Which statement about electronic records is correct?', ['Share logins to save time', 'Use individual secure login and sign entries correctly', 'Leave screen unlocked when leaving', 'Copy-forward assessments without review'], 'B', 'Secure individual access and accurate authentication are required for legal records.'],
    ['Documentation', 'When documenting wound care, which detail is essential?', ['Only that dressing was changed', 'Site assessment, wound appearance, intervention and patient response', 'Nurse mood during procedure', 'Colour of gloves used'], 'B', 'Clinical usefulness requires objective findings, actions and outcomes.'],
    ['Documentation', 'How should late entries be handled?', ['Inserted without timing', 'Clearly marked as late entry with actual event time and entry time', 'Backdated to original time without note', 'Written in another patient chart'], 'B', 'Late entries must preserve chronology and transparency.'],
    ['Documentation', 'A patient requests access to their records. What should the nurse do?', ['Refuse immediately', 'Follow local information-governance process for access requests', 'Delete sensitive notes', 'Give another patient file by mistake'], 'B', 'Requests should be handled through formal legal and governance pathways.'],
    ['Documentation', 'What is the best response if a colleague asks you to document care they provided?', ['Document it as yours', 'Do not sign for care you did not provide; advise them to record their own entry', 'Record without time', 'Use initials only'], 'B', 'Entries must be attributable to the person who delivered or directly observed care.'],
    ['Mental Health', 'A patient with severe anxiety is hyperventilating. What should the nurse do first?', ['Dismiss concerns', 'Use calm communication, assess risk and guide controlled breathing', 'Leave the patient alone in a locked room', 'Administer sedatives without prescription'], 'B', 'Immediate supportive de-escalation and assessment reduce distress and identify risk.'],
    ['Mental Health', 'A patient with psychosis appears increasingly agitated. Which approach is best?', ['Confront loudly in crowded area', 'Reduce stimulation, use de-escalation and request support early', 'Argue about delusions', 'Ignore escalating behaviour'], 'B', 'Early de-escalation in a safe environment can prevent harm.'],
    ['Mental Health', 'Which statement best reflects trauma-informed care?', ['Force disclosure of trauma details', 'Promote safety, choice, collaboration and empowerment', 'Use threats to ensure compliance', 'Avoid asking about preferences'], 'B', 'Trauma-informed care emphasises safety, trust and patient control where possible.'],
    ['Mental Health', 'A patient reports new command hallucinations to self-harm. What is the priority?', ['Routine follow-up tomorrow', 'Immediate risk assessment and urgent escalation', 'Advise journaling only', 'Send home unaccompanied'], 'B', 'Command hallucinations with self-harm content require urgent safety intervention.'],
    ['Mental Health', 'Which action supports therapeutic boundaries?', ['Sharing personal contact details', 'Maintaining professional limits while being compassionate', 'Meeting socially after discharge', 'Accepting expensive gifts'], 'B', 'Clear professional boundaries protect patients and staff.'],
    ['Mental Health', 'A patient says they feel hopeless but deny plan or intent. What should the nurse do?', ['No further assessment needed', 'Complete structured suicide-risk assessment and safety planning', 'Document only mood score', 'Discharge immediately'], 'B', 'Any hopelessness statements require fuller risk assessment and safety planning.'],
    ['Child Nursing', 'A febrile child develops non-blanching rash. What is the nurse’s first action?', ['Offer juice and observe', 'Urgent escalation for possible serious infection', 'Book routine clinic review', 'Delay review until parent returns'], 'B', 'Non-blanching rash with fever can indicate life-threatening illness and needs urgent review.'],
    ['Child Nursing', 'Before giving oral medicine to a child, what is essential?', ['Estimate dose by appearance', 'Calculate dose using verified weight and prescription', 'Use adult dose then halve it', 'Ask sibling to confirm'], 'B', 'Paediatric dosing must be weight-based and verified to reduce harm.'],
    ['Child Nursing', 'Which strategy helps reduce procedural anxiety in a child?', ['No explanation beforehand', 'Use age-appropriate preparation and parental involvement where suitable', 'Perform procedure during sleep without consent', 'Ignore child questions'], 'B', 'Preparation and communication reduce fear and improve cooperation.'],
    ['Child Nursing', 'A toddler has increased work of breathing and intercostal recession. What should the nurse do?', ['Give toys and reassess in 2 hours', 'Immediate respiratory assessment and escalation', 'Offer large meal', 'Discharge with leaflet'], 'B', 'Respiratory distress signs require urgent assessment and support.'],
    ['Child Nursing', 'What is best practice for safeguarding concerns?', ['Wait for certainty before action', 'Document concerns objectively and escalate according to safeguarding policy', 'Discuss publicly in waiting area', 'Delete previous notes'], 'B', 'Safeguarding relies on timely documentation and appropriate escalation.'],
    ['Child Nursing', 'Which approach supports accurate pain assessment in children?', ['Use adult scale for all ages', 'Use developmentally appropriate validated pain tools', 'Assume children exaggerate pain', 'Assess pain only once daily'], 'B', 'Validated age-appropriate tools improve paediatric pain assessment.'],
    ['Adult Nursing', 'An older adult has reduced oral intake and dry mucosa. What should the nurse prioritise?', ['No action unless family complains', 'Hydration assessment, fluid balance monitoring and escalation if needed', 'Restrict fluids automatically', 'Delay review until discharge'], 'B', 'Early hydration assessment prevents deterioration and supports safe care.'],
    ['Adult Nursing', 'A bedbound patient is at high falls risk during transfers. What is best practice?', ['Transfer alone quickly', 'Use falls-prevention plan and appropriate assistance/equipment', 'Remove call bell access', 'Encourage unassisted walking'], 'B', 'Falls risk management requires planned support and safe transfer methods.'],
    ['Adult Nursing', 'A patient has sepsis warning signs. What should the nurse do first?', ['Schedule outpatient review', 'Escalate urgently and initiate local sepsis pathway', 'Wait for all culture results before acting', 'Encourage sleep only'], 'B', 'Sepsis requires time-critical recognition and escalation.'],
    ['Adult Nursing', 'Which intervention best prevents venous thromboembolism in high-risk inpatients?', ['Encourage prolonged bed rest', 'Apply prescribed prophylaxis and promote safe mobilisation', 'Stop all anticoagulants', 'Limit leg movement'], 'B', 'Risk-appropriate prophylaxis and mobilisation reduce VTE risk.'],
    ['Adult Nursing', 'What should the nurse do when pressure damage risk increases?', ['Document only', 'Implement and review an individual pressure prevention plan immediately', 'Use donut cushions continuously', 'Massage reddened areas'], 'B', 'Early preventive actions reduce risk of pressure injury progression.'],
    ['Adult Nursing', 'A patient with diabetes has a capillary glucose of 2.8 mmol/L and sweating. What is first action?', ['Delay until meal time', 'Treat hypoglycaemia immediately per protocol', 'Give insulin now', 'Discharge from ward'], 'B', 'Symptomatic hypoglycaemia is urgent and needs immediate treatment.'],
    ['Anatomy and Physiology', 'Which chamber of the heart pumps oxygenated blood to the systemic circulation?', ['Right atrium', 'Left ventricle', 'Right ventricle', 'Left atrium'], 'B', 'The left ventricle pumps oxygenated blood through the aorta to systemic circulation.'],
    ['Anatomy and Physiology', 'Gas exchange primarily occurs in which lung structure?', ['Bronchi', 'Alveoli', 'Pleura', 'Diaphragm'], 'B', 'Alveoli provide the surface area for oxygen and carbon dioxide exchange.'],
    ['Anatomy and Physiology', 'Which part of the nephron is mainly responsible for filtration?', ['Loop of Henle', 'Glomerulus', 'Collecting duct', 'Distal tubule'], 'B', 'The glomerulus filters plasma to form ultrafiltrate.'],
    ['Anatomy and Physiology', 'Which electrolyte is most associated with cardiac conduction abnormalities when markedly elevated?', ['Sodium', 'Potassium', 'Calcium', 'Chloride'], 'B', 'Hyperkalaemia can cause serious conduction disturbances and arrhythmias.'],
    ['Anatomy and Physiology', 'What is the normal role of insulin?', ['Raises blood glucose by glycogen breakdown', 'Facilitates glucose uptake into cells and lowers blood glucose', 'Stimulates cortisol release', 'Inhibits kidney filtration'], 'B', 'Insulin promotes cellular glucose uptake and reduces circulating glucose.'],
    ['Anatomy and Physiology', 'Which cranial nerve is primarily responsible for vagal parasympathetic output to thoracic organs?', ['Optic nerve', 'Vagus nerve', 'Trigeminal nerve', 'Hypoglossal nerve'], 'B', 'The vagus nerve carries major parasympathetic fibres to thoracic and abdominal organs.']
  ];

  const nclexSeeds = [
    ['Safety and Infection Control', 'Which action should the nurse take first for a client with suspected airborne infection?', ['Place the client in an appropriate airborne-infection isolation room', 'Keep the door open', 'Use standard precautions only', 'Transport the client through public areas'], ['A'], 'Institute appropriate airborne precautions promptly and follow facility policy.', 'Identify the transmission route and choose the precaution that immediately limits exposure.'],
    ['Safety and Infection Control', 'Which action breaks sterile technique?', ['Keeping sterile items above waist level', 'Reaching across the sterile field', 'Opening the far flap first', 'Treating the outer edge as contaminated'], ['B'], 'Reaching across a sterile field risks contaminating it.', 'Picture the sterile field and eliminate any action that crosses or obscures it.'],
    ['Pharmacological Therapies', 'Before giving a newly prescribed medication, which finding requires immediate clarification?', ['A documented severe allergy to the medication class', 'The client asks for water', 'The medication is in unit-dose packaging', 'The prescription uses the generic name'], ['A'], 'A severe allergy creates a potentially life-threatening risk and must be clarified before administration.', 'Look first for information that could make administration immediately unsafe.'],
    ['Pharmacological Therapies', 'Which client statement shows correct understanding of medication safety?', ['I will double the next dose if I forget one', 'I will check with a pharmacist before using a new over-the-counter product', 'I can share medicines with a relative', 'I can stop antibiotics when I feel better'], ['B'], 'Checking for interactions and contraindications before adding nonprescription products supports safe medication use.', 'Choose the statement that prevents interactions and avoids independent dose changes.'],
    ['Fundamentals of Care', 'Which intervention best reduces pressure-injury risk for an immobile client?', ['Reposition regularly and inspect the skin', 'Massage reddened bony prominences', 'Use a ring cushion continuously', 'Limit protein without assessment'], ['A'], 'Regular repositioning, skin assessment and an individual prevention plan reduce pressure injury risk.', 'Select prevention that relieves pressure and detects early tissue damage.'],
    ['Fundamentals of Care', 'Which action is safest when assisting a weak client to transfer?', ['Pull the client by both arms', 'Assess mobility and use the prescribed transfer aid', 'Ask the client to hold the nurse’s neck', 'Transfer without footwear'], ['B'], 'Assess first and use appropriate equipment and technique to protect the client and staff.', 'Choose the action based on assessment and safe handling principles.'],
    ['Psychosocial Integrity', 'A client says, “There is no reason to live.” What is the nurse’s priority response?', ['Change the subject', 'Ask directly about suicidal thoughts, plan and means', 'Promise confidentiality', 'Leave the client alone'], ['B'], 'Direct suicide-risk assessment is necessary and does not increase suicidal intent.', 'Safety comes first; choose the response that assesses immediacy and lethality.'],
    ['Psychosocial Integrity', 'Which response demonstrates therapeutic communication?', ['Why did you do that?', 'Tell me more about what has been most difficult today.', 'Everything will be fine.', 'You should not feel that way.'], ['B'], 'An open-ended, nonjudgmental invitation supports assessment and expression.', 'Avoid reassurance, judgment and “why” questions.'],
    ['Maternal-Newborn Nursing', 'A postpartum client has heavy bleeding and a boggy uterus. What should the nurse do first?', ['Massage the uterine fundus while summoning assistance', 'Offer oral fluids only', 'Delay assessment for one hour', 'Encourage unassisted ambulation'], ['A'], 'A boggy uterus suggests uterine atony; fundal massage and rapid escalation are immediate priorities.', 'Match the finding to the most likely reversible cause and act on the immediate threat.'],
    ['Maternal-Newborn Nursing', 'Which newborn finding requires immediate evaluation?', ['Central cyanosis', 'Acrocyanosis shortly after birth', 'Sneezing twice', 'A strong cry'], ['A'], 'Central cyanosis indicates inadequate oxygenation and needs urgent assessment.', 'Distinguish normal transition findings from signs of impaired oxygenation.'],
    ['Paediatric Nursing', 'Which finding in an infant with vomiting is most concerning?', ['Sunken fontanel and reduced urine output', 'One wet diaper after feeding', 'Crying during examination', 'Sleeping after a feed'], ['A'], 'A sunken fontanel and oliguria suggest significant dehydration.', 'Choose the finding that signals impaired circulating volume.'],
    ['Paediatric Nursing', 'A child has stridor at rest and increased work of breathing. What is the priority?', ['Inspect the throat with a tongue blade', 'Maintain the airway and obtain urgent help', 'Encourage running', 'Delay intervention until laboratory results return'], ['B'], 'Stridor at rest can signal critical upper-airway obstruction; protect the airway and escalate urgently.', 'Airway findings outrank diagnostic procedures.'],
    ['Medical-Surgical Nursing', 'A client reports crushing chest pain and is diaphoretic. Which action has priority?', ['Begin rapid assessment and activate the emergency response pathway', 'Complete discharge teaching', 'Offer a large meal', 'Ask the client to walk'], ['A'], 'Possible acute coronary syndrome requires immediate assessment and emergency intervention.', 'Apply ABC priorities to sudden, potentially life-threatening symptoms.'],
    ['Medical-Surgical Nursing', 'Which finding in a client with diabetes requires the most immediate action?', ['Altered mental status with diaphoresis', 'A request for dietary teaching', 'A healed foot blister', 'A scheduled appointment next month'], ['A'], 'Altered mental status and diaphoresis may indicate severe hypoglycemia and require immediate assessment and treatment.', 'Prioritize an acute change in neurological status over stable needs.'],
    ['Management of Care', 'Which task is appropriate to delegate to trained assistive personnel?', ['Initial assessment of new chest pain', 'Routine vital signs for a stable client', 'Teaching a new insulin regimen', 'Evaluating pain after medication'], ['B'], 'Routine, predictable tasks for stable clients may be delegated; assessment, teaching and evaluation remain with the nurse.', 'Match the task to the worker’s scope and the client’s stability.'],
    ['Management of Care', 'The nurse receives an unclear prescription. What is the correct action?', ['Guess the intended dose', 'Clarify it with the prescribing provider before carrying it out', 'Ask a family member to interpret it', 'Ignore it without documentation'], ['B'], 'The nurse must clarify incomplete or ambiguous prescriptions before implementation.', 'Do not act on ambiguity when it can affect client safety.'],
    ['Prioritisation', 'Which client should the nurse assess first?', ['A client with new unilateral weakness and slurred speech', 'A stable client awaiting discharge papers', 'A client requesting a blanket', 'A client scheduled for routine teaching'], ['A'], 'New focal neurological deficits suggest stroke and require immediate time-sensitive assessment.', 'Select the client with an acute threat and time-critical treatment window.'],
    ['Prioritisation', 'After handoff, which client requires immediate follow-up?', ['A postoperative client with sudden dyspnea', 'A client asking when lunch arrives', 'A stable client due for a bath', 'A client awaiting routine transport'], ['A'], 'Sudden postoperative dyspnea may indicate pulmonary embolism or another life-threatening problem.', 'Prioritize an acute breathing change over routine care.'],
    ['Safety and Infection Control', 'A fire alarm sounds on the unit. What action follows RACE principles first?', ['Extinguish all fires alone', 'Rescue those in immediate danger', 'Collect client charts', 'Continue medication pass'], ['B'], 'RACE starts with rescuing people at immediate risk before alarm/contain/extinguish steps.', 'Use emergency mnemonics to prioritize immediate life safety actions.'],
    ['Safety and Infection Control', 'Which client should be placed on contact precautions?', ['Client with pulmonary tuberculosis', 'Client with uncontrolled wound drainage', 'Client with measles', 'Client with neutropenia'], ['B'], 'Uncontrolled wound drainage requires contact precautions to limit transmission by direct contact.', 'Link organism route and symptoms with the precaution category.'],
    ['Safety and Infection Control', 'Which finding indicates a need to re-educate on hand hygiene?', ['Cleaning hands before aseptic task', 'Using alcohol rub on visibly soiled hands', 'Cleaning hands after glove removal', 'Cleaning hands after touching surroundings'], ['B'], 'Visibly soiled hands require soap and water, not only alcohol rub.', 'Know when alcohol rub is appropriate versus soap and water.'],
    ['Safety and Infection Control', 'A nurse receives a needlestick injury. What is the priority action?', ['Finish shift first', 'Perform immediate first aid and report per exposure protocol', 'Discard incident details', 'Wait for symptoms'], ['B'], 'Prompt first aid and exposure reporting allow timely prophylaxis and follow-up.', 'Choose the response that preserves time-critical occupational health steps.'],
    ['Pharmacological Therapies', 'A client on opioids has respiratory rate 8/min and is difficult to arouse. What is priority?', ['Give next opioid dose', 'Hold opioid and initiate urgent assessment/escalation', 'Encourage sleep', 'Offer extra sedative'], ['B'], 'Respiratory depression is an opioid emergency requiring immediate intervention.', 'Prioritize airway and breathing over routine pain management.'],
    ['Pharmacological Therapies', 'Before administering digoxin, which assessment is most important?', ['Apical pulse and hold parameters', 'Skin colour only', 'Pupil size only', 'Bowel sounds only'], ['A'], 'Digoxin administration depends on pulse rate and clinical parameters due to bradycardia risk.', 'Identify medication-specific pre-assessment requirements.'],
    ['Pharmacological Therapies', 'Which instruction is correct for clients taking anticoagulants?', ['Double dose after missed tablet', 'Report unusual bleeding or bruising promptly', 'Stop medicine before dental review without advice', 'Take with aspirin daily unless told otherwise'], ['B'], 'Bleeding signs require prompt review to prevent serious complications.', 'Select teaching that supports safety and early complication detection.'],
    ['Pharmacological Therapies', 'A medication order reads 10 mg but vial concentration is 5 mg/mL. How much should be drawn up?', ['1 mL', '2 mL', '5 mL', '10 mL'], ['B'], 'Required volume is dose divided by concentration: 10 mg / 5 mg per mL = 2 mL.', 'Use dimensional reasoning to calculate safe dose volume.'],
    ['Fundamentals of Care', 'Which intervention is best for aspiration risk during feeding?', ['Supine position', 'Upright positioning and swallow precautions', 'Rapid feeding', 'Large bites'], ['B'], 'Upright positioning and paced feeding reduce aspiration risk.', 'Apply basic safety principles in nutrition support.'],
    ['Fundamentals of Care', 'A client has urinary catheter discomfort and cloudy urine. What is priority?', ['Ignore symptoms', 'Assess for possible CAUTI and escalate findings', 'Remove catheter without order', 'Increase sedation'], ['B'], 'Symptoms suggest possible infection and require assessment and escalation.', 'Recognize early infection signs linked to invasive devices.'],
    ['Fundamentals of Care', 'Which finding shows effective pain reassessment after analgesia?', ['No record made', 'Documented pain score change and functional response', 'Only medicine name listed', 'Vitals omitted'], ['B'], 'Pain management includes reassessment of intensity and function after intervention.', 'Evaluation is essential to confirm treatment effect.'],
    ['Fundamentals of Care', 'Which action helps prevent constipation in immobile clients?', ['Restrict fluid intake', 'Promote hydration, fibre and mobility as tolerated', 'Delay toileting opportunities', 'Use laxatives only after obstruction ruled out'], ['B'], 'Hydration, fibre and activity are first-line preventive measures.', 'Prefer non-pharmacologic prevention when appropriate.'],
    ['Psychosocial Integrity', 'A grieving client says, "I should have done more." Which response is therapeutic?', ['You should not feel that way', 'This sounds very painful; tell me more about what you are feeling', 'At least they lived a long life', 'Do not think about it'], ['B'], 'Open, empathic responses encourage emotional expression and assessment.', 'Choose communication that validates emotion without judgment.'],
    ['Psychosocial Integrity', 'A client with panic symptoms asks for help. What is best initial intervention?', ['Challenge beliefs immediately', 'Stay with client, provide calm reassurance and breathing coaching', 'Leave to promote independence', 'Discuss discharge plans first'], ['B'], 'Presence and de-escalation reduce panic while allowing further assessment.', 'Initial management aims to restore safety and control.'],
    ['Psychosocial Integrity', 'Which behavior indicates possible elder abuse and needs escalation?', ['Family asks about visiting hours', 'Repeated unexplained injuries with delayed care-seeking', 'Client dislikes hospital food', 'Relative brings clothes'], ['B'], 'Patterned injuries and delayed presentation can indicate abuse and require safeguarding action.', 'Identify red flags and escalate using policy.'],
    ['Psychosocial Integrity', 'A client declines eye contact and speaks little after trauma. What should nurse do?', ['Force detailed disclosure', 'Offer choice, privacy and supportive pacing during assessment', 'Discharge immediately', 'Ignore behavior'], ['B'], 'Trauma-informed communication respects control and psychological safety.', 'Avoid coercion and support gradual engagement.'],
    ['Maternal-Newborn Nursing', 'A pregnant client reports severe headache, visual changes and epigastric pain. Priority?', ['Routine review next week', 'Urgent assessment for hypertensive disorder', 'Advise rest only', 'Increase caffeine intake'], ['B'], 'These are warning signs of severe preeclampsia requiring urgent assessment.', 'Recognize maternal red-flag symptoms requiring rapid escalation.'],
    ['Maternal-Newborn Nursing', 'Which newborn intervention supports thermoregulation immediately after birth?', ['Delayed drying', 'Drying, skin-to-skin contact and warm covering', 'Cool room exposure', 'Early bathing'], ['B'], 'Drying and skin-to-skin reduce heat loss in newborns.', 'Apply simple physiology to immediate neonatal care.'],
    ['Maternal-Newborn Nursing', 'A postpartum client saturates two pads in 30 minutes. What is priority?', ['Document for later', 'Immediate hemorrhage assessment and emergency response', 'Encourage ambulation', 'Offer oral iron only'], ['B'], 'Heavy rapid bleeding may indicate postpartum hemorrhage and requires urgent action.', 'Prioritize life-threatening blood loss signs.'],
    ['Maternal-Newborn Nursing', 'Which teaching is correct for breastfeeding latch?', ['Latch only on nipple tip', 'Ensure deep latch including areola to reduce trauma', 'Feed every 8-10 hours', 'Stop if infant roots frequently'], ['B'], 'Deep latch improves transfer and reduces nipple trauma.', 'Select teaching that supports effective feeding mechanics.'],
    ['Paediatric Nursing', 'A child with asthma has audible wheeze and speaks in short phrases. Priority action?', ['Delay bronchodilator', 'Initiate acute asthma protocol and monitor response', 'Encourage running to open lungs', 'Give cough suppressant only'], ['B'], 'Signs suggest moderate-severe exacerbation needing protocol-based treatment.', 'Rapid respiratory support takes priority in paediatric asthma.'],
    ['Paediatric Nursing', 'Which sign suggests severe dehydration in a child?', ['Moist oral mucosa', 'Capillary refill over 3 seconds with lethargy', 'Normal urine output', 'Tearful crying'], ['B'], 'Delayed capillary refill and lethargy indicate poor perfusion and dehydration.', 'Use perfusion and mental status to gauge dehydration severity.'],
    ['Paediatric Nursing', 'A parent reports possible accidental ingestion of cleaning fluid. What should nurse do first?', ['Induce vomiting', 'Assess airway/breathing and contact poison management pathway', 'Offer milk immediately without assessment', 'Wait for symptoms'], ['B'], 'Caustic ingestion requires urgent airway assessment and specialist guidance.', 'Do not induce emesis; follow poison protocols.'],
    ['Paediatric Nursing', 'Which strategy improves medicine adherence in school-age children?', ['No explanation to child', 'Provide clear age-appropriate instructions and involve caregiver', 'Use punishment for missed doses', 'Stop medicines when symptoms improve'], ['B'], 'Understanding and caregiver involvement improve adherence and safety.', 'Education should match developmental level.'],
    ['Medical-Surgical Nursing', 'A client with COPD becomes drowsy with rising CO2. Priority?', ['Increase sedatives', 'Urgent respiratory assessment and escalation for ventilatory support', 'Offer large meal', 'Delay blood gas review'], ['B'], 'Drowsiness with hypercapnia can indicate respiratory failure.', 'Recognize signs of CO2 retention and deteriorating ventilation.'],
    ['Medical-Surgical Nursing', 'Which assessment finding suggests compartment syndrome after limb injury?', ['Warm limb with strong pulse', 'Severe pain out of proportion and pain on passive stretch', 'Mild swelling relieved by elevation', 'Improved sensation'], ['B'], 'Disproportionate pain and stretch pain are early critical signs.', 'Identify limb-threatening complications early.'],
    ['Medical-Surgical Nursing', 'A postoperative client has calf pain and unilateral swelling. What is nurse priority?', ['Massage calf', 'Assess for possible DVT and escalate urgently', 'Encourage deep tissue massage', 'Apply heat and discharge'], ['B'], 'DVT signs need urgent evaluation to prevent embolic complications.', 'Avoid interventions that may dislodge clot.'],
    ['Medical-Surgical Nursing', 'Which finding is most concerning in acute abdominal pain?', ['Pain score 3/10 stable', 'Rigid abdomen with rebound tenderness', 'Request for extra blanket', 'Mild nausea only'], ['B'], 'Peritonism signs indicate possible surgical emergency.', 'Prioritize findings suggesting acute abdomen complications.'],
    ['Management of Care', 'Which task can be delegated to assistive personnel for a stable client?', ['Initial neurological assessment', 'Ambulation assistance using established plan', 'Complex wound assessment', 'Discharge education'], ['B'], 'Stable, routine tasks may be delegated; assessment and teaching remain nurse responsibilities.', 'Use scope and stability to decide delegation.'],
    ['Management of Care', 'A nurse is caring for clients from different cultures. What action reflects culturally safe care?', ['Use same assumptions for all', 'Assess individual beliefs and adapt care respectfully', 'Avoid interpreter use', 'Ignore spiritual preferences'], ['B'], 'Culturally safe care requires individualized assessment and adaptation.', 'Avoid stereotypes; ask and align with patient preferences.'],
    ['Management of Care', 'Which action is required when receiving verbal telephone prescription?', ['Document from memory later', 'Read back complete order for confirmation', 'Ask another nurse to guess unclear parts', 'Carry out without verification'], ['B'], 'Read-back reduces communication errors in verbal orders.', 'Closed-loop communication improves medication safety.'],
    ['Management of Care', 'A near-miss medication event occurs with no harm. What should nurse do?', ['Do not report since no harm', 'Report through incident system to support learning', 'Delete related notes', 'Inform only friends'], ['B'], 'Near-miss reporting identifies system risks before harm occurs.', 'Safety culture relies on transparent reporting.'],
    ['Prioritisation', 'Which client should be seen first in the emergency queue?', ['Sprained ankle pain score 4/10', 'Client with stridor and suprasternal recession', 'Minor rash for two days', 'Prescription refill request'], ['B'], 'Upper airway obstruction signs are immediately life-threatening.', 'Airway compromise always outranks non-urgent problems.'],
    ['Prioritisation', 'During shift, which finding warrants immediate provider notification?', ['New urine output 10 mL/hour', 'Request for extra blanket', 'Mild chronic back pain unchanged', 'Missed television programme'], ['A'], 'Severely reduced urine output can indicate shock or acute kidney injury.', 'Recognize objective deterioration metrics requiring escalation.'],
    ['Reduction of Risk Potential', 'A client has potassium 6.3 mmol/L and peaked T waves. Priority action?', ['Repeat blood test tomorrow', 'Immediate cardiac monitoring and urgent treatment escalation', 'Give potassium supplement', 'Encourage high-potassium diet'], ['B'], 'Severe hyperkalaemia with ECG changes is life-threatening.', 'Link abnormal labs with immediate physiological risk.'],
    ['Reduction of Risk Potential', 'After contrast study, which client finding is highest concern?', ['Mild thirst', 'New wheeze and facial swelling', 'Small bruise at cannula site', 'Desire to sleep'], ['B'], 'Wheeze and facial swelling suggest acute hypersensitivity reaction.', 'Differentiate benign effects from anaphylaxis signs.'],
    ['Reduction of Risk Potential', 'A client on anticoagulants has black tarry stool. What should nurse do?', ['Reassure and discharge', 'Escalate possible gastrointestinal bleeding urgently', 'Give iron tablets only', 'Document and review next week'], ['B'], 'Melena while anticoagulated suggests potentially serious bleeding.', 'Identify occult bleeding indicators.'],
    ['Reduction of Risk Potential', 'A post-thyroidectomy client develops tingling around mouth and muscle twitching. Likely priority?', ['Normal recovery only', 'Assess for hypocalcaemia and notify provider', 'Increase sedatives', 'Restrict fluids'], ['B'], 'Perioral tingling and twitching can indicate hypocalcaemia.', 'Match postoperative complication patterns promptly.'],
    ['Physiological Adaptation', 'A client with heart failure has sudden frothy sputum and severe dyspnea. Priority?', ['Encourage oral fluids', 'Urgent respiratory support and escalation for pulmonary edema', 'Lay flat and observe', 'Delay action until x-ray'], ['B'], 'Acute pulmonary edema requires immediate supportive intervention.', 'Recognize decompensated heart failure signs.'],
    ['Physiological Adaptation', 'A septic client becomes hypotensive despite fluids. What is next priority?', ['Discontinue monitoring', 'Escalate for vasopressor support per protocol', 'Give sedative and wait', 'Switch off oxygen'], ['B'], 'Persistent septic shock needs escalation to advanced hemodynamic support.', 'Follow sepsis pathway when initial measures fail.'],
    ['Physiological Adaptation', 'A client with head injury develops unilateral dilated pupil and decreasing GCS. Priority?', ['Routine neuro check in 4 hours', 'Immediate emergency escalation for possible raised ICP', 'Give oral analgesic only', 'Encourage ambulation'], ['B'], 'Neurological deterioration with anisocoria can indicate herniation risk.', 'Treat worsening neuro signs as time-critical.'],
    ['Physiological Adaptation', 'Which sign in diabetic ketoacidosis indicates improvement?', ['Persistent ketones and acidosis', 'Closing anion gap with improving bicarbonate', 'Worsening hypotension', 'Increasing confusion'], ['B'], 'Metabolic normalization indicates improving DKA resolution.', 'Use objective biochemical trends to judge adaptation.'],
    ['Health Promotion and Maintenance', 'Which counselling point best supports smoking cessation?', ['Set no quit date', 'Use behavioural support and discuss pharmacotherapy options', 'Stop all follow-up', 'Advise smoking only outdoors'], ['B'], 'Combined behavioural and pharmacologic support improves quit success.', 'Choose evidence-based preventive counseling.'],
    ['Health Promotion and Maintenance', 'A client asks about hypertension prevention. Which advice is most appropriate?', ['Increase sodium intake', 'Promote DASH-style diet, activity and weight management', 'Avoid all exercise', 'Stop monitoring blood pressure'], ['B'], 'Lifestyle modification reduces hypertension risk and improves control.', 'Select modifiable risk reduction strategies.'],
    ['Health Promotion and Maintenance', 'Which vaccine teaching is correct for adults with chronic disease?', ['Vaccines are never indicated', 'Stay up to date with recommended immunizations and boosters', 'Only childhood vaccines matter', 'Skip influenza vaccination'], ['B'], 'Chronic disease increases benefit from guideline-recommended vaccines.', 'Preventive care includes age and risk-based vaccination.'],
    ['Health Promotion and Maintenance', 'Which strategy supports medication adherence after discharge?', ['Complex schedule without explanation', 'Use teach-back and simplified written plan', 'Rely on memory alone', 'Discourage family support'], ['B'], 'Teach-back and clear plans improve understanding and adherence.', 'Effective discharge education reduces readmission risk.']
  ];

  function normaliseStem(value) {
    return String(value || '')
      .replace(/^\[BTV-(?:CBT|NCLEX)-(?:SAMPLE(?:-V\d+)?-)?\d+\]\s*/i, '')
      .replace(/^Extended practice draft \d+\.\s*/i, '')
      .replace(/^[^.]+ is being cared for in [^.]+ during the [^.]+\.\s*/i, '')
      .replace(/\s+/g, ' ').trim().toLowerCase();
  }

  function buildCbt(total = cbtSeeds.length) {
    return cbtSeeds.slice(0, Math.min(total, cbtSeeds.length)).map((seed, index) => {
      return {
        profession: seed[0] === 'Child Nursing' ? 'nurse' : 'both',
        subject: seed[0], difficulty: ['easy', 'medium', 'hard'][index % 3],
        question_text: `[BTV-CBT-SAMPLE-${pad(index + 1)}] ${seed[1]}`,
        option_a: seed[2][0], option_b: seed[2][1], option_c: seed[2][2], option_d: seed[2][3],
        correct_option: seed[3], explanation: seed[4], access_level: 'free', is_active: false,
        standard_version: 'Unofficial sample aligned to the NMC Test of Competence 2021 blueprint', blueprint_domain: cbtDomain[seed[0]],
        review_status: 'sample_unreviewed', quality_status: 'needs_clinical_review'
      };
    });
  }

  function buildNclex(total = nclexSeeds.length) {
    return nclexSeeds.slice(0, Math.min(total, nclexSeeds.length)).map((seed, index) => {
      return {
        exam: 'NCLEX-RN', category: nclexNeed[seed[0]], client_need: nclexNeed[seed[0]],
        difficulty: ['easy', 'medium', 'hard'][index % 3], question_type: 'single',
        question_text: `[BTV-NCLEX-SAMPLE-${pad(index + 1)}] ${seed[1]}`,
        option_a: seed[2][0], option_b: seed[2][1], option_c: seed[2][2], option_d: seed[2][3],
        option_e: null, option_f: null, correct_options: seed[3], rationale: seed[4],
        test_strategy: seed[5], access_level: 'free', is_active: false,
        standard_version: 'Unofficial sample aligned to the NCSBN 2026 NCLEX-RN Test Plan', blueprint_domain: nclexNeed[seed[0]],
        review_status: 'sample_unreviewed', quality_status: 'needs_clinical_review'
      };
    });
  }

  window.BTVQuestionFactory = {
    TARGET: 2000, CBT_CATEGORIES, NCLEX_CATEGORIES, IELTS_CATEGORIES, buildCbt, buildNclex, normaliseStem,
    note: 'Original, unofficial sample items. They remain inactive until qualified clinical and regulatory review; cosmetic variants are never generated.'
  };
})();
