(()=>{'use strict';if(window.__btvV67)return;window.__btvV67=true;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let state={section:'reading',index:0,audio:null,recorder:null,chunks:[],recording:null,premium:false,unlocks:new Set(),costs:{ielts_reading:100,ielts_writing:100},listeningMode:'gate',instructionReady:false,audioPlaying:false,listeningSetId:null};
const LISTENING_INSTRUCTION_SET='ielts-listening-test-instructions';
const bank=()=>window.BTVIELTSAcademic,account=()=>{try{return JSON.parse(localStorage.getItem('btv-account')||'{}')}catch{return {}}};
const eligible=()=>{try{const journey=JSON.parse(localStorage.getItem('btv-v1')||'{}'),profile=JSON.parse(localStorage.getItem('btv-profile')||'{}'),country=journey.country||profile.destination||'uk';return ['uk','au','ca','nz','ie'].includes(country)}catch{return false}};
async function premium(){const a=account();if(['premium','admin'].includes(String(a.accountType||a.account_type||'').toLowerCase())||a.role==='admin')return true;try{const u=(await window.btvSupabase.auth.getUser()).data.user;if(!u)return false;const {data}=await window.btvSupabase.from('profiles').select('account_type,role').eq('id',u.id).maybeSingle();return data?.role==='admin'||data?.account_type==='premium'}catch{return false}}
async function loadUnlocks(){
  if(!window.btvSupabase)return;
  try{const user=(await window.btvSupabase.auth.getUser()).data.user;if(!user)return;
    const [catalog,owned]=await Promise.all([
      window.btvSupabase.from('btv_learning_unlock_catalog').select('code,coin_cost').eq('module','ielts').eq('is_active',true),
      window.btvSupabase.from('btv_user_learning_unlocks').select('unlock_code').eq('user_id',user.id)
    ]);
    (catalog.data||[]).forEach(x=>state.costs[x.code]=Number(x.coin_cost));
    state.unlocks=new Set((owned.data||[]).map(x=>x.unlock_code));
  }catch{}
}
const unlockCode=id=>'ielts_'+id;
const hasAccess=id=>state.unlocks.has(unlockCode(id));
async function unlockSection(id){const button=document.querySelector('[data-unlock-ielts]');if(button){button.disabled=true;button.textContent='Unlocking securely...'}
  try{const {data,error}=await window.btvSupabase.rpc('btv_unlock_learning',{p_code:unlockCode(id)});if(error)throw error;await loadUnlocks();window.dispatchEvent(new CustomEvent('btv:wallet-changed',{detail:data}));renderShell();renderPractice();window.toast?.('IELTS section unlocked.');}
  catch(e){window.alert(e.message||'This section could not be unlocked.');if(button){button.disabled=false;button.textContent='Unlock with Beyond Coins'}}
}
function install(){const learn=$('#learn');if(!learn)return false;const existing=learn.querySelector('[data-learn-tab="ielts"]'),panel=$('#ieltsLesson');if(!eligible()){existing?.remove();panel?.remove();return true}if(existing)return true;const tabs=learn.querySelector('.learnTabs'),last=learn.querySelector('.learnPanel:last-of-type');if(!tabs||!last)return false;tabs.insertAdjacentHTML('beforeend','<button data-learn-tab="ielts">IELTS Academic <small>Beyond Coins</small></button>');last.insertAdjacentHTML('afterend','<section id="ieltsLesson" class="learnPanel"><div id="ieltsAcademicRoot" class="ieltsAcademicPanel"></div></section>');const btn=learn.querySelector('[data-learn-tab="ielts"]');btn.onclick=()=>{if(typeof window.showLearningTab==='function')window.showLearningTab('ielts');openIELTS()};return true}
async function openIELTS(){if(!eligible()){window.toast?.('IELTS preparation is not shown for your selected destination.');return}await loadUnlocks();renderShell();if(hasAccess(state.section))renderPractice()}
function renderShell(){const root=$('#ieltsAcademicRoot');if(!root)return;const sections=[['reading','Reading','500 Academic passages and questions','available'],['writing','Writing','500 Task 1 and Task 2 prompts','available'],['listening','Listening','Marked as coming soon while audio library is finalised','soon'],['speaking','Speaking','Marked as coming soon while voice assessment is finalised','soon']];root.innerHTML=`<div class="ieltsHero"><span>IELTS ACADEMIC PREPARATION</span><h2>IELTS Academic Studio</h2><p>Original Academic IELTS-style preparation for internationally educated nurses and midwives. Reading and Writing are unlocked securely with Beyond Coins.</p><div class="ieltsHeroMeta"><b>1,000 available practice items</b><b>Academic module only</b><b>Listening coming soon</b><b>Speaking coming soon</b><b>Zibur feedback</b></div></div><div class="ieltsSectionGrid">${sections.map(([id,label,copy,status])=>{const open=status==='soon'||hasAccess(id),cost=state.costs[unlockCode(id)]||100;return `<button data-ielts-section="${id}" data-status="${status}" class="${state.section===id?'active':''} ${status==='soon'?'comingSoon':''}"><b>${label}${status==='soon'?' <em>Coming soon</em>':open?' <em>Available</em>':` <em>${cost} BC</em>`}</b><small>${copy}</small></button>`}).join('')}</div><div id="ieltsPractice"></div>`;root.querySelectorAll('[data-ielts-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.ieltsSection;state.index=0;state.listeningMode='gate';state.instructionReady=false;state.listeningSetId=null;renderShell();if(b.dataset.status==='soon')renderComingSoon(state.section);else if(hasAccess(state.section))renderPractice();else renderLocked(state.section)})}
function renderLocked(id){const box=$('#ieltsPractice'),label=id[0].toUpperCase()+id.slice(1),cost=state.costs[unlockCode(id)]||100;if(!box)return;box.innerHTML=`<article class="ieltsCard ieltsCoinLock"><span class="ieltsEyebrow">BEYOND COINS ACCESS</span><h3>Unlock IELTS Academic ${label}</h3><p>Get permanent access to all 500 ${label} practice items, saved progress and formative Zibur feedback.</p><strong>${cost} BC</strong><button type="button" data-unlock-ielts class="ieltsPrimary">Unlock with Beyond Coins</button><small>Your unlock is permanent and recorded in your Beyond Coins history.</small></article>`;box.querySelector('[data-unlock-ielts]').onclick=()=>unlockSection(id)}
function renderComingSoon(section){const box=$('#ieltsPractice'),label=section[0].toUpperCase()+section.slice(1);if(box)box.innerHTML=`<article class="ieltsCard ieltsSoon"><span class="ieltsEyebrow">IN DEVELOPMENT</span><h3>${label} is coming soon</h3><p>We are giving this section further design, content and accessibility testing before releasing it. It will not use a poor-quality artificial voice.</p><button type="button" data-community-notify class="ieltsPrimary">Notify me when it is ready</button></article>`}
function listeningSet(){const sets=bank()?.listeningSets||[];const q=current();if(q?.setId)return sets.find(x=>x.id===q.setId)||null;return sets[Math.floor(state.index/10)]||null}
async function signedListeningUrl(setId){
  if(!setId||!window.btvSupabase)return null;
  try{
    const fn=await window.btvSupabase.functions.invoke('get-ielts-listening-audio',{body:{set_id:setId}});
    const fnUrl=fn?.data?.signed_url||fn?.data?.url||null;
    if(fnUrl)return fnUrl;
  }catch{}
  try{
    const {data}=await window.btvSupabase.from('ielts_listening_audio').select('storage_path,status').eq('set_id',setId).eq('status','published').maybeSingle();
    if(!data?.storage_path)return null;
    const signed=await window.btvSupabase.storage.from('ielts-audio').createSignedUrl(data.storage_path,1800);
    return signed.data?.signedUrl||null;
  }catch{return null}
}
function renderListeningGate(){const box=$('#ieltsPractice');if(!box)return;const set=listeningSet();box.innerHTML=`<article class="ieltsCard"><span class="ieltsEyebrow">IELTS LISTENING</span><h3>Are you ready for your IELTS Listening?</h3><p>${set?`Set: ${esc(set.title)}.`:'Your listening test is ready.'} Once audio begins, keep listening. Controls are hidden during playback.</p><div class="ieltsActions"><button type="button" id="ieltsReadyYes" class="primary">Yes, I am ready</button></div><div id="ieltsListeningStatus" class="ieltsFeedback"><p class="ieltsNotice">You will hear instructions first.</p></div></article>`;$('#ieltsReadyYes').onclick=playListeningInstructions}
function playInstructionFallback(out){const text='Welcome to your IELTS Listening test. You will hear each recording once. Listen carefully and answer the questions based on what you hear. Do not pause or replay the audio. Click Start my listening test to begin.';if(!('speechSynthesis' in window)){state.instructionReady=true;renderListeningStart();return}window.speechSynthesis.cancel();const say=new SpeechSynthesisUtterance(text);say.rate=.94;say.onend=()=>{state.instructionReady=true;renderListeningStart()};say.onerror=()=>{state.instructionReady=true;renderListeningStart()};out.innerHTML='<p>Playing instructions. Please listen carefully.</p>';window.speechSynthesis.speak(say)}
async function playListeningInstructions(){const out=$('#ieltsListeningStatus');if(!out)return;out.innerHTML='<p>Loading instructions...</p>';const url=await signedListeningUrl(LISTENING_INSTRUCTION_SET);if(!url){playInstructionFallback(out);return}out.innerHTML='<p>Playing instructions. Please listen carefully.</p>';const audio=new Audio(url);audio.onended=()=>{state.instructionReady=true;renderListeningStart()};audio.onerror=()=>playInstructionFallback(out);audio.play().catch(()=>playInstructionFallback(out))}
function renderListeningStart(){const box=$('#ieltsPractice');if(!box)return;box.innerHTML=`<article class="ieltsCard"><span class="ieltsEyebrow">IELTS LISTENING</span><h3>Instructions complete</h3><p>When you start, the screen will be blank while the recording plays.</p><div class="ieltsActions"><button type="button" id="ieltsStartListening" class="primary">Start my listening test</button></div></article>`;$('#ieltsStartListening').onclick=startListeningAudio}
function renderListeningBlank(){const box=$('#ieltsPractice');if(!box)return;box.innerHTML=`<div class="ieltsListeningBlank" aria-live="polite"><span class="sr-only">Listening audio is in progress.</span></div>`}
async function startListeningAudio(){
  const set=listeningSet(),url=await signedListeningUrl(set?.id);
  if(!url){const box=$('#ieltsPractice');if(box)box.innerHTML='<article class="ieltsCard"><h3>Listening audio unavailable</h3><p>This listening set has no published audio yet. Ask admin to publish audio for this set.</p></article>';return}
  state.audioPlaying=true;state.listeningMode='playing';state.listeningSetId=set?.id||null;renderListeningBlank();
  const audio=new Audio(url);
  audio.onended=()=>{state.audioPlaying=false;state.listeningMode='questions';renderListeningQuestions()};
  audio.onerror=()=>{state.audioPlaying=false;state.listeningMode='gate';renderListeningGate()};
  audio.play().catch(()=>{state.audioPlaying=false;state.listeningMode='gate';renderListeningGate()});
}
function renderListeningQuestions(){const box=$('#ieltsPractice'),q=current();if(!box||!q)return;const total=bank().count('listening');box.innerHTML=`<div class="ieltsWorkspace"><article class="ieltsCard"><span class="ieltsEyebrow">${esc(q.type||'Listening')}</span><h3>${esc(q.title||`Question ${q.number}`)}</h3><p class="ieltsQuestion">${esc(q.prompt)}</p>${questionInput(q)}<div class="ieltsActions"><button id="ieltsPrevious">Previous</button><button id="ieltsSubmit" class="primary">Check answer</button><button id="ieltsNext">Next</button></div></article><aside class="ieltsCard"><span class="ieltsEyebrow">YOUR SESSION</span><h3>Listening</h3><p>Question ${state.index+1} of ${total}</p><div id="ieltsFeedback" class="ieltsFeedback"><p class="ieltsNotice">Answer after listening. No replay controls are shown during playback.</p></div></aside></div>`;bind(q)}
async function loadHumanAudio(){state.audio=null;if(state.section!=='listening')return;const set=bank()?.listeningSets?.[Math.floor(state.index/10)];if(!set||!window.btvSupabase)return;try{const {data}=await window.btvSupabase.from('ielts_listening_audio').select('storage_path,status').eq('set_id',set.id).eq('status','published').maybeSingle();if(data?.storage_path){const signed=await window.btvSupabase.storage.from('ielts-audio').createSignedUrl(data.storage_path,1800);state.audio=signed.data?.signedUrl||null}}catch{}}
function current(){const b=bank();if(state.section==='listening')return b?.bank('listening')?.[state.index%b.count('listening')];if(state.section==='reading')return b?.bank('reading')?.[state.index%b.count('reading')];return b?.bank(state.section)?.[state.index%b.count(state.section)]}
function questionInput(q){if(q.options?.length)return `<div class="ieltsOptions">${q.options.map((o,i)=>`<label><input type="radio" name="ieltsAnswer" value="${esc(o)}"><span>${String.fromCharCode(65+i)}. ${esc(o)}</span></label>`).join('')}</div>`;return '<input id="ieltsAnswer" class="ieltsAnswer" autocomplete="off" placeholder="Type your answer">'}
function chart(v){if(!v)return'';const max=Math.max(...v.values);return `<div class="ieltsChart"><b>${esc(v.title)}</b><small> · ${esc(v.unit)}</small><div class="ieltsBars">${v.values.map((n,i)=>`<div class="ieltsBar"><b>${n}%</b><i style="height:${Math.round(n/max*82)}%"></i><small>${v.labels[i]}</small></div>`).join('')}</div></div>`}
function renderPractice(){if(!hasAccess(state.section)&&!['listening','speaking'].includes(state.section)){renderLocked(state.section);return}if(['listening','speaking'].includes(state.section)){renderComingSoon(state.section);return}const box=$('#ieltsPractice'),q=current();if(!box||!q)return;const total=bank().count(state.section),intro=state.section==='reading'?bank().readingSets[Math.floor(state.index/10)]?.passage:'';let main='';if(state.section==='reading')main=`<details class="ieltsCard" open><summary><b>Academic passage</b></summary><div class="ieltsPassage">${esc(intro)}</div></details><p class="ieltsQuestion"><b>${esc(q.type)}</b><br>${esc(q.prompt)}</p>${questionInput(q)}`;if(state.section==='writing')main=`${chart(q.visual)}<p class="ieltsQuestion">${esc(q.prompt)}</p><textarea id="ieltsEssay" class="ieltsEssay" placeholder="Write at least ${q.minimumWords} words..."></textarea><div class="ieltsProgress"><span id="ieltsWords">0 words</span><span>Minimum ${q.minimumWords}</span></div>`;box.innerHTML=`<div class="ieltsWorkspace"><article class="ieltsCard"><span class="ieltsEyebrow">${esc(q.type||state.section.toUpperCase())}</span><h3>${esc(q.title||`Question ${q.number}`)}</h3>${main}<div class="ieltsActions"><button id="ieltsPrevious">Previous</button><button id="ieltsSubmit" class="primary">Ask Zibur to mark</button><button id="ieltsNext">Next</button></div></article><aside class="ieltsCard"><span class="ieltsEyebrow">YOUR SESSION</span><h3>${state.section[0].toUpperCase()+state.section.slice(1)}</h3><p>Question ${state.index+1} of ${total}</p><div id="ieltsFeedback" class="ieltsFeedback"><p class="ieltsNotice">Complete the task, then request formative feedback from Zibur. Official test results can only be issued by an authorised IELTS test centre.</p></div></aside></div>`;bind(q)}
function consumePaidQuestion(){try{const x=JSON.parse(sessionStorage.getItem('btv-ielts-paid-session')||'null');if(!x)return true;if(x.expires<=Date.now()||x.remaining<=0)return false;x.remaining--;sessionStorage.setItem('btv-ielts-paid-session',JSON.stringify(x));return x.remaining>=0}catch{return true}}
function bind(q){$('#ieltsPrevious').onclick=async()=>{const beforeSet=state.section==='listening'?listeningSet()?.id:null;state.index=(state.index-1+bank().count(state.section))%bank().count(state.section);const afterSet=state.section==='listening'?listeningSet()?.id:null;if(state.section==='listening'&&beforeSet!==afterSet){state.listeningMode='gate';state.instructionReady=false;state.listeningSetId=null}else await loadHumanAudio();renderPractice()};$('#ieltsNext').onclick=async()=>{const beforeSet=state.section==='listening'?listeningSet()?.id:null;state.index=(state.index+1)%bank().count(state.section);const afterSet=state.section==='listening'?listeningSet()?.id:null;if(state.section==='listening'&&beforeSet!==afterSet){state.listeningMode='gate';state.instructionReady=false;state.listeningSetId=null}else await loadHumanAudio();renderPractice()};$('#ieltsSubmit').onclick=()=>state.section==='listening'?checkListening(q):mark(q);$('#ieltsPlay')?.addEventListener('click',()=>{new Audio(state.audio).play()});$('#ieltsEssay')?.addEventListener('input',e=>$('#ieltsWords').textContent=`${e.target.value.trim().split(/\s+/).filter(Boolean).length} words`);if(state.section==='speaking')bindRecorder()}
function checkListening(q){const response=answer(),out=$('#ieltsFeedback');if(!response){out.innerHTML='<p>Enter an answer before checking.</p>';return}const normal=text=>String(text||'').trim().toLowerCase().replace(/[^a-z0-9£$€]+/g,' ');const ok=normal(response)===normal(q.answer);out.innerHTML=`<h4>${ok?'Correct.':`Best answer: ${esc(q.answer)}`}</h4><p>${esc(q.explanation||'Check spelling and key details from the recording.')}</p>`}
async function bindRecorder(){if(!navigator.mediaDevices?.getUserMedia){$('#ieltsRecord').disabled=true;$('#ieltsTimer').textContent='Microphone unavailable';return}$('#ieltsRecord').onclick=async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(stream);state.recorder.ondataavailable=e=>e.data.size&&state.chunks.push(e.data);state.recorder.onstop=()=>{state.recording=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'});stream.getTracks().forEach(t=>t.stop());$('#ieltsListen').disabled=false;$('#ieltsSubmit').disabled=false;$('#ieltsTimer').textContent='Recording ready'};state.recorder.start();$('#ieltsRecord').disabled=true;$('#ieltsStop').disabled=false;$('#ieltsSubmit').disabled=true;let n=0;state.timer=setInterval(()=>{$('#ieltsTimer').textContent=`Recording ${++n}s`},1000)};$('#ieltsStop').onclick=()=>{clearInterval(state.timer);state.recorder?.stop();$('#ieltsStop').disabled=true;$('#ieltsRecord').disabled=false};$('#ieltsListen').onclick=()=>state.recording&&new Audio(URL.createObjectURL(state.recording)).play()}
function answer(){return $('input[name="ieltsAnswer"]:checked')?.value||$('#ieltsAnswer')?.value.trim()||$('#ieltsEssay')?.value.trim()||''}
const b64=blob=>new Promise((res,rej)=>{const r=new FileReader;r.onerror=rej;r.onload=()=>res(String(r.result).split(',')[1]);r.readAsDataURL(blob)});
async function mark(q){const out=$('#ieltsFeedback'),button=$('#ieltsSubmit');const response=answer();if(!response){out.innerHTML='<p>Enter an answer before marking.</p>';return}button.disabled=true;button.textContent='Zibur is reviewing...';try{if(!window.btvSupabase?.functions)throw Error('The secure Zibur service is still loading.');const task=state.section==='writing'?'Assess this IELTS Academic writing response using the official-style criteria: Task Achievement or Task Response, Coherence and Cohesion, Lexical Resource, and Grammatical Range and Accuracy. Give an estimated formative band, specific evidence, strengths, and three practical improvements.':'Mark this IELTS Academic reading response. State whether it is correct, explain the evidence from the passage or question, and give one useful reading strategy.';const prompt=`${task}\n\nTask: ${q.title||q.prompt||q.type}\nCandidate response: ${response}`;const context={feature:'IELTS Academic preparation',section:state.section,item:{type:q.type,title:q.title,prompt:q.prompt,answer:q.answer,explanation:q.explanation,minimumWords:q.minimumWords},candidateResponse:response,safety:'Do not claim this is an official IELTS result.'};const timeout=new Promise((_,reject)=>setTimeout(()=>reject(Error('Zibur took too long to respond. Please try again.')),35000));const result=await Promise.race([window.btvSupabase.functions.invoke('zibur-gemini',{body:{question:prompt,history:[],context}}),timeout]);if(result.error)throw result.error;if(result.data?.error)throw new Error(result.data.error);const text=String(result.data?.answer||'').trim();if(!text)throw Error('Zibur did not return feedback.');showFeedback({answer:text})}catch(e){const fallback=window.BTVZiburFallback?.markIELTS(state.section,q,response);if(fallback)showFeedback({answer:fallback});else out.innerHTML=`<p><b>Zibur feedback is temporarily unavailable.</b></p><p>${esc(e.message||'Try again shortly.')}</p>`}finally{button.disabled=false;button.textContent='Ask Zibur to mark'}}
function showFeedback(d){const out=$('#ieltsFeedback');if(d.answer){out.innerHTML=`<h4>Zibur formative feedback</h4><div class="ieltsZiburAnswer">${esc(d.answer).replace(/\n/g,'<br>')}</div><p class="ieltsNotice">This is Zibur-assisted formative feedback, not an official IELTS result.</p>`;return}out.innerHTML=`<div class="score">${esc(d.band||d.score||'—')}</div><h4>${esc(d.summary||'Formative feedback')}</h4>${d.criteria?`<ul>${Object.entries(d.criteria).map(([k,v])=>`<li><b>${esc(k)}:</b> ${esc(v)}</li>`).join('')}</ul>`:''}${d.strengths?.length?`<p><b>Strengths</b><br>${d.strengths.map(esc).join(' · ')}</p>`:''}${d.improvements?.length?`<p><b>Improve next</b><br>${d.improvements.map(esc).join(' · ')}</p>`:''}<p class="ieltsNotice">This is Zibur-assisted formative feedback, not an official IELTS result.</p>`}
let installer;const startInstall=()=>{if(install()){installer?.disconnect();return}installer=new MutationObserver(()=>{if(install())installer.disconnect()});installer.observe(document.documentElement,{childList:true,subtree:true})};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',startInstall):startInstall();window.BTVIELTS={open:openIELTS,refresh:install,eligible};
const v68css=document.createElement('link');v68css.rel='stylesheet';v68css.href='release-v68.css?v=68';document.head.append(v68css);const v68js=document.createElement('script');v68js.src='release-v68.js?v=68';document.head.append(v68js);
})();
