(()=>{
 'use strict';
 if(window.__btvReleaseV33)return;window.__btvReleaseV33=true;
 const q=s=>document.querySelector(s),sb=window.btvSupabase;let sending=false;
 function buildChat(){let panel=q('#ziburFloatPanel');if(panel)return panel;panel=document.createElement('aside');panel.id='ziburFloatPanel';panel.className='ziburFloatPanel';panel.hidden=true;panel.setAttribute('aria-label','Ask Zibur chat');panel.innerHTML='<header class="ziburFloatHead"><div class="ziburFloatMark">Z</div><div><b>Ask Zibur</b><small>Journey guidance without leaving this page</small></div><button type="button" aria-label="Close floating chat">×</button></header><div class="ziburFloatChat" aria-live="polite"><article class="ziburFloatMessage">Hi, I’m Zibur. What would you like help with today?</article></div><form class="ziburFloatForm"><label class="sr" for="ziburFloatQuestion">Ask Zibur</label><input id="ziburFloatQuestion" maxlength="1500" placeholder="Ask about your journey…" autocomplete="off"><button aria-label="Send message">↑</button><small class="ziburFloatNote">General guidance only. Verify official, legal, immigration and clinical decisions.</small></form>';document.body.append(panel);panel.querySelector('.ziburFloatHead button').onclick=()=>toggle(false);panel.querySelector('form').onsubmit=send;return panel}
 function toggle(force){const panel=buildChat(),show=force??panel.hidden;panel.hidden=!show;document.body.classList.toggle('zibur-float-open',show);q('#btvPlatformOpen')?.setAttribute('aria-expanded',String(show));if(show)setTimeout(()=>q('#ziburFloatQuestion')?.focus(),30)}window.BTVFloatingZiburToggle=toggle;
 function bubble(text,user=false,thinking=false){const box=q('.ziburFloatChat'),a=document.createElement('article');a.className='ziburFloatMessage'+(user?' user':'')+(thinking?' thinking':'');a.textContent=text;box.append(a);box.scrollTop=box.scrollHeight;return a}
 function context(){try{return typeof window.ziburContext==='function'?window.ziburContext():{profile:JSON.parse(localStorage.getItem('btv-profile')||'null'),journey:JSON.parse(localStorage.getItem('btv-v1')||'{}')}}catch{return{}}}
 async function send(event){event.preventDefault();if(sending)return;const input=q('#ziburFloatQuestion'),button=q('.ziburFloatForm button'),question=input.value.trim();if(!question)return;sending=true;input.value='';input.disabled=true;if(button)button.disabled=true;bubble(question,true);const wait=bubble('Zibur is preparing your answer…',false,true);let history=[];try{history=JSON.parse(localStorage.getItem('btv-zibur-history')||'[]');if(!Array.isArray(history))history=[]}catch{}let answer='';try{if(!sb)throw Error('The secure Zibur service is unavailable.');const timeout=new Promise((_,reject)=>setTimeout(()=>reject(Error('Zibur took too long to respond. Please try again.')),25000));const result=await Promise.race([sb.functions.invoke('zibur-gemini',{body:{question,history:history.slice(-8),context:context()}}),timeout]);if(result.error)throw result.error;answer=String(result.data?.answer||'').trim();if(!answer)throw Error('Zibur did not return an answer.')}catch(error){console.warn('Zibur request failed',error);answer=window.BTVZiburFallback?.answer(question,context())||'Zibur is temporarily unavailable. Please try again in a moment.'}wait.textContent=answer;wait.classList.remove('thinking');history.push({role:'user',content:question},{role:'assistant',content:answer});try{localStorage.setItem('btv-zibur-history',JSON.stringify(history.slice(-16)))}catch{}const messages=q('.ziburFloatChat')?.querySelectorAll('.ziburFloatMessage');if(messages?.length>24)[...messages].slice(0,messages.length-24).forEach(x=>x.remove());sending=false;input.disabled=false;if(button)button.disabled=false;input.focus()}
 function wireFloating(){const button=q('#btvPlatformOpen');if(!button)return;button.dataset.floatChatReady='yes';button.setAttribute('aria-controls','ziburFloatPanel');if(!button.hasAttribute('aria-expanded'))button.setAttribute('aria-expanded','false');button.onclick=event=>{event.preventDefault();event.stopPropagation();toggle()}}
 function wire(){wireFloating()}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',wire,{once:true}):wire();
})();
